import { existsSync } from "node:fs";
import { mkdir, readFile, rename, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import type { ProjectMetadata } from "../../packages/registry/src/schema";
import { copyDirectory, repoRoot, writeJson } from "../project-utils";
import type { FactoryBlueprint } from "./blueprint";
import {
  renderApp,
  renderBrief,
  renderEval,
  renderReadme,
  renderScenario,
  renderSpec,
  renderStyles
} from "./templates";

export type ScaffoldOptions = {
  root?: string;
  templateRoot?: string;
  failAfterBlueprint?: boolean;
};

function projectMetadata(blueprint: FactoryBlueprint): ProjectMetadata {
  return {
    id: blueprint.slug,
    name: blueprint.name,
    status: "prototype",
    type: "demo",
    runtime: "static-artifact",
    summary: blueprint.pitch,
    tags: blueprint.tags,
    projectRoot: `projects/${blueprint.slug}`,
    entry: { kind: "iframe", path: `/runs/${blueprint.slug}/index.html` },
    docs: {
      brief: "brief.md",
      spec: "spec.md",
      eval: "eval.md",
      readme: "README.md",
      changelog: "changelog.md"
    },
    assets: {},
    commands: {
      dev: `pnpm --filter ${blueprint.slug} dev`,
      build: `pnpm --filter ${blueprint.slug} build`,
      test: `pnpm --filter ${blueprint.slug} test`
    }
  };
}

export async function readSavedBlueprint(projectRoot: string) {
  return JSON.parse(await readFile(path.join(projectRoot, "data", "factory-blueprint.json"), "utf8"));
}

export async function writeProjectAtomically(
  blueprint: FactoryBlueprint,
  prompt: string,
  source: string,
  options: ScaffoldOptions = {}
) {
  const root = options.root ?? repoRoot;
  const projectsRoot = path.join(root, "projects");
  const finalRoot = path.join(projectsRoot, blueprint.slug);
  const templateRoot = options.templateRoot ?? path.join(repoRoot, "templates", "vite-react-project");
  const stagingRoot = path.join(
    projectsRoot,
    `.${blueprint.slug}.factory-${process.pid}-${Date.now()}-${Math.random().toString(16).slice(2)}`
  );

  if (existsSync(finalRoot)) throw new Error(`Project already exists: projects/${blueprint.slug}`);
  await mkdir(projectsRoot, { recursive: true });

  try {
    await copyDirectory(templateRoot, stagingRoot);
    await mkdir(path.join(stagingRoot, "data"), { recursive: true });
    await writeJson(path.join(stagingRoot, "data", "factory-blueprint.json"), blueprint);
    if (options.failAfterBlueprint) throw new Error("injected scaffold failure");

    await writeJson(path.join(stagingRoot, "project.json"), projectMetadata(blueprint));
    await writeJson(path.join(stagingRoot, "app", "package.json"), {
      name: blueprint.slug,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: {
        dev: "vite --host 127.0.0.1",
        build: "tsc && vite build",
        lint: "tsc --noEmit",
        test: "tsc --noEmit"
      },
      dependencies: {
        "@types/react": "^18.3.18",
        "@types/react-dom": "^18.3.5",
        "@vitejs/plugin-react": "^4.3.4",
        react: "^18.3.1",
        "react-dom": "^18.3.1",
        typescript: "^5.7.3",
        vite: "^6.0.7"
      }
    });

    const indexPath = path.join(stagingRoot, "app", "index.html");
    const indexHtml = (await readFile(indexPath, "utf8")).replace("Template Project", blueprint.name);
    await writeFile(indexPath, indexHtml, "utf8");

    await Promise.all([
      writeFile(path.join(stagingRoot, "brief.md"), renderBrief(blueprint), "utf8"),
      writeFile(path.join(stagingRoot, "spec.md"), renderSpec(blueprint), "utf8"),
      writeFile(path.join(stagingRoot, "eval.md"), renderEval(blueprint), "utf8"),
      writeFile(path.join(stagingRoot, "README.md"), renderReadme(blueprint), "utf8"),
      writeFile(path.join(stagingRoot, "changelog.md"), `# Changelog\n\n- Generated by AI Prototype Factory (${source}).\n`, "utf8"),
      writeFile(path.join(stagingRoot, "app", "src", "App.tsx"), renderApp(blueprint), "utf8"),
      writeFile(path.join(stagingRoot, "app", "src", "styles.css"), renderStyles(blueprint.theme), "utf8"),
      writeFile(path.join(stagingRoot, "tests", "e2e", "scenario.mjs"), renderScenario(blueprint), "utf8")
    ]);
    await mkdir(path.join(stagingRoot, "prompts"), { recursive: true });
    await writeFile(
      path.join(stagingRoot, "prompts", "initial-request.md"),
      `# Initial Request\n\n${prompt}\n\n## Blueprint source\n\n${source}\n`,
      "utf8"
    );

    // Atomic publication: concurrent same-slug runs race only at rename; neither can delete the winner.
    await rename(stagingRoot, finalRoot);
    return finalRoot;
  } catch (error) {
    await rm(stagingRoot, { recursive: true, force: true });
    throw error;
  }
}
