'use strict';
(()=>{
const $=id=>document.getElementById(id),T=THREE;
const canvas=$('game');let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});}catch(e){$('description').textContent='WebGL을 시작하지 못했습니다. 최신 데스크톱 브라우저에서 하드웨어 가속을 켜고 다시 열어주세요.';throw e;}
renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.autoClear=false;
const scene=new T.Scene();scene.background=new T.Color('#8c929f');scene.fog=new T.FogExp2('#89919c',.034);
const cam=new T.PerspectiveCamera(78,1,.06,130);cam.rotation.order='YXZ';
scene.add(new T.HemisphereLight('#cbd2dc','#1a1e29',1.7));let sunlight=new T.DirectionalLight('#d5dbe1',1.65);sunlight.position.set(-15,40,20);scene.add(sunlight);
const gunScene=new T.Scene(),gunCam=new T.PerspectiveCamera(62,1,.01,10);gunScene.add(new T.HemisphereLight('#ffffff','#293346',2.5));let gl=new T.DirectionalLight('#ffffff',2.5);gl.position.set(-2,3,4);gunScene.add(gl);
let world,level=1,totalCash=0,state='title',yaw=0,pitch=0,clock=0,shake=0,recoil=0,flash=0,damageFlash=0,msgTime=0,msg='',bob=0,mouseHeld=false,aimDown=false,muted=false,wallMeshes=[],enemyMeshes=[],itemMeshes=[],debris=[],decals=[],dynamic=new T.Group();scene.add(dynamic);
const casings=[];let ads=0,reloadPhase=-1,kick=0,kickVelocity=0,swayX=0,swayY=0,cycleTime=0,hitPause=0,hitMarker=0;let keys={},firstStart=true,gunGroup=new T.Group();gunScene.add(gunGroup);let hammer,gunCylinder,muzzle;
const geo=new T.BoxGeometry(1,1,1),sphereGeo=new T.IcosahedronGeometry(1,1);
const colors={boundary:[40,45,53],rock:[90,98,111],wood:[69,73,83],trunk:[34,39,49],concrete:[148,156,143],brick:[116,71,53],steel:[46,65,65],red:[91,18,28],gold:[169,137,57],crate:[102,78,46],plaster:[156,145,112],floor:[92,102,91]};
const mats={};
function texture(kind){const n=64,d=new Uint8Array(n*n*4),c=colors[kind];let seed=31;for(let y=0;y<n;y++)for(let x=0;x<n;x++){seed=(seed*1664525+1013904223)>>>0;let v=(seed/4294967296-.5)*30;let line=false;
 if(kind==='brick')line=y%16<2||(x+(Math.floor(y/16)%2)*16)%32<2;
 else if(kind==='steel')line=x%8<2||y%32<2;
 else if(kind==='red')v+=Math.sin(x*.8)*Math.sin(y*.8)*13;
 else if(kind==='crate')line=x<4||x>59||y<4||y>59||Math.abs(x-y)<3;
 else if(kind==='floor')line=x%32<2||y%32<2;
 else line=y%32<2||x%32<1;
 let i=(y*n+x)*4;for(let k=0;k<3;k++)d[i+k]=HC.clamp(c[k]+v-(line?40:0),0,255);d[i+3]=255;}
 let tex=new T.DataTexture(d,n,n,T.RGBAFormat);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.magFilter=tex.minFilter=T.NearestFilter;tex.needsUpdate=true;return tex;}
for(let key in colors)mats[key]=new T.MeshLambertMaterial({map:texture(key)});
const mat=(c)=>new T.MeshLambertMaterial({color:c});const black=mat('#151c21'),metal=mat('#d8dddf'),darkmetal=mat('#394246'),gold=mat('#c0c6ce'),leather=mat('#3b231b'),skin=mat('#171d27'),red=mat('#8b2434');
function box(x,y,z,w,h,d,m,parent=dynamic){let o=new T.Mesh(geo,m);o.position.set(x,y,z);o.scale.set(w,h,d);parent.add(o);return o;}
function cylinder(x,y,z,r,h,m,parent=dynamic,sides=10){let o=new T.Mesh(new T.CylinderGeometry(r,r,h,sides),m);o.position.set(x,y,z);parent.add(o);return o;}
function orb(x,y,z,r,m,parent=dynamic){let o=new T.Mesh(sphereGeo,m);o.position.set(x,y,z);o.scale.setScalar(r);parent.add(o);return o;}
function sign(text,x,y,z,w,color='#b8ded6',rotation=0){let c=document.createElement('canvas');c.width=512;c.height=96;let ctx=c.getContext('2d');ctx.fillStyle='#182829';ctx.fillRect(0,0,512,96);ctx.strokeStyle=color;ctx.lineWidth=4;ctx.strokeRect(5,5,502,86);ctx.font='bold 43px monospace';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,256,63);let t=new T.CanvasTexture(c);t.magFilter=T.NearestFilter;let o=new T.Mesh(new T.PlaneGeometry(w,w*96/512),new T.MeshBasicMaterial({map:t,side:T.DoubleSide}));o.position.set(x,y,z);o.rotation.y=rotation;dynamic.add(o);return o;}
function enemyModel(e){let g=new T.Group(),coat=mat(e.boss?'#a9afb5':'#acb7bf');let torso=box(0,1.12,0,.58,.8,.35,coat,g);box(0,.71,0,.58,.13,.4,leather,g);box(0,.71,-.22,.14,.12,.04,gold,g);let head=orb(0,1.83,0,.24,skin,g);box(0,1.87,-.205,.32,.06,.05,black,g);box(0,1.71,-.2,.22,.1,.06,leather,g);cylinder(0,2.05,0,.38,.05,black,g);cylinder(0,2.15,0,.23,.2,black,g);
 let legs=[];for(let s of [-1,1]){let l=new T.Group();l.position.set(s*.18,.74,0);box(0,-.29,0,.21,.57,.24,black,l);box(0,-.64,-.06,.24,.16,.38,leather,l);g.add(l);legs.push(l);let arm=box(s*.43,1.19,-.12,.2,.58,.22,coat,g);arm.rotation.x=-.6;orb(s*.4,1.02,-.35,.13,skin,g);}box(.24,1.2,-.53,.16,.16,.63,darkmetal,g);box(.24,1.31,-.77,.04,.08,.03,metal,g);if(e.boss){box(0,1.27,-.19,.4,.5,.08,gold,g);g.scale.setScalar(1.18);}let warning=orb(.24,1.34,-.82,.12,new T.MeshBasicMaterial({color:'#ead8d4'}),g);warning.visible=false;g.userData={enemy:e,head,legs,warning,coat};dynamic.add(g);return g;}
function weaponModel(){const previous=gunGroup.userData.model;if(previous){const geometries=new Set(),materials=new Set();previous.traverse(o=>{if(o.geometry)geometries.add(o.geometry);if(o.material)materials.add(o.material);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());}gunGroup.clear();const g=DFWeapon.create(T,world?.weapon||0,{suppressed:$('suppressor').checked,laser:$('laser').checked});gunGroup.add(g);hammer=g.userData.hammer;gunCylinder=null;muzzle=g.userData.muzzle;gunGroup.userData.model=g;}

function build(){const persistent=new Set([...Object.values(mats),black,metal,darkmetal,gold,leather,skin,red]);const geometries=new Set(),materials=new Set();dynamic.traverse(o=>{if(o.isInstancedMesh)o.dispose();if(o.geometry&&o.geometry!==geo&&o.geometry!==sphereGeo)geometries.add(o.geometry);if(o.material&&!persistent.has(o.material))materials.add(o.material);});geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());while(dynamic.children.length)dynamic.remove(dynamic.children[0]);wallMeshes=[];enemyMeshes=[];itemMeshes=[];debris=[];decals=[];
 box(0,-.18,0,180,.3,180,mat('#5b6470'));box(0,-.012,13,8,.035,38,mat('#808a96'));box(3,-.008,-13,11,.04,29,mat('#6d7783'));
 // Tall, densely layered conifers are real scene geometry. The dither pass creates the coarse tonal texture.
 const trunkGeo=new T.CylinderGeometry(.16,.34,1,6),leafGeo=new T.ConeGeometry(1,1,7,1),forest=new T.InstancedMesh(trunkGeo,mat('#242b38'),180),leaves=new T.InstancedMesh(leafGeo,mat('#18212d'),1080);let dummy=new T.Object3D();let randSeed=196;
 function rnd(){randSeed=(randSeed*1664525+1013904223)>>>0;return randSeed/4294967296;}
 for(let i=0;i<180;i++){let x=(rnd()-.5)*115,z=(rnd()-.5)*140-15;if(Math.abs(x)<7&&z>-29&&z<30)x+=(x<0?-1:1)*12;let h=9+rnd()*19;dummy.position.set(x,h/2,z);dummy.rotation.set(0,rnd()*6,0);dummy.scale.set(.7+rnd(),h,.7+rnd());dummy.updateMatrix();forest.setMatrixAt(i,dummy.matrix);for(let j=0;j<6;j++){let radius=(6-j)*(.45+rnd()*.15);dummy.position.set(x+(rnd()-.5)*.35,h*.28+j*h*.11,z);dummy.rotation.set((rnd()-.5)*.07,rnd()*6,(rnd()-.5)*.07);dummy.scale.set(radius,h*.32,radius*.85);dummy.updateMatrix();leaves.setMatrixAt(i*6+j,dummy.matrix);}}dynamic.add(forest,leaves);
 // Broken bark and low branches frame the left side of the start view, matching the reference's dark foreground mass.
 for(let i=0;i<17;i++){let z=20-i*2.8,x=-7-(i%3);let h=11+(i%5)*2;cylinder(x,h/2,z,.24,h,mat('#101724'),dynamic,7);for(let j=0;j<4;j++){let branch=box(x+1.6,1.8+j*1.5,z,3.5,.12,.14,mat('#0d1520'));branch.rotation.z=.19;}}
 for(let w of world.walls){let o;if(w.kind==='rock'){o=orb(w.x,w.h*.45,w.z,1,mats.rock);o.scale.set(w.w*.56,w.h,w.d*.6);}else if(w.kind==='trunk'){o=cylinder(w.x,w.h/2,w.z,.4,w.h,mats.trunk);}else o=box(w.x,(w.y||0)+w.h/2,w.z,w.w,w.h,w.d,mats[w.kind]);o.userData={kind:'wall',id:w.id};if(w.kind==='boundary')o.visible=false;wallMeshes.push(o);}
 // Mossy boulders and uneven rubble establish terrain depth without bright decoration.
 for(let i=0;i<85;i++){let x=(rnd()-.5)*65,z=(rnd()-.5)*90;if(Math.abs(x)<4)continue;let rock=orb(x,.08,z,.2+rnd()*.85,mat(i%2?'#4a5361':'#7c8490'));rock.scale.y=.5;}
 // Ruined relay at the target: pale concrete and black openings in the mist.
 for(let x of [-5,5]){box(x,2.1,-30,.5,4.2,3,mat('#858b94'));box(x,4.4,-30,1,.3,3.3,mat('#373f4c'));}box(0,4.6,-31,11,.5,1,mat('#818995'));for(let y=1;y<17;y+=3){box(0,y,-36,.15,3,.15,mat('#354050'));box(-1,y,-36,.08,3,.08,mat('#354050'));let br=box(-.5,y,-36,1.6,.06,.06,mat('#354050'));br.rotation.z=.9;}
 let pad=cylinder(0,.04,25,2.7,.08,mat('#bec7ce'),dynamic,16);let r=new T.Mesh(new T.TorusGeometry(2.7,.03,4,32),new T.MeshBasicMaterial({color:'#dce2e5'}));r.rotation.x=Math.PI/2;r.position.set(0,.11,25);dynamic.add(r);
 world.enemies.forEach(e=>enemyMeshes.push(enemyModel(e)));syncItems();weaponModel();
}

function syncItems(){world.pickups.forEach((it,i)=>{if(itemMeshes[i])return;let g=new T.Group();g.position.set(it.x,0,it.z);if(it.type==='barrel'){cylinder(0,.72,0,.55,1.4,mats.red,g,12);for(let y of [.2,1.17])cylinder(0,y,0,.565,.09,black,g,12);box(0,.77,.56,.5,.43,.015,gold,g);}else if(it.type==='bounty'){orb(0,.65,0,.3,gold,g);cylinder(0,.35,0,.36,.09,black,g);let light=new T.PointLight('#bbc8d9',4,5);g.add(light);}else{box(0,.38,0,.7,.5,.6,it.type==='health'?mat('#ddd9c6'):mat('#355954'),g);if(it.type==='health'){box(0,.64,0,.1,.01,.37,red,g);box(0,.64,0,.38,.01,.1,red,g);}else box(0,.65,0,.5,.015,.38,gold,g);}g.userData={kind:it.type==='barrel'?'barrel':'item',id:i};dynamic.add(g);itemMeshes[i]=g;});}
function resetPresentation(){keys={};mouseHeld=false;aimDown=false;ads=0;kick=0;kickVelocity=0;recoil=0;shake=0;flash=0;damageFlash=0;hitPause=0;hitMarker=0;swayX=0;swayY=0;cycleTime=0;reloadPhase=-1;for(let c of casings){gunScene.remove(c.mesh);c.mesh.geometry.dispose();c.mesh.material.dispose();}casings.length=0;}
function start(newGame=false){resetPresentation();if(newGame||firstStart||!world||state==='dead'){level=newGame?1:level;world=new HC.Mission(level,Number($('difficulty').value));yaw=0;pitch=0;build();}if(state==='won'){level++;world=new HC.Mission(level,Number($('difficulty').value));world.player.armor=0;build();yaw=0;pitch=0;}
 state='playing';$('overlay').style.display='none';firstStart=false;initAudio();try{canvas.requestPointerLock()?.catch(()=>tell('마우스 잠금 불가: 화살표 키로 조준할 수 있습니다',5));}catch(e){tell('화살표 키로 조준할 수 있습니다',5);}tell('중계소의 표적을 추적하세요. SPACE 회피 · R 타이밍 장전',6);}
function pause(){if(state!=='playing')return;state='paused';keys={};mouseHeld=false;aimDown=false;document.exitPointerLock?.();$('overlay').style.display='grid';$('start').textContent='계속하기';$('restart').hidden=false;$('stats').textContent='';}
function end(win){resetPresentation();state=win?'won':'dead';keys={};mouseHeld=false;document.exitPointerLock?.();$('overlay').style.display='grid';$('description').textContent=win?'계약 완료. 안개를 뚫고 살아 돌아왔습니다. 다음 계약에서도 정확한 사격과 회피 타이밍이 중요합니다.':'계약 실패. 표적은 아직 살아 있습니다. 장전을 마친 뒤 엄폐를 이용해 다시 도전하세요.';$('stats').textContent=`${Math.floor(world.time)}초 · ${world.kills} 처치 · ${world.style} STYLE · ${Math.round(world.hits/Math.max(1,world.shots)*100)}% 명중`;$('start').textContent=win?'다음 계약':'다시 도전';$('restart').hidden=false;if(win){totalCash+=world.cash;try{localStorage.setItem('deadfreight-best',JSON.stringify({cash:totalCash,level}));}catch(e){}}}
function tell(s,t=2.4){msg=s;msgTime=t;$('message').textContent=s;}
let audio;
function initAudio(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch(e){}}
function tone(freq,duration=.1,type='square',vol=.06){if(!audio||!$('sound').checked)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*.25),audio.currentTime+duration);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function noise(duration=.13,volume=.15){if(!audio||!$('sound').checked)return;let b=audio.createBuffer(1,audio.sampleRate*duration,audio.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3);let s=audio.createBufferSource();s.buffer=b;let g=audio.createGain();g.gain.value=volume;s.connect(g);g.connect(audio.destination);s.start();}
const ray=new T.Raycaster();
function shoot(){if(state!=='playing')return;if(!$('manual').checked&&!world.cocked)world.cycle();ray.setFromCamera(new T.Vector2(0,0),cam);let targets=wallMeshes.filter((m,i)=>world.walls[i].alive).concat(enemyMeshes.filter((m,i)=>world.enemies[i].alive),itemMeshes.filter((m,i)=>world.pickups[i]?.alive&&world.pickups[i].type==='barrel'));let hits=ray.intersectObjects(targets,true),hit=null;if(hits.length){let h=hits[0],obj=h.object;while(!obj.userData.kind&&!obj.userData.enemy&&obj.parent)obj=obj.parent;if(obj.userData.enemy){let e=obj.userData.enemy;hit={kind:'enemy',id:e.id,head:h.point.y>(e.boss?1.95:1.58)};}else hit={kind:obj.userData.kind,id:obj.userData.id};if(world.fire(hit))spawnParticles(h.point.x,h.point.y,h.point.z,hit.kind==='enemy'?'#a50721':'#c7b783',hit.kind==='enemy'?18:8);}else world.fire(null);}
function ejectCase(){let mesh=new T.Mesh(new T.CylinderGeometry(.009,.009,.035,6),new T.MeshStandardMaterial({color:'#b8bdc2',metalness:.7,roughness:.35}));let g=gunGroup.userData.model;mesh.position.set(.105,.06,-.04);g.updateMatrixWorld(true);g.localToWorld(mesh.position);gunScene.add(mesh);casings.push({mesh,velocity:new T.Vector3(.8+Math.random()*.4,.7+Math.random()*.4,.2),life:1.1});while(casings.length>16){let old=casings.shift().mesh;gunScene.remove(old);old.geometry.dispose();old.material.dispose();}}
function plankDebris(event){for(let i=0;i<9;i++){let o=new T.Mesh(geo,mats.wood);o.scale.set(.1+Math.random()*.15,.4+Math.random()*.7,.1);o.position.set(event.x+(Math.random()-.5),.3+Math.random()*2,event.z);dynamic.add(o);debris.push({o,v:new T.Vector3((Math.random()-.5)*6,1+Math.random()*4,(Math.random()-.5)*6),t:2.5});}}
function releaseEffect(o){dynamic.remove(o);if(o.geometry!==geo&&o.geometry!==sphereGeo)o.geometry?.dispose();let shared=o.userData.effectMaterial;if(shared&&--shared.refs===0)shared.mat.dispose();}
function spawnParticles(x,y,z,c,n=14,power=4){let material=new T.MeshBasicMaterial({color:c}),shared={mat:material,refs:n};for(let i=0;i<n;i++){let o=new T.Mesh(geo,material);o.userData.effectMaterial=shared;o.scale.setScalar(.025+Math.random()*.1);o.position.set(x,y,z);dynamic.add(o);debris.push({o,v:new T.Vector3((Math.random()-.5)*power,Math.random()*power,(Math.random()-.5)*power),t:.6+Math.random()*.7});}while(debris.length>240)releaseEffect(debris.shift().o);}
function splat(x,z){let o=new T.Mesh(new T.CircleGeometry(.55+Math.random()*.45,9),new T.MeshBasicMaterial({color:'#4e0d1b',transparent:true,opacity:.85}));o.userData.effectMaterial={mat:o.material,refs:1};o.rotation.x=-Math.PI/2;o.position.set(x,.025,z);o.scale.x=1.5;dynamic.add(o);decals.push(o);if(decals.length>45)releaseEffect(decals.shift());}
function events(){for(let e of world.events){switch(e.type){case'shot':ejectCase();flash=$('suppressor').checked?.024:.055;recoil=1;kickVelocity+=world.weapon===1?4.9:3.5;shake=.024;noise($('suppressor').checked?.07:.14,(world.weapon===1?.28:.12)*($('suppressor').checked?.55:1));tone(world.weapon===1?75:140,.16,'sawtooth',$('suppressor').checked?.07:.12);break;case'dash':tone(110,.12,'triangle',.04);shake=.025;break;case'perfect':tone(1000,.12,'triangle',.06);tell('PERFECT / 30% DAMAGE',1.4);break;case'mistime':tone(90,.13,'square',.03);tell('장전 타이밍 실패',1);break;case'warning':tone(680,.08,'sine',.03);break;case'cycle':cycleTime=.24;tone(670,.045,'triangle',.05);recoil=.3;break;case'reload':reloadPhase=-1;aimDown=false;tell('장전 중…',2);noise(.2,.025);break;case'loaded':tone(780,.045);tell('장전 완료',1);break;case'needcycle':tell('Q: 해머를 당기세요',1.3);break;case'empty':tone(320,.04,'triangle');tell('R: 탄약을 장전하세요',1.3);break;case'hurt':damageFlash=.42;shake=.025;break;case'blood':hitMarker=.14;tone(e.head?940:95,.055,'triangle',.035);break;case'kill':if(enemyMeshes[e.id])enemyMeshes[e.id].userData.deathTime=clock;hitPause=.045;hitMarker=.25;spawnParticles(e.x,1.3,e.z,'#850c24',30,5);splat(e.x,e.z);tone(220,.14,'triangle',.045);if(e.boss)tell('표적 제거. E로 금빛 증표를 회수하세요',5);break;case'break':plankDebris(e);hitPause=.025;spawnParticles(e.x,e.y+1,e.z,'#a99975',24,5);shake=.12;noise(.25,.11);break;case'explosion':spawnParticles(e.x,.9,e.z,'#e4dfd1',40,8);shake=.2;noise(.5,.26);tone(65,.4,'sawtooth',.16);break;case'enemyshot':spawnParticles(e.x,1.3,e.z,'#e1b34a',3,2);tone(200,.06,'square',.017);break;case'pickup':tone(800,.16,'triangle',.04);tell(e.kind==='bounty'?'증표 회수. 착륙장으로 돌아가 E로 탈출하세요':e.kind==='health'?'체력 회복':e.kind==='armor'?'방탄 장비 획득':'탄약 획득',4);break;case'win':end(true);break;}}
 world.events=[];syncItems();}
function update(dt){clock+=dt;if(state==='playing'){
 let simulationDt=hitPause>0?dt*.12:dt;hitPause=Math.max(0,hitPause-dt);world.tick(simulationDt);let speed=(world.player.dash>0?18:ads>.5?2.8:keys.ShiftLeft||keys.ShiftRight?7.5:4.8)*dt;let forward=(keys.KeyW?1:0)-(keys.KeyS?1:0),strafe=(keys.KeyD?1:0)-(keys.KeyA?1:0);if(forward&&strafe){forward*=.707;strafe*=.707;}world.move((-Math.sin(yaw)*forward+Math.cos(yaw)*strafe)*speed,(-Math.cos(yaw)*forward-Math.sin(yaw)*strafe)*speed);if(keys.ArrowLeft)yaw+=dt*1.8;if(keys.ArrowRight)yaw-=dt*1.8;if(keys.ArrowUp)pitch=HC.clamp(pitch+dt,-.85,.85);if(keys.ArrowDown)pitch=HC.clamp(pitch-dt,-.85,.85);if(forward||strafe)bob+=dt*(speed/dt)*1.8;else bob*=.95;if(mouseHeld&&world.weapon===2)shoot();if(!$('manual').checked&&!world.cocked&&world.cooldown===0)world.cycle();events();if(world.player.hp<=0)end(false);
 }
 ads+=((aimDown&&state==='playing'&&world.reload<=0?1:0)-ads)*Math.min(1,dt*13);cam.fov=78-ads*19;cam.updateProjectionMatrix();kickVelocity+=(-kick*185-kickVelocity*22)*dt;kick+=kickVelocity*dt;cycleTime=Math.max(0,cycleTime-dt);swayX*=Math.exp(-dt*12);swayY*=Math.exp(-dt*12);hitMarker=Math.max(0,hitMarker-dt);$('crosshair').style.transform='translate(-50%,-50%) rotate(45deg) scale('+(hitMarker>0?3:1)+')';recoil=Math.max(0,recoil-dt*7);damageFlash=Math.max(0,damageFlash-dt);shake=Math.max(0,shake-dt*.6);msgTime-=dt;if(msgTime<=0)$('message').textContent='';
 if(world){cam.position.set(world.player.x,1.67+Math.sin(bob)*.035+(Math.random()-.5)*shake,world.player.z);cam.rotation.set(pitch+kick*.10+(Math.random()-.5)*shake,yaw,(Math.random()-.5)*shake*.3);wallMeshes.forEach((o,i)=>o.visible=world.walls[i].alive&&world.walls[i].kind!=='boundary');enemyMeshes.forEach((o,i)=>{let e=world.enemies[i];o.position.set(e.x,0,e.z);o.rotation.y=Math.atan2(world.player.x-e.x,world.player.z-e.z)+Math.PI;let deathAge=clock-(o.userData.deathTime??-100);o.visible=e.alive||deathAge<1.25;o.position.y=e.alive?0:-Math.min(.75,deathAge*.6);o.rotation.z=e.alive?0:Math.min(1.4,deathAge*2.4);o.userData.coat.emissive.setHex(e.hit>0?0x9099aa:0);o.userData.warning.visible=e.windup>0;o.userData.warning.scale.setScalar(e.windup>0?.12+.09*Math.sin(clock*30):.12);if(e.alert&&e.alive){o.userData.legs.forEach((l,j)=>l.rotation.x=Math.sin(clock*8+j*Math.PI)*.3);}o.scale.setScalar((e.boss?1.18:1)*(e.hit>0?1.04:1));});itemMeshes.forEach((o,i)=>{let it=world.pickups[i];o.visible=it.alive;if(it.type!=='barrel'){o.rotation.y=clock;o.position.y=Math.sin(clock*2+i)*.08;}});
 let g=gunGroup.userData.model;if(g){
 const v=g.userData,rp=world.reload>0?1-world.reload/Math.max(.1,world.reloadDuration):0;
 const reloadTilt=world.reload>0?Math.sin(Math.max(0,rp)*Math.PI):0;
 g.position.set(.16*(1-ads)+Math.sin(bob*.5)*.006*(1-ads)+swayX*.009*(1-ads),-.19+ads*.055+Math.sin(bob)*.012*(1-ads*.85)-kick*.036-reloadTilt*.09,-.55+ads*.10+kick*.11);
 g.rotation.set(.22*(1-ads)+.01*ads+kick*.38+swayY*.014*(1-ads)-reloadTilt*.19,.45*(1-ads)-reloadTilt*.16,-.09*(1-ads)+kick*.09+Math.sin(bob)*.008*(1-ads)-reloadTilt*.31);
 v.slide.position.z=recoil>.48?.064*Math.sin((1-recoil)/.52*Math.PI):0;
 v.hammer.rotation.x=world.cocked?-.7:0;v.trigger.rotation.x=-recoil*.35;v.index.rotation.x=-recoil*.18+reloadTilt*.3;v.index.rotation.y=reloadTilt*.27;
 v.support.position.set(-reloadTilt*.065,-reloadTilt*.27,reloadTilt*.13);
 v.support.rotation.z=-reloadTilt*.35;if(world.reload>0){let phase=Math.floor(rp*4);if(phase>reloadPhase){reloadPhase=phase;tone([430,210,660,820][Math.min(3,phase)],.045,'triangle',.035);noise(.035,.025);}}v.magazine.position.y=rp>0&&rp<.68?-Math.sin(rp/.68*Math.PI)*.28:0;
 if(cycleTime>0){let t=Math.sin(cycleTime/.24*Math.PI);v.support.position.y+=t*.11;v.support.position.z-=t*.1;v.slide.position.z+=t*.055;}
 }hud();
 }else{cam.position.set(0,2,24);cam.rotation.set(0,Math.sin(clock*.08)*.18,0);}
 for(let p of debris){p.t-=dt;p.v.y-=dt*9;p.o.position.addScaledVector(p.v,dt);p.o.rotation.x+=dt*4;p.o.rotation.z+=dt*3;if(p.o.position.y<.07){p.o.position.y=.07;p.v.y*=-.25;p.v.x*=.9;p.v.z*=.9;}}debris=debris.filter(p=>{if(p.t<=0){releaseEffect(p.o);return false;}return true;});$('damage').style.opacity=damageFlash;$('crt').style.display=$('crtsetting').checked?'block':'none';
 laserLine.visible=laserDot.visible=$('laser').checked&&state==='playing'&&world.reload<=0;if(laserLine.visible){cam.updateMatrixWorld();ray.setFromCamera(new T.Vector2(0,0),cam);let hits=ray.intersectObjects(wallMeshes.filter((m,i)=>world.walls[i].alive).concat(enemyMeshes.filter((m,i)=>world.enemies[i].alive),itemMeshes.filter((m,i)=>world.pickups[i]?.alive&&world.pickups[i].type==='barrel')),true);let end=hits.length?hits[0].point:ray.ray.at(45,new T.Vector3());let viewmodel=gunGroup.userData.model;viewmodel.updateMatrixWorld(true);gunCam.updateMatrixWorld();let projected=viewmodel.localToWorld(viewmodel.userData.laserEmitter.clone()).project(gunCam);let origin=new T.Vector3(projected.x,projected.y,.5).unproject(cam).sub(cam.position).normalize().multiplyScalar(.45).add(cam.position);let arr=laserGeometry.attributes.position.array;origin.toArray(arr,0);end.toArray(arr,3);laserGeometry.attributes.position.needsUpdate=true;laserGeometry.computeBoundingSphere();laserDot.position.copy(end);}
 shotMeshes.forEach((m,i)=>{let p=world?.projectiles[i];m.visible=!!p;if(p){m.position.set(p.x,1.4,p.z);m.scale.set(1,1,2.8);}});for(let i=casings.length-1;i>=0;i--){let c=casings[i];c.life-=dt;c.velocity.y-=dt*3.8;c.mesh.position.addScaledVector(c.velocity,dt);c.mesh.rotation.x+=dt*13;c.mesh.rotation.z+=dt*9;if(c.life<=0){gunScene.remove(c.mesh);c.mesh.geometry.dispose();c.mesh.material.dispose();casings.splice(i,1);}}renderer.setRenderTarget(target);renderer.clear();renderer.render(scene,cam);renderer.clearDepth();renderer.render(gunScene,gunCam);if(flash>0){flashMesh.visible=true;flashMesh.position.copy(muzzle||new T.Vector3());gunGroup.userData.model.localToWorld(flashMesh.position);flashMesh.scale.setScalar(.1+Math.random()*.12);flashMesh.rotation.z=Math.random()*6;renderer.render(flashScene,gunCam);}else flashMesh.visible=false;renderer.setRenderTarget(null);renderer.clear();postMaterial.uniforms.time.value=clock;renderer.render(postScene,postCamera);flash=Math.max(0,flash-dt);
}
const laserGeometry=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3()]);const laserLine=new T.Line(laserGeometry,new T.LineBasicMaterial({color:'#784b56',transparent:true,opacity:.38}));scene.add(laserLine);const laserDot=new T.Mesh(new T.SphereGeometry(.035,7,5),new T.MeshBasicMaterial({color:'#bd8291'}));scene.add(laserDot);
const shotMeshes=[];for(let i=0;i<32;i++){let m=new T.Mesh(new T.SphereGeometry(.08,5,4),new T.MeshBasicMaterial({color:'#f3eeee'}));m.visible=false;scene.add(m);shotMeshes.push(m);}
const target=new T.WebGLRenderTarget(640,360,{minFilter:T.NearestFilter,magFilter:T.NearestFilter});const postScene=new T.Scene(),postCamera=new T.OrthographicCamera(-1,1,1,-1,0,1);
const postMaterial=new T.ShaderMaterial({uniforms:{frame:{value:target.texture},time:{value:0}},vertexShader:'varying vec2 vUv; void main(){vUv=uv;gl_Position=vec4(position,1.0);}',fragmentShader:`precision highp float; varying vec2 vUv; uniform sampler2D frame; uniform float time;
float bayer(vec2 p){int x=int(mod(p.x,4.0)),y=int(mod(p.y,4.0));if(y==0){if(x==0)return 0.;if(x==1)return 8.;if(x==2)return 2.;return 10.;}if(y==1){if(x==0)return 12.;if(x==1)return 4.;if(x==2)return 14.;return 6.;}if(y==2){if(x==0)return 3.;if(x==1)return 11.;if(x==2)return 1.;return 9.;}if(x==0)return 15.;if(x==1)return 7.;if(x==2)return 13.;return 5.;}
void main(){vec2 p=floor(vUv*vec2(640.,360.));vec3 col=texture2D(frame,vUv).rgb;float lum=dot(col,vec3(.2126,.7152,.0722));lum=pow(lum,.72);float grit=fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);float d=(bayer(p)/16.-.5)*.25+(grit-.5)*.1;float v=lum+d;vec3 outc;if(v<.20)outc=vec3(.024,.035,.058);else if(v<.40)outc=vec3(.23,.26,.32);else if(v<.69)outc=vec3(.52,.55,.61);else outc=vec3(.83,.86,.86);float red=max(0.,col.r-max(col.g,col.b));outc=mix(outc,vec3(.43,.27,.31),smoothstep(.045,.14,red)*.75);gl_FragColor=vec4(outc,1.);}`});postScene.add(new T.Mesh(new T.PlaneGeometry(2,2),postMaterial));
const flashScene=new T.Scene(),flashMesh=new T.Mesh(new T.OctahedronGeometry(1,0),new T.MeshBasicMaterial({color:'#ffe7a0',transparent:true,opacity:.96}));flashScene.add(flashMesh);
function hud(){let p=world.player;$('hp').textContent=Math.ceil(p.hp);$('armor').textContent=Math.ceil(p.armor);$('healthfill').style.width=p.hp+'%';$('staminafill').style.width=p.stamina+'%';$('style').textContent=world.combo>1?world.combo+' CHAIN / '+world.style:world.style+' STYLE';$('reloadmeter').style.display=world.reload>0?'block':'none';$('reloadcursor').style.left=(1-world.reload/Math.max(.1,world.reloadDuration))*100+'%';$('ammo').textContent=String(world.ammo[world.weapon]).padStart(2,'0');$('reserve').textContent=' / '+world.reserve[world.weapon];$('weapon').textContent=['IRON SIX / REVOLVER','BREACH / SHOTGUN','TWIN / SMG'][world.weapon];let count=world.ammo[world.weapon];$('rounds').innerHTML=Array.from({length:world.weapon===2?12:[6,2][world.weapon]},(_,i)=>`<i class="${i<(world.weapon===2?Math.ceil(count/2):count)?'':'empty'}"></i>`).join('');$('objective').textContent=world.bounty?'증표 확보 · 착륙장으로 돌아가 E로 탈출':world.enemies.at(-1).alive?'계약 0'+level+' · 안개 속 중계소의 표적을 제거':'표적 제거 · 금빛 증표 가까이에서 E';let near=world.pickups.find(it=>it.alive&&it.type!=='barrel'&&Math.hypot(it.x-p.x,it.z-p.z)<2.5);$('hint').textContent=near?'[ E ] '+({health:'구급상자',armor:'방탄 장비',ammo:'탄약',bounty:'현상금 증표'})[near.type]:world.bounty&&Math.hypot(p.x,p.z-25)<3.5?'[ E ] 탈출':' ';if($('minimap').style.display==='block')drawMap();}
function drawMap(){let c=$('minimap').getContext('2d');c.clearRect(0,0,140,170);c.fillStyle='#718689';for(let w of world.walls)if(w.alive)c.fillRect(70+w.x*2-w.w,80+w.z*2-w.d,w.w*2,w.d*2);c.fillStyle='#f3bb4c';for(let e of world.enemies)if(e.alive){c.fillRect(68+e.x*2,78+e.z*2,4,4);}c.fillStyle='#49d4e3';c.beginPath();c.arc(70+world.player.x*2,80+world.player.z*2,3,0,Math.PI*2);c.fill();c.strokeStyle='#fff';c.beginPath();c.moveTo(70+world.player.x*2,80+world.player.z*2);c.lineTo(70+world.player.x*2-Math.sin(yaw)*9,80+world.player.z*2-Math.cos(yaw)*9);c.stroke();}
function resize(){let w=Math.min(innerWidth-24,(innerHeight-24)*16/9),h=w*9/16;renderer.setSize(640,360,false);canvas.style.width=w+'px';canvas.style.height=h+'px';canvas.style.left=(innerWidth-w)/2+'px';canvas.style.top=(innerHeight-h)/2+'px';cam.aspect=gunCam.aspect=16/9;cam.updateProjectionMatrix();gunCam.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();
$('laser').onchange=weaponModel;$('suppressor').onchange=weaponModel;$('start').onclick=()=>start();$('restart').onclick=()=>{state='title';start(true);};$('fullscreen').onclick=()=>{document.documentElement.requestFullscreen?.().catch(()=>tell('브라우저 메뉴에서 전체 화면을 선택하세요'));};
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape')pause();if(state!=='playing')return;if(e.code==='KeyL'){$('laser').checked=!$('laser').checked;weaponModel();}if(e.code==='Space')world.dash();if(e.code==='KeyQ')world.cycle();if(e.code==='KeyR')world.load();if(e.code==='KeyE')world.interact();if(e.code==='KeyF')shoot();if(e.code==='KeyM')$('minimap').style.display=$('minimap').style.display==='block'?'none':'block';if(/^Digit[123]$/.test(e.code)){world.switchWeapon(Number(e.code.at(-1))-1);hammer=null;weaponModel();}});
window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing')pause();});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&state==='playing'){swayX=HC.clamp(swayX+e.movementX*.014,-1,1);swayY=HC.clamp(swayY+e.movementY*.014,-1,1);yaw-=e.movementX*.0024;pitch=HC.clamp(pitch-e.movementY*.0024,-1.05,1.05);}});canvas.addEventListener('mousedown',e=>{if(state!=='playing')return;if(e.button===0){mouseHeld=true;shoot();}if(e.button===2)aimDown=true;});window.addEventListener('mouseup',e=>{if(e.button===0)mouseHeld=false;if(e.button===2)aimDown=false;});canvas.addEventListener('contextmenu',e=>e.preventDefault());
world=new HC.Mission(1);build();let previous=performance.now();function frame(now){let dt=Math.min(.05,(now-previous)/1000);previous=now;update(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.addEventListener('error',e=>{$('notice').textContent='실행 오류: '+e.message;});
})();
