'use strict';
(()=>{
const $=id=>document.getElementById(id),T=THREE;
const canvas=$('game');let renderer;
try{renderer=new T.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});}catch(e){$('description').textContent='WebGL을 시작하지 못했습니다. 최신 데스크톱 브라우저에서 하드웨어 가속을 켜고 다시 열어주세요.';throw e;}
renderer.setPixelRatio(1);renderer.outputColorSpace=T.SRGBColorSpace;renderer.autoClear=false;
const scene=new T.Scene();scene.background=new T.Color('#8fa3a0');scene.fog=new T.FogExp2('#9dafa7',.021);
const cam=new T.PerspectiveCamera(78,1,.06,130);cam.rotation.order='YXZ';
scene.add(new T.HemisphereLight('#dfefe0','#402b29',2.3));let sunlight=new T.DirectionalLight('#ffe8bf',2.6);sunlight.position.set(-15,40,20);scene.add(sunlight);
const gunScene=new T.Scene(),gunCam=new T.PerspectiveCamera(62,1,.01,10);gunScene.add(new T.HemisphereLight('#ffffff','#293346',2.5));let gl=new T.DirectionalLight('#ffffff',2.5);gl.position.set(-2,3,4);gunScene.add(gl);
let world,level=1,totalCash=0,state='title',yaw=0,pitch=0,clock=0,shake=0,recoil=0,flash=0,damageFlash=0,msgTime=0,msg='',bob=0,mouseHeld=false,aimDown=false,muted=false,wallMeshes=[],enemyMeshes=[],itemMeshes=[],debris=[],decals=[],dynamic=new T.Group();scene.add(dynamic);
let keys={},firstStart=true,gunGroup=new T.Group();gunScene.add(gunGroup);let hammer,gunCylinder,muzzle;
const geo=new T.BoxGeometry(1,1,1),sphereGeo=new T.IcosahedronGeometry(1,1);
const colors={concrete:[148,156,143],brick:[116,71,53],steel:[46,65,65],red:[91,18,28],gold:[169,137,57],crate:[102,78,46],plaster:[156,145,112],floor:[92,102,91]};
const mats={};
function texture(kind){const n=64,d=new Uint8Array(n*n*4),c=colors[kind];let seed=31;for(let y=0;y<n;y++)for(let x=0;x<n;x++){seed=(seed*1664525+1013904223)>>>0;let v=(seed/4294967296-.5)*30;let line=false;
 if(kind==='brick')line=y%16<2||(x+(Math.floor(y/16)%2)*16)%32<2;
 else if(kind==='steel')line=x%8<2||y%32<2;
 else if(kind==='red')v+=Math.sin(x*.8)*Math.sin(y*.8)*13;
 else if(kind==='crate')line=x<4||x>59||y<4||y>59||Math.abs(x-y)<3;
 else if(kind==='floor')line=x%32<2||y%32<2;
 else line=y%32<2||x%32<1;
 let i=(y*n+x)*4;for(let k=0;k<3;k++)d[i+k]=HC.clamp(c[k]+v-(line?40:0),0,255);d[i+3]=255;}
 let tex=new T.DataTexture(d,n,n,T.RGBAFormat);tex.colorSpace=T.SRGBColorSpace;tex.wrapS=tex.wrapT=T.RepeatWrapping;tex.magFilter=tex.minFilter=T.NearestFilter;tex.needsUpdate=true;return tex;}
for(let key in colors)mats[key]=new T.MeshLambertMaterial({map:texture(key)});
const mat=(c)=>new T.MeshLambertMaterial({color:c});const black=mat('#151c21'),metal=mat('#969b96'),darkmetal=mat('#394246'),gold=mat('#bea053'),leather=mat('#3b231b'),skin=mat('#a56b50'),red=mat('#8b2434');
function box(x,y,z,w,h,d,m,parent=dynamic){let o=new T.Mesh(geo,m);o.position.set(x,y,z);o.scale.set(w,h,d);parent.add(o);return o;}
function cylinder(x,y,z,r,h,m,parent=dynamic,sides=10){let o=new T.Mesh(new T.CylinderGeometry(r,r,h,sides),m);o.position.set(x,y,z);parent.add(o);return o;}
function orb(x,y,z,r,m,parent=dynamic){let o=new T.Mesh(sphereGeo,m);o.position.set(x,y,z);o.scale.setScalar(r);parent.add(o);return o;}
function sign(text,x,y,z,w,color='#b8ded6',rotation=0){let c=document.createElement('canvas');c.width=512;c.height=96;let ctx=c.getContext('2d');ctx.fillStyle='#182829';ctx.fillRect(0,0,512,96);ctx.strokeStyle=color;ctx.lineWidth=4;ctx.strokeRect(5,5,502,86);ctx.font='bold 43px monospace';ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,256,63);let t=new T.CanvasTexture(c);t.magFilter=T.NearestFilter;let o=new T.Mesh(new T.PlaneGeometry(w,w*96/512),new T.MeshBasicMaterial({map:t,side:T.DoubleSide}));o.position.set(x,y,z);o.rotation.y=rotation;dynamic.add(o);return o;}
function enemyModel(e){let g=new T.Group(),coat=mat(e.boss?'#81293e':'#405358');let torso=box(0,1.12,0,.58,.8,.35,coat,g);box(0,.71,0,.58,.13,.4,leather,g);box(0,.71,-.22,.14,.12,.04,gold,g);let head=orb(0,1.83,0,.24,skin,g);box(0,1.87,-.205,.32,.06,.05,black,g);box(0,1.71,-.2,.22,.1,.06,leather,g);cylinder(0,2.05,0,.38,.05,black,g);cylinder(0,2.15,0,.23,.2,black,g);
 let legs=[];for(let s of [-1,1]){let l=new T.Group();l.position.set(s*.18,.74,0);box(0,-.29,0,.21,.57,.24,black,l);box(0,-.64,-.06,.24,.16,.38,leather,l);g.add(l);legs.push(l);let arm=box(s*.43,1.19,-.12,.2,.58,.22,coat,g);arm.rotation.x=-.6;orb(s*.4,1.02,-.35,.13,skin,g);}box(.24,1.2,-.53,.16,.16,.63,darkmetal,g);box(.24,1.31,-.77,.04,.08,.03,metal,g);if(e.boss){box(0,1.27,-.19,.4,.5,.08,gold,g);g.scale.setScalar(1.18);}g.userData={enemy:e,head,legs};dynamic.add(g);return g;}
function weaponModel(){gunGroup.clear();let g=new T.Group();gunGroup.add(g);let w=world?.weapon||0;
 if(w===0){box(0,-.09,.02,.12,.3,.14,leather,g).rotation.x=-.3;box(0,.06,-.03,.15,.19,.35,metal,g);gunCylinder=cylinder(0,.09,-.03,.105,.18,darkmetal,g,12);gunCylinder.rotation.x=Math.PI/2;for(let i=0;i<6;i++){let a=i*Math.PI/3;let c=cylinder(Math.sin(a)*.073,.09+Math.cos(a)*.073,-.129,.023,.012,black,g);c.rotation.x=Math.PI/2;}let barrel=cylinder(0,.14,-.34,.043,.43,metal,g,8);barrel.rotation.x=Math.PI/2;box(0,.194,-.36,.028,.04,.4,metal,g);let hole=cylinder(0,.14,-.558,.028,.004,black,g);hole.rotation.x=Math.PI/2;hammer=box(0,.21,.13,.045,.08,.035,darkmetal,g);let ring=new T.Mesh(new T.TorusGeometry(.085,.014,5,12),metal);ring.position.set(0,-.06,-.07);ring.rotation.y=Math.PI/2;g.add(ring);box(.075,-.15,.14,.16,.22,.21,skin,g);box(.1,-.3,.21,.21,.3,.25,leather,g);muzzle=new T.Vector3(0,.14,-.58);}
 else if(w===1){box(0,-.13,.2,.17,.2,.45,leather,g);box(0,.015,-.02,.18,.17,.5,darkmetal,g);for(let x of [-.055,.055]){let b=cylinder(x,.08,-.48,.045,.75,metal,g,8);b.rotation.x=Math.PI/2;}box(0,-.04,-.43,.17,.15,.28,leather,g);box(0,.14,-.83,.025,.06,.03,gold,g);box(.08,-.2,.16,.15,.23,.2,skin,g);muzzle=new T.Vector3(0,.08,-.88);}
 else {for(let side of [-1,1]){let s=new T.Group();s.position.set(side*.23,0,0);box(0,0,-.1,.17,.22,.55,darkmetal,s);box(0,.13,-.1,.12,.04,.4,gold,s);box(0,-.22,.02,.11,.35,.16,black,s);box(0,-.12,.25,.15,.22,.13,skin,s);let b=cylinder(0,.025,-.5,.045,.32,metal,s);b.rotation.x=Math.PI/2;for(let z=-.3;z<0;z+=.05)box(.088,.025,z,.012,.06,.025,black,s);g.add(s);}muzzle=new T.Vector3(.23,.025,-.7);}
 g.position.set(w===2?0:.27,-.23,-.55);g.rotation.y=w===2?0:-.08;gunGroup.userData.model=g;}
function build(){while(dynamic.children.length)dynamic.remove(dynamic.children[0]);wallMeshes=[];enemyMeshes=[];itemMeshes=[];debris=[];decals=[];
 let f=box(0,-.16,0,54,.3,67,mats.floor);f.material=mats.floor.clone();f.material.map=mats.floor.map.clone();f.material.map.repeat.set(24,30);f.material.map.needsUpdate=true;
 // Street paving and inset sidewalks.
 box(0,.012,14,11,.025,34,mat('#626d68'));for(let x of [-5.7,5.7])box(x,.11,14,.28,.22,34,mat('#b5b6a1'));
 for(let z=0;z<27;z+=5)box(0,.036,z,.14,.015,2.8,mat('#c1b47a'));
 for(let w of world.walls){let m=mats[w.kind].clone();m.map=m.map.clone();m.map.repeat.set(w.w/2,w.h/2);m.map.needsUpdate=true;let o=box(w.x,(w.y||0)+w.h/2,w.z,w.w,w.h,w.d,m);o.userData={kind:'wall',id:w.id};wallMeshes.push(o);}
 // Industrial facade detail and vent machinery.
 for(let side of [-1,1])for(let z=-25;z<=26;z+=5){let x=side*22.92;for(let y of [3,6.5,10]){box(x,y,z,.08,1.6,2.7,black);box(x-side*.06,y+.15,z,.1,.08,2.7,metal);box(x-side*.1,y,z,.12,1.65,.07,metal);}box(x-side*.2,.8,z,.25,1.6,1.9,mats.steel);}
 for(let z of [7,14])for(let y of [4,7,10]){box(7.93,y,z,.06,1.6,3.2,black);box(7.88,y,z,.08,.07,3.2,metal);}
 for(let z of [9,15]){box(-5.94,4,z,.06,2,2.4,black);box(-5.89,4,z,.07,.08,2.4,metal);}
 for(let z of [-3,12,23]){cylinder(-5.1,3,z,.07,6,darkmetal);box(-4.6,6,z,1.1,.1,.1,darkmetal);box(-4.1,5.95,z,.4,.08,.4,new T.MeshBasicMaterial({color:'#e6ebbc'}));}
 // Distant stepped towers beyond the perimeter.
 for(let i=0;i<9;i++){let x=-42+i*10,h=18+((i*7)%17);box(x,h/2,-48,7,h,8,mat('#8b9d96'));for(let y=3;y<h;y+=2)box(x,y,-43.95,6,.5,.05,mat('#5b7777'));}
 sign('FREIGHT / 08',0,6.7,-8.3,7,'#d0b16e');sign('ORBITAL TRANSIT',14,5.4,18.05,9);sign('NO SAFE PASSAGE',-14,3.5,18.06,9,'#b86849');
 sign('SERVICE ACCESS',0,4.9,-8.27,4,'#d29f71');sign('VOSS ESTATE',0,5.2,-29.85,9,'#e2bc69');
 // Mansion atrium: heavy red panels, brass trim, columns and vaulted ceiling.
 box(0,.06,-23,27,.1,14,mats.red);box(0,.12,-23,5,.05,14,mat('#8b2832'));
 box(0,8,-23,28,.3,17,mat('#382020'));for(let z of [-15,-20,-25,-30])box(0,7.65,z,28,.35,.25,leather);
 for(let x of [-13.85,13.85])for(let z=-16;z>=-28;z-=4){box(x,3,z,.14,4.5,3.3,mats.red);box(x,5.3,z,.2,.1,3.4,gold);for(let dz of [-1.7,1.7])box(x,3,z+dz,.2,4.7,.1,gold);}
 for(let x of [-7,7]){cylinder(x,2.9,-26,.4,5.8,mats.gold);cylinder(x,.2,-26,.65,.4,mats.gold);cylinder(x,5.7,-26,.7,.3,mats.gold);}
 let ring=new T.Mesh(new T.TorusGeometry(1.4,.08,5,18),gold);ring.rotation.x=Math.PI/2;ring.position.set(0,6.1,-22);dynamic.add(ring);cylinder(0,7,-22,.04,2,gold);for(let i=0;i<10;i++){let a=i*Math.PI/5;cylinder(Math.cos(a)*1.4,6.3,-22+Math.sin(a)*1.4,.045,.4,new T.MeshBasicMaterial({color:'#ffdc96'}));}
 let lp=new T.PointLight('#ed993d',12,22,2);lp.position.set(0,5,-23);dynamic.add(lp);
 // Arrival / extraction pad.
 let pad=cylinder(0,.08,25,2.7,.1,mat('#15475a'),dynamic,24);let r=new T.Mesh(new T.TorusGeometry(2.7,.07,4,32),new T.MeshBasicMaterial({color:'#38c3db'}));r.rotation.x=Math.PI/2;r.position.set(0,.15,25);dynamic.add(r);sign('EXTRACT',0,.3,28.4,4,'#39c0e8');
 world.enemies.forEach(e=>enemyMeshes.push(enemyModel(e)));syncItems();weaponModel();
}
function syncItems(){world.pickups.forEach((it,i)=>{if(itemMeshes[i])return;let g=new T.Group();g.position.set(it.x,0,it.z);if(it.type==='barrel'){cylinder(0,.72,0,.55,1.4,mats.red,g,12);for(let y of [.2,1.17])cylinder(0,y,0,.565,.09,black,g,12);box(0,.77,.56,.5,.43,.015,gold,g);}else if(it.type==='bounty'){orb(0,.65,0,.3,gold,g);cylinder(0,.35,0,.36,.09,black,g);let light=new T.PointLight('#e5b44b',4,5);g.add(light);}else{box(0,.38,0,.7,.5,.6,it.type==='health'?mat('#ddd9c6'):mat('#355954'),g);if(it.type==='health'){box(0,.64,0,.1,.01,.37,red,g);box(0,.64,0,.38,.01,.1,red,g);}else box(0,.65,0,.5,.015,.38,gold,g);}g.userData={kind:it.type==='barrel'?'barrel':'item',id:i};dynamic.add(g);itemMeshes[i]=g;});}
function start(newGame=false){if(newGame||firstStart||!world||state==='dead'){level=newGame?1:level;world=new HC.Mission(level,Number($('difficulty').value));yaw=0;pitch=0;build();}if(state==='won'){level++;world=new HC.Mission(level,Number($('difficulty').value));world.player.armor=Math.min(85,35+(level-1)*15);build();yaw=0;pitch=0;}
 state='playing';$('overlay').style.display='none';firstStart=false;initAudio();try{canvas.requestPointerLock()?.catch(()=>tell('마우스 잠금 불가: 화살표 키로 조준할 수 있습니다',5));}catch(e){tell('화살표 키로 조준할 수 있습니다',5);}tell('표적은 저택 안쪽. R 장전 · 우클릭/Q 해머 · E 회수',6);}
function pause(){if(state!=='playing')return;state='paused';keys={};mouseHeld=false;document.exitPointerLock?.();$('overlay').style.display='grid';$('start').textContent='계속하기';$('restart').hidden=false;$('stats').textContent='';}
function end(win){state=win?'won':'dead';keys={};mouseHeld=false;document.exitPointerLock?.();$('overlay').style.display='grid';$('description').textContent=win?'계약 완료. 보상을 받았습니다. 다음 계약에서는 적이 더 강해지고, 방탄 장비가 보강됩니다.':'계약 실패. 표적은 아직 살아 있습니다. 장전을 마친 뒤 엄폐를 이용해 다시 도전하세요.';$('stats').textContent=`${Math.floor(world.time)}초 · ${world.kills} 처치 · ${world.destroyed} 장벽 파괴 · ${Math.round(world.hits/Math.max(1,world.shots)*100)}% 명중`;$('start').textContent=win?'다음 계약':'다시 도전';$('restart').hidden=false;if(win){totalCash+=world.cash;try{localStorage.setItem('deadfreight-best',JSON.stringify({cash:totalCash,level}));}catch(e){}}}
function tell(s,t=2.4){msg=s;msgTime=t;$('message').textContent=s;}
let audio;
function initAudio(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume();}catch(e){}}
function tone(freq,duration=.1,type='square',vol=.06){if(!audio||!$('sound').checked)return;let o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(20,freq*.25),audio.currentTime+duration);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function noise(duration=.13,volume=.15){if(!audio||!$('sound').checked)return;let b=audio.createBuffer(1,audio.sampleRate*duration,audio.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/d.length,3);let s=audio.createBufferSource();s.buffer=b;let g=audio.createGain();g.gain.value=volume;s.connect(g);g.connect(audio.destination);s.start();}
const ray=new T.Raycaster();
function shoot(){if(state!=='playing')return;if(!$('manual').checked&&!world.cocked)world.cycle();ray.setFromCamera(new T.Vector2(0,0),cam);let targets=wallMeshes.filter((m,i)=>world.walls[i].alive).concat(enemyMeshes.filter((m,i)=>world.enemies[i].alive),itemMeshes.filter((m,i)=>world.pickups[i]?.alive&&world.pickups[i].type==='barrel'));let hits=ray.intersectObjects(targets,true),hit=null;if(hits.length){let h=hits[0],obj=h.object;while(!obj.userData.kind&&!obj.userData.enemy&&obj.parent)obj=obj.parent;if(obj.userData.enemy){let e=obj.userData.enemy;hit={kind:'enemy',id:e.id,head:h.point.y>(e.boss?1.95:1.58)};}else hit={kind:obj.userData.kind,id:obj.userData.id};if(world.fire(hit))spawnParticles(h.point.x,h.point.y,h.point.z,hit.kind==='enemy'?'#a50721':'#c7b783',hit.kind==='enemy'?18:8);}else world.fire(null);}
function spawnParticles(x,y,z,c,n=14,power=4){let material=new T.MeshBasicMaterial({color:c});for(let i=0;i<n;i++){let o=new T.Mesh(geo,material);o.scale.setScalar(.025+Math.random()*.1);o.position.set(x,y,z);dynamic.add(o);debris.push({o,v:new T.Vector3((Math.random()-.5)*power,Math.random()*power,(Math.random()-.5)*power),t:.6+Math.random()*.7});}while(debris.length>240)dynamic.remove(debris.shift().o);}
function splat(x,z){let o=new T.Mesh(new T.CircleGeometry(.55+Math.random()*.45,9),new T.MeshBasicMaterial({color:'#4e0d1b',transparent:true,opacity:.85}));o.rotation.x=-Math.PI/2;o.position.set(x,.025,z);o.scale.x=1.5;dynamic.add(o);decals.push(o);if(decals.length>45)dynamic.remove(decals.shift());}
function events(){for(let e of world.events){switch(e.type){case'shot':flash=.065;recoil=1;shake=.05;noise(.12,world.weapon===1?.28:.12);tone(world.weapon===1?75:140,.16,'sawtooth',.12);break;case'cycle':tone(670,.045,'triangle',.05);recoil=.3;break;case'reload':tell('장전 중…',2);noise(.2,.025);break;case'loaded':tone(780,.045);tell('장전 완료',1);break;case'needcycle':tell('우클릭 또는 Q: 해머를 당기세요',1.3);break;case'empty':tone(320,.04,'triangle');tell('R: 탄약을 장전하세요',1.3);break;case'hurt':damageFlash=.42;shake=.025;break;case'kill':spawnParticles(e.x,1.3,e.z,'#850c24',30,5);splat(e.x,e.z);tone(220,.14,'triangle',.045);if(e.boss)tell('표적 제거. E로 금빛 증표를 회수하세요',5);break;case'break':spawnParticles(e.x,e.y+1,e.z,'#a99975',24,5);shake=.12;noise(.25,.11);break;case'explosion':spawnParticles(e.x,.9,e.z,'#ffaf44',40,8);shake=.2;noise(.5,.26);tone(65,.4,'sawtooth',.16);break;case'enemyshot':spawnParticles(e.x,1.3,e.z,'#e1b34a',3,2);tone(200,.06,'square',.017);break;case'pickup':tone(800,.16,'triangle',.04);tell(e.kind==='bounty'?'증표 회수. 착륙장으로 돌아가 E로 탈출하세요':e.kind==='health'?'체력 회복':e.kind==='armor'?'방탄 장비 획득':'탄약 획득',4);break;case'win':end(true);break;}}
 world.events=[];syncItems();}
function update(dt){clock+=dt;if(state==='playing'){
 world.tick(dt);let speed=(keys.ShiftLeft||keys.ShiftRight?7:4.8)*dt;let forward=(keys.KeyW?1:0)-(keys.KeyS?1:0),strafe=(keys.KeyD?1:0)-(keys.KeyA?1:0);if(forward&&strafe){forward*=.707;strafe*=.707;}world.move((-Math.sin(yaw)*forward+Math.cos(yaw)*strafe)*speed,(-Math.cos(yaw)*forward-Math.sin(yaw)*strafe)*speed);if(keys.ArrowLeft)yaw+=dt*1.8;if(keys.ArrowRight)yaw-=dt*1.8;if(keys.ArrowUp)pitch=HC.clamp(pitch+dt,-.85,.85);if(keys.ArrowDown)pitch=HC.clamp(pitch-dt,-.85,.85);if(forward||strafe)bob+=dt*(speed/dt)*1.8;else bob*=.95;if(mouseHeld&&world.weapon===2)shoot();if(!$('manual').checked&&!world.cocked&&world.cooldown===0)world.cycle();events();if(world.player.hp<=0)end(false);
 }
 recoil=Math.max(0,recoil-dt*5);flash=Math.max(0,flash-dt);damageFlash=Math.max(0,damageFlash-dt);shake=Math.max(0,shake-dt*.6);msgTime-=dt;if(msgTime<=0)$('message').textContent='';
 if(world){cam.position.set(world.player.x,1.67+Math.sin(bob)*.035+(Math.random()-.5)*shake,world.player.z);cam.rotation.set(pitch+(Math.random()-.5)*shake,yaw,(Math.random()-.5)*shake*.3);wallMeshes.forEach((o,i)=>o.visible=world.walls[i].alive);enemyMeshes.forEach((o,i)=>{let e=world.enemies[i];o.position.set(e.x,0,e.z);o.rotation.y=Math.atan2(world.player.x-e.x,world.player.z-e.z)+Math.PI;o.visible=e.alive;if(e.alert&&e.alive){o.userData.legs.forEach((l,j)=>l.rotation.x=Math.sin(clock*8+j*Math.PI)*.3);}o.scale.setScalar((e.boss?1.18:1)*(e.hit>0?1.04:1));});itemMeshes.forEach((o,i)=>{let it=world.pickups[i];o.visible=it.alive;if(it.type!=='barrel'){o.rotation.y=clock;o.position.y=Math.sin(clock*2+i)*.08;}});
 let g=gunGroup.userData.model;if(g){g.position.y=-.23+Math.sin(bob)*.015-recoil*.07-(world.reload>0?.15:0);g.position.z=-.55+recoil*.12;g.rotation.x=recoil*.23+(world.reload>0?-.5:0);if(hammer)hammer.rotation.x=world.cocked?-.7:0;}hud();
 }else{cam.position.set(0,2,24);cam.rotation.set(0,Math.sin(clock*.08)*.18,0);}
 for(let p of debris){p.t-=dt;p.v.y-=dt*9;p.o.position.addScaledVector(p.v,dt);p.o.rotation.x+=dt*4;p.o.rotation.z+=dt*3;if(p.o.position.y<.07){p.o.position.y=.07;p.v.y*=-.25;p.v.x*=.9;p.v.z*=.9;}}debris=debris.filter(p=>{if(p.t<=0){dynamic.remove(p.o);return false;}return true;});$('damage').style.opacity=damageFlash;$('crt').style.display=$('crtsetting').checked?'block':'none';
 renderer.clear();renderer.render(scene,cam);renderer.clearDepth();renderer.render(gunScene,gunCam);if(flash>0){flashMesh.visible=true;flashMesh.position.copy(muzzle||new T.Vector3());flashMesh.position.add(gunGroup.userData.model.position);flashMesh.scale.setScalar(.1+Math.random()*.12);flashMesh.rotation.z=Math.random()*6;renderer.render(flashScene,gunCam);}else flashMesh.visible=false;
}
const flashScene=new T.Scene(),flashMesh=new T.Mesh(new T.OctahedronGeometry(1,0),new T.MeshBasicMaterial({color:'#ffe7a0',transparent:true,opacity:.96}));flashScene.add(flashMesh);
function hud(){let p=world.player;$('hp').textContent=Math.ceil(p.hp);$('armor').textContent=Math.ceil(p.armor);$('healthfill').style.width=p.hp+'%';$('ammo').textContent=String(world.ammo[world.weapon]).padStart(2,'0');$('reserve').textContent=' / '+world.reserve[world.weapon];$('weapon').textContent=['IRON SIX / REVOLVER','BREACH / SHOTGUN','TWIN / SMG'][world.weapon];let count=world.ammo[world.weapon];$('rounds').innerHTML=Array.from({length:world.weapon===2?12:[6,2][world.weapon]},(_,i)=>`<i class="${i<(world.weapon===2?Math.ceil(count/2):count)?'':'empty'}"></i>`).join('');$('objective').textContent=world.bounty?'증표 확보 · 착륙장으로 돌아가 E로 탈출':world.enemies.at(-1).alive?'계약 0'+level+' · 저택의 표적을 찾아 제거':'표적 제거 · 금빛 증표 가까이에서 E';let near=world.pickups.find(it=>it.alive&&it.type!=='barrel'&&Math.hypot(it.x-p.x,it.z-p.z)<2.5);$('hint').textContent=near?'[ E ] '+({health:'구급상자',armor:'방탄 장비',ammo:'탄약',bounty:'현상금 증표'})[near.type]:world.bounty&&Math.hypot(p.x,p.z-25)<3.5?'[ E ] 탈출':' ';if($('minimap').style.display==='block')drawMap();}
function drawMap(){let c=$('minimap').getContext('2d');c.clearRect(0,0,140,170);c.fillStyle='#718689';for(let w of world.walls)if(w.alive)c.fillRect(70+w.x*2-w.w,80+w.z*2-w.d,w.w*2,w.d*2);c.fillStyle='#f3bb4c';for(let e of world.enemies)if(e.alive){c.fillRect(68+e.x*2,78+e.z*2,4,4);}c.fillStyle='#49d4e3';c.beginPath();c.arc(70+world.player.x*2,80+world.player.z*2,3,0,Math.PI*2);c.fill();c.strokeStyle='#fff';c.beginPath();c.moveTo(70+world.player.x*2,80+world.player.z*2);c.lineTo(70+world.player.x*2-Math.sin(yaw)*9,80+world.player.z*2-Math.cos(yaw)*9);c.stroke();}
function resize(){let w=innerWidth*.96,h=innerHeight*.96,scale=Math.min(1,640/w);renderer.setSize(Math.max(320,Math.floor(w*scale)),Math.max(200,Math.floor(h*scale)),false);cam.aspect=gunCam.aspect=w/h;cam.updateProjectionMatrix();gunCam.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();
$('start').onclick=()=>start();$('restart').onclick=()=>{state='title';start(true);};$('fullscreen').onclick=()=>{document.documentElement.requestFullscreen?.().catch(()=>tell('브라우저 메뉴에서 전체 화면을 선택하세요'));};
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.repeat)return;if(e.code==='Escape')pause();if(state!=='playing')return;if(e.code==='KeyQ')world.cycle();if(e.code==='KeyR')world.load();if(e.code==='KeyE')world.interact();if(e.code==='KeyF')shoot();if(e.code==='KeyM')$('minimap').style.display=$('minimap').style.display==='block'?'none':'block';if(/^Digit[123]$/.test(e.code)){world.switchWeapon(Number(e.code.at(-1))-1);hammer=null;weaponModel();}});
window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&state==='playing')pause();});document.addEventListener('mousemove',e=>{if(document.pointerLockElement===canvas&&state==='playing'){yaw-=e.movementX*.0024;pitch=HC.clamp(pitch-e.movementY*.0024,-1.05,1.05);}});canvas.addEventListener('mousedown',e=>{if(state!=='playing')return;if(e.button===0){mouseHeld=true;shoot();}if(e.button===2)world.cycle();});window.addEventListener('mouseup',()=>mouseHeld=false);canvas.addEventListener('contextmenu',e=>e.preventDefault());
world=new HC.Mission(1);build();let previous=performance.now();function frame(now){let dt=Math.min(.05,(now-previous)/1000);previous=now;update(dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
window.addEventListener('error',e=>{$('notice').textContent='실행 오류: '+e.message;});
})();
