/* Pure owned-inventory UI; currency actions stay in the profile transaction layer. */
(function(root){
'use strict';
const I=typeof module!=='undefined'&&module.exports?require('./inventory.js'):root.DFInventory;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={weapon:'무기',armor:'방탄',healing:'회복',health:'회복',heal:'회복',throwable:'투척',gadget:'가젯',ammo:'탄약',material:'전리품',loot:'전리품',quest:'증표'};
const button=(text,action,location='',disabled=false)=>'<button type="button" data-action="'+esc(action)+'" data-location="'+esc(location)+'"'+(disabled?' disabled':'')+'>'+esc(text)+'</button>';
const details=s=>s.rounds!==undefined?'장전 '+s.rounds+'발'+(s.chamber!==undefined?' · 약실 '+s.chamber:''):s.durability!==undefined?'방호 '+Math.ceil(s.durability):'수량 '+s.quantity;
function sorted(items,sort='category'){
 const result=[...items],C=I.Catalog;
 result.sort((a,b)=>{let difference=0;if(sort==='value')difference=I.stackValue(b)-I.stackValue(a);else if(sort==='weight')difference=I.stackWeight(b)-I.stackWeight(a);else if(sort==='category')difference=(C[a.itemId].category||'').localeCompare(C[b.itemId].category||'');return difference||C[a.itemId].name.localeCompare(C[b.itemId].name,'ko')||a.uid.localeCompare(b.uid);});return result;
}
function render({profile,inventory,selected=null,sort='category',message='',confirmation=null,canMutate=true}){
 const C=I.Catalog,p=profile,stash=p.stash||[],recovery=p.recovery||[],busy=!canMutate,prepared=new Set(inventory.all().map(x=>x.stack.uid));
 if(p.known===false)return '<header class="inv-header"><h2>보유 보관함</h2></header><p class="home-warning">기존 보관 기록을 읽지 못했습니다. 빈 보관함을 의미하지 않습니다. 기존 데이터를 그대로 보존했으며, 출격 메뉴의 저장 재시도로 다시 확인하세요.</p><footer class="inv-footer">'+button('출격 메뉴로 돌아가기 · Esc','close')+'</footer>';
 const entry=selected?.kind==='recovery'?recovery.find(s=>s.uid===selected.uid):selected?.kind==='stash'?stash.find(s=>s.uid===selected.uid):null;
 const selectedSource=selected?.kind==='recovery'?'recovery':'stash';
 function cards(items,source){return sorted(items,sort).map(s=>{const chosen=selected?.kind===source&&selected.uid===s.uid;return '<button type="button" class="home-item'+(chosen?' selected':'')+'" data-action="select-'+source+'" data-location="'+esc(s.uid)+'" aria-pressed="'+chosen+'"><small>'+esc(labels[C[s.itemId].category]||C[s.itemId].category)+'</small><strong>'+esc(C[s.itemId].name)+'</strong><span>'+esc(details(s))+'</span><span>'+I.stackWeight(s).toFixed(2)+' kg · 가치 '+I.stackValue(s)+'</span>'+(prepared.has(s.uid)?'<em>출격 준비에 포함</em>':'')+'</button>';}).join('');}
 let info='<h3>물품 정보</h3><p>보유 물품을 선택해 비교하고 다음 출격에 준비하세요. 한 묶음이 한 칸을 사용합니다.</p>';
 if(entry){const item=C[entry.itemId],equipped=item.category==='weapon'?inventory.get('weapon:0'):item.category==='armor'?inventory.get('armor'):null;
  info='<h3>'+esc(item.name)+'</h3><p>'+esc(labels[item.category]||item.category)+' · '+esc(details(entry))+'</p><dl><dt>총 무게</dt><dd>'+I.stackWeight(entry).toFixed(2)+' kg</dd><dt>판매 금액</dt><dd>'+I.stackValue(entry)+(entry.issued?' · 보급품':'')+'</dd>'+(item.magazineSize?'<dt>탄창 정원</dt><dd>'+item.magazineSize+'</dd>':'')+(item.heal?'<dt>회복량</dt><dd>'+item.heal+'</dd>':'')+'</dl>';
  if(equipped&&equipped.uid!==entry.uid)info+='<p>준비한 '+esc(C[equipped.itemId].name)+' 대비 무게 '+(I.stackWeight(entry)-I.stackWeight(equipped)).toFixed(2)+' kg</p>';
  info+='<div class="home-actions">'+(selectedSource==='recovery'?button('보관함으로 받기','claim-one',entry.uid,busy||p.available<=0):button(prepared.has(entry.uid)?'이미 출격 준비에 포함':'가방에 준비','take-stash',entry.uid,busy||prepared.has(entry.uid)))+button('이 묶음 판매…','review-sell',entry.uid,busy)+'</div>';
 }
 let confirm='';
 if(confirmation){const q=confirmation,isUpgrade=q.kind==='expand';confirm='<section class="home-confirm" role="region" aria-label="'+(isUpgrade?'보관함 확장 확인':'물품 판매 확인')+'"><h3>'+(isUpgrade?'보관함 확장':'선택한 묶음 판매')+'</h3><p>'+(isUpgrade?q.from+' → '+q.to+'칸 · 비용 '+q.amount:esc(q.name)+' ×'+q.quantity+' · 판매 금액 '+q.amount)+'</p><p>보관 재화 '+q.balance+' → '+(isUpgrade?q.balance-q.amount:q.balance+q.amount)+'</p><p>'+(isUpgrade?'원정 가방의 12칸·30kg 제한은 바뀌지 않습니다.':'이 묶음 전체를 보관함과 출격 준비에서 제외합니다.')+'</p><div class="home-actions">'+button(isUpgrade?'확장 구매 확정':'판매 확정','confirm-home','',busy)+button('취소','cancel-home')+'</div></section>';}
 return '<header class="inv-header"><div><small>DEAD FREIGHT / OWNED INVENTORY</small><h2>보유 보관함</h2><p>이 브라우저에 저장되는 장비와 물품</p></div><div class="home-balance"><small>보관 재화</small><strong>'+p.bank+'</strong></div></header><nav class="home-tabs">'+button('출격 장비','loadout-view')+button('보유 보관함','home-view')+'</nav><p class="inv-message" role="status" aria-live="polite">'+esc(message||'출격하기 전까지 물품은 보관함에 유지됩니다. 판매와 확장은 확인 후 저장됩니다.')+'</p><section class="home-summary"><div><strong>'+p.used+' / '+p.capacity+'칸</strong><p>빈 칸 '+p.available+' · 최대 64칸</p>'+(p.overCapacity?'<p class="home-warning">기존 초과 물품 '+p.overCapacity+'묶음도 보존했습니다.</p>':'')+'</div><div><strong>'+(p.nextCost===null?'최대 확장 완료':p.capacity+' → '+p.nextCapacity+'칸')+'</strong><p>'+(p.nextCost===null?'64칸까지 확장했습니다.':'다음 확장 비용 '+p.nextCost+(p.bank>=p.nextCost?' · 구매 후 잔액 '+(p.bank-p.nextCost):' · 재화 '+(p.nextCost-p.bank)+' 부족'))+'</p>'+button(p.nextCost===null?'최대 단계':p.bank<p.nextCost?'재화 '+(p.nextCost-p.bank)+' 부족':'보관함 확장…','review-expand','',busy||p.nextCost===null||p.bank<p.nextCost)+'</div></section>'+confirm+(recovery.length?'<section class="home-recovery"><h3>회수 대기 '+recovery.length+'묶음</h3><p>보관함에 자리가 없어 안전하게 대기 중입니다. 받기 또는 판매를 마쳐야 새 원정을 시작할 수 있습니다.</p>'+button('빈 칸만큼 받기','claim-all','',busy||p.available<=0)+'<div class="home-grid">'+cards(recovery,'recovery')+'</div></section>':'')+'<div class="home-toolbar"><h3>보유 물품 '+stash.length+'묶음</h3><label>정렬 <select data-action="home-sort">'+[['category','종류'],['name','이름'],['value','가치 높은 순'],['weight','무거운 순']].map(([v,t])=>'<option value="'+v+'"'+(sort===v?' selected':'')+'>'+t+'</option>').join('')+'</select></label></div><div class="home-layout"><section class="home-grid" aria-label="보유 물품">'+cards(stash,'stash')+Array.from({length:Math.max(0,p.capacity-p.used)},(_,i)=>'<div class="home-empty"><small>빈 칸 '+(p.used+i+1)+'</small></div>').join('')+'</section><aside class="inv-details home-details">'+info+'</aside></div><footer class="inv-footer">'+button('출격 장비','loadout-view')+button('출격 메뉴로 돌아가기 · Esc','close')+'</footer>';
}
const api={render,sorted};if(typeof module!=='undefined'&&module.exports)module.exports=api;root.DFStashUI=api;
})(typeof globalThis!=='undefined'?globalThis:this);
