'use strict';
const assert=require('node:assert/strict'),W=require('./world.js');let checks=0;function test(name,fn){fn();checks++;console.log('✓ '+name);}
const d=W.definition;
test('a bounded 340 m region contains five distinct landmarks and two extraction zones',()=>{assert.equal(d.size,340);assert.equal(d.landmarks.length,5);assert.equal(d.extractionZones.length,2);assert.equal(new Set(d.landmarks.map(l=>l.id)).size,5);assert.equal(d.bounds.maxX-d.bounds.minX,340);});
test('deterministic authorship and bounded forest/encounter budgets',()=>{assert.deepEqual(W.createDefinition(),d);assert.ok(d.trees.length>=500&&d.trees.length<=900);assert.ok(d.walls.length<1000);assert.ok(d.enemies.length>=14&&d.enemies.length<=25);assert.ok(d.routes.length>=8);assert.equal(d.enemies.filter(e=>e.boss).length,1);assert.ok(d.enemies.at(-1).boss);});
test('every tree has a matching collision footprint and all IDs are stable',()=>{d.walls.forEach((w,i)=>assert.equal(w.id,i));d.trees.forEach((t,i)=>{const w=d.walls[t.wallId];assert.equal(w.treeIndex,i);assert.equal(w.kind,'trunk');assert.equal(w.x,t.x);assert.equal(w.w,t.r*2);});});
test('trees preserve continuous authored road and landmark clearances',()=>{for(const t of d.trees){assert.ok(W.routeDistance(t.x,t.z)>=3.2);assert.ok(d.landmarks.every(l=>Math.hypot(t.x-l.x,t.z-l.z)>=l.radius+2));}});
const step=1,radius=.45,min=-169,max=169,width=(max-min)/step+1,occupied=new Uint8Array(width*width),seen=new Uint8Array(width*width),distance=new Int32Array(width*width).fill(-1);
const cell=(x,z)=>Math.round((z-min)/step)*width+Math.round((x-min)/step);
for(const w of d.walls){if(w.y>=1.75)continue;const x0=Math.max(0,Math.ceil((w.x-w.w/2-radius-min)/step)),x1=Math.min(width-1,Math.floor((w.x+w.w/2+radius-min)/step)),z0=Math.max(0,Math.ceil((w.z-w.d/2-radius-min)/step)),z1=Math.min(width-1,Math.floor((w.z+w.d/2+radius-min)/step));for(let z=z0;z<=z1;z++)occupied.fill(1,z*width+x0,z*width+x1+1);}
const queue=new Int32Array(width*width);let start=cell(d.spawn.x,d.spawn.z),head=0,tail=1;queue[0]=start;seen[start]=1;distance[start]=0;
while(head<tail){const i=queue[head++],x=i%width,z=(i/width)|0;for(const j of [x>0?i-1:-1,x+1<width?i+1:-1,z>0?i-width:-1,z+1<width?i+width:-1])if(j>=0&&!occupied[j]&&!seen[j]){seen[j]=1;distance[j]=distance[i]+1;queue[tail++]=j;}}
function reachable(p,label){assert.ok(!occupied[cell(p.x,p.z)],`${label} is inside solid collision`);assert.ok(seen[cell(p.x,p.z)],`${label} is unreachable from insertion`);}
test('spawn and every landmark are connected with a .45 m player clearance',()=>{assert.ok(!occupied[start]);for(const l of d.landmarks)reachable(l,l.id);});
test('boss, every encounter, optional cache and both extraction pads are reachable on foot',()=>{for(const [i,e] of d.enemies.entries())reachable(e,'enemy '+i);for(const [i,p] of d.pickups.entries())reachable(p,p.type+' '+i);for(const e of d.extractionZones)reachable(e,e.id);});
test('route waypoints and sampled road centers are connected on foot',()=>{for(const r of d.routes)for(let j=1;j<r.points.length;j++){const a=r.points[j-1],b=r.points[j],n=Math.ceil(Math.hypot(b.x-a.x,b.z-a.z)/3);for(let i=0;i<=n;i++)reachable({x:a.x+(b.x-a.x)*i/n,z:a.z+(b.z-a.z)*i/n},r.id);}});
test('travel is substantial, spawn is safe and route rewards are distributed',()=>{assert.ok(distance[cell(28,-130)]>=270);assert.ok(d.enemies.every(e=>Math.hypot(e.x-d.spawn.x,e.z-d.spawn.z)>60));assert.ok(d.pickups.filter(p=>p.type==='cargo').length>=5);assert.ok(new Set(d.pickups.filter(p=>p.type==='cargo').map(p=>p.value)).size>=4);for(const l of d.landmarks)assert.ok(d.pickups.some(p=>p.type!=='barrel'&&Math.hypot(p.x-l.x,p.z-l.z)<l.radius+10));});
test('movement practice offers real jump cover and a slide-only gap',()=>{assert.ok(d.walls.some(w=>w.vaultable&&w.h<=.9));assert.ok(d.walls.some(w=>w.slideable&&w.y>.72&&w.y<1.75));});
test('populate uses mission APIs without installing gameplay logic',()=>{const m={player:{},walls:[],pickups:[],enemies:[],rand:()=>.5,wall(x,z,w,d,h,kind,destructible,y){const v={id:this.walls.length,x,z,w,d,h,kind,hp:destructible?75:Infinity,y,alive:true};this.walls.push(v);return v;}};assert.equal(W.populate(m),d);assert.equal(m.walls.length,d.walls.length);assert.equal(m.enemies.length,d.enemies.length);assert.deepEqual(m.player,d.spawn);assert.equal(m.extractionZones.length,2);assert.ok(m.extractionZones.every(z=>z.holdTime===6));assert.notEqual(m.enemies[0],d.enemies[0]);assert.notEqual(m.pickups[0],d.pickups[0]);});


const T=require('./vendor/three.min.js'),View=require('./world-view.js'),parent=new T.Group();
const view=View.build({T,parent,world:d});
test('actual Three.js scene keeps 720 trees instanced and static draws bounded',()=>{assert.equal(view.treeMeshes.length,3);assert.equal(view.treeMeshes[0].count,720);assert.equal(view.treeMeshes[1].count,2880);assert.ok(view.stats.visibleMeshes<200,JSON.stringify(view.stats));assert.ok(view.stats.triangles<150000);assert.ok(view.stats.materials<36);assert.ok(view.stats.textures<=28);assert.equal(view.wallMeshes.length,d.walls.length);});
test('world construction emits finite geometry, transforms and instance buffers',()=>{parent.traverse(o=>{assert.ok(o.matrixWorld.elements.every(Number.isFinite));if(o.geometry)assert.ok(o.geometry.attributes.position.array.every(Number.isFinite));if(o.isInstancedMesh)assert.ok(o.instanceMatrix.array.every(Number.isFinite));});});
test('hidden forest proxies retain raycast identity without duplicate rendering',()=>{const t=d.trees[0],proxy=view.wallMeshes[t.wallId];assert.equal(proxy.visible,false);assert.equal(proxy.userData.renderProxy,true);assert.equal(proxy.userData.id,t.wallId);const ray=new T.Raycaster(new T.Vector3(t.x,1,t.z+3),new T.Vector3(0,0,-1)),hits=ray.intersectObject(proxy);assert.ok(hits.length>0);assert.equal(hits[0].object.userData.id,t.wallId);});
test('world surfaces use static object textures and dispose cleanly',()=>{const materialNames=new Set();parent.traverse(o=>{if(o.material)materialNames.add(o.material.name);});assert.ok(materialNames.has('weathered-soil'));assert.ok(materialNames.has('weathered-wood'));assert.ok(materialNames.has('weathered-steel'));view.dispose();assert.equal(parent.children.length,0);});
console.log(`${checks} world checks passed; ${tail} reachable grid cells; relay route ${distance[cell(28,-130)]} m (four-neighbor grid).`);
console.log('Rendererless region budget:',JSON.stringify(view.stats));
