import {CLASSES,BIOMES,RELICS,BUILDINGS,GEAR_NAMES,createMap,defaultSave,sanitizeSave,seeded} from './data.js';
const $=s=>document.querySelector(s),canvas=$('#game'),ctx=canvas.getContext('2d'),W=1280,H=800,T=32,TAU=Math.PI*2;
let save;try{save=sanitizeSave(JSON.parse(localStorage.getItem('emberwatch-save')));}catch{save=defaultSave();}
let pendingResume=!!save.run;
let mode='town',panel=null,paused=false,run=null,p=null,map=null,entities=[],shots=[],loot=[],effects=[],floaters=[],objects=[],time=0,last=0,saveTick=0,uiTick=0,noticeTimer=0,shake=0,hitstop=0,cam={x:0,y:0},keys={},mouse={x:640,y:400,down:false,active:false},seen=[],discovered=[],audio=null,selected=save.classId,inventoryTab='gear',townTime=0;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rnd=(a,b)=>a+Math.random()*(b-a),choice=a=>a[Math.floor(Math.random()*a.length)],cls=()=>CLASSES.find(c=>c.id===save.classId)||CLASSES[0],bio=()=>BIOMES[Math.min(2,Math.floor((run?.floor||0)/2))],hero=()=>save.heroes[save.classId]||(save.heroes[save.classId]={level:1,xp:0,spec:0}),levelXp=l=>50+l*l*14;
function persist(){try{if(!pendingResume)save.run=run?{...run,p:{...p},entities,loot,objects,seen,discovered,shots:[]}:null;localStorage.setItem('emberwatch-save',JSON.stringify(save));$('#saveState').textContent='Saved on this device';}catch{$('#saveState').textContent='Save unavailable';}}
function notify(s){$('#notice').textContent=s;$('#notice').classList.add('show');noticeTimer=3.5;}
function sound(type){if(!save.settings.sound)return;try{audio ||= new AudioContext();if(audio.state==='suspended')audio.resume();let o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);const v={hit:[180,.055,'triangle'],slash:[340,.06,'sawtooth'],coin:[900,.08,'sine'],hurt:[100,.16,'sawtooth'],skill:[420,.2,'triangle'],level:[660,.4,'sine'],die:[70,.5,'triangle'],dash:[240,.07,'sine']}[type]||[300,.1,'sine'];o.type=v[2];o.frequency.setValueAtTime(v[0],audio.currentTime);o.frequency.exponentialRampToValueAtTime(v[0]*.45,audio.currentTime+v[1]);g.gain.setValueAtTime(.05,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+v[1]);o.start();o.stop(audio.currentTime+v[1]);}catch{}}
function stats(){let c=cls(),h=hero(),r={damage:c.damage*(1+.08*save.buildings.forge+.035*(h.level-1)),hp:c.hp+15*save.buildings.chapel+5*(h.level-1),mana:c.mana+10*save.buildings.enchanter,speed:c.speed,armor:Math.floor(h.level/3),crit:.05,critpower:2,haste:0,cooldown:0,dodge:0,spell:.05*save.buildings.enchanter,lifekill:0,gold:0,thorns:0,burn:0,slow:0,revive:0,magnet:0};for(let slot of ['weapon','armor','charm']){let g=save.gear.find(g=>g.id===save.equipped[slot]);if(g){r[g.stat]=(r[g.stat]||0)+g.value;}}
 for(let id of run?.relics||[]){let q=RELICS.find(x=>x.id===id);if(['damage','speed'].includes(q.stat))r[q.stat]*=1+q.value;else r[q.stat]=(r[q.stat]||0)+q.value;}
 if(save.buildings.guild>=1){if(h.spec===0)r.damage*=1.1;else if(h.spec===1){r.hp+=25;r.armor+=2;}else{r.spell+=.2;r.mana+=20;}}return r;}
function newPlayer(){let s=stats();return {x:0,y:0,hp:s.hp,mana:s.mana,angle:0,attack:0,q:0,e:0,dash:0,dashTime:0,invuln:0,potions:2+Math.floor(save.buildings.apothecary/2),vx:0,vy:0,walk:0};}
function beginRun(){pendingResume=false;save.classId=selected;save.runs++;hero();run={seed:Math.floor(Math.random()*1e9),floor:0,relics:[],gold:0,wood:0,stone:0,iron:0,kills:0,seconds:0,bossKills:0,revived:false,ng:save.wins,cleared:[]};p=newPlayer();loadFloor();closePanel();mode='run';notify('The Pinewild awaits. Follow the lanterns.');persist();canvas.focus();}
function loadFloor(){map=createMap(run.seed,run.floor);entities=[];shots=[];loot=[];effects=[];floaters=[];objects=[];seen=Array.from({length:map.h},()=>Array(map.w).fill(false));discovered=Array(map.rooms.length).fill(false);p.x=map.rooms[0].cx*T;p.y=map.rooms[0].cy*T;cam.x=p.x-W/2;cam.y=p.y-H/2;const random=seeded(run.seed+run.floor*912),b=bio();
 map.rooms.forEach((r,i)=>{if(i===0){objects.push({type:'return',x:(r.cx-2)*T,y:r.cy*T});return;}if(i===11&&map.boss){spawnEnemy('boss',r.cx*T,r.cy*T);objects.push({type:'exit',x:(r.cx+3)*T,y:r.cy*T,locked:true});return;}let n=3+Math.floor(random()*3)+Math.floor(run.floor/2);for(let j=0;j<n;j++){let type=b.enemy[Math.floor(random()*b.enemy.length)];spawnEnemy(type,(r.x+2+random()*(r.w-4))*T,(r.y+2+random()*(r.h-4))*T);}if(i%3===1)objects.push({type:'chest',x:(r.cx+2)*T,y:r.cy*T,open:false});if(i===5)objects.push({type:'bird',x:r.cx*T,y:(r.cy+2)*T,used:false});if(i===7)objects.push({type:'shrine',x:r.cx*T,y:(r.cy-2)*T,used:false});if(i===9)objects.push({type:'relic',x:r.cx*T,y:(r.cy+2)*T,used:false});if(i===11&&!map.boss)objects.push({type:'exit',x:(r.cx+3)*T,y:r.cy*T,locked:false});
 if(i>2&&i%2===0)objects.push({type:'trap',x:r.cx*T,y:r.cy*T,phase:random()*3});
 });for(let r of map.rooms){objects.push({type:'torch',x:(r.x+1)*T,y:(r.y+1)*T});objects.push({type:'torch',x:(r.x+r.w-2)*T,y:(r.y+1)*T});for(let k=0;k<2;k++)objects.push({type:'barrel',x:(r.x+1+k)*T,y:(r.y+r.h-2)*T,hp:1});}
 save.bestFloor=Math.max(save.bestFloor,run.floor+1);$('#where').textContent=`${b.name} · ${map.boss?'Guardian floor':'Depth '+(run.floor+1)}`;updateHud();}
function spawnEnemy(type,x,y){const f=1+run.floor*.3+run.ng*.5;let table={rat:[24,92,8,11],bandit:[48,62,12,13],archer:[34,48,11,12],skeleton:[58,55,14,13],mage:[45,42,15,13],knight:[110,40,21,16],imp:[44,100,12,11],boss:[540+run.floor*100,43,23,29]},v=table[type];let e={type,x,y,hp:v[0]*f,max:v[0]*f,speed:v[1],damage:v[2]*f,r:v[3],state:'idle',timer:rnd(.3,1.5),flash:0,slow:0,burn:0,burnTick:0,angle:0,walk:0,attackCount:0,phase:1,active:false};entities.push(e);return e;}
function resumeRun(){pendingResume=false;run=save.run;p=run.p;entities=run.entities||[];loot=run.loot||[];objects=run.objects||[];seen=run.seen;discovered=run.discovered;map=createMap(run.seed,run.floor);shots=[];effects=[];floaters=[];mode='run';closePanel();$('#where').textContent=`${bio().name} · Depth ${run.floor+1}`;notify('Expedition resumed');canvas.focus();}
function clearInput(){keys={};mouse.down=false;}
function showPanel(html,small=false){clearInput();panel=true;$('#overlay').innerHTML=`<section class="panel ${small?'small':''}">${html}</section>`;$('#overlay').classList.add('open');}
function closePanel(){panel=null;$('#overlay').classList.remove('open');$('#overlay').innerHTML='';canvas.focus();}
function bind(id,fn){document.getElementById(id)?.addEventListener('click',fn);}
function townPanel(){pendingResume=false;mode='town';run=null;p=null;$('#where').textContent='Cinderfall refuge';$('#hud').innerHTML='';let c=CLASSES.find(c=>c.id===selected)||CLASSES[0],h=save.heroes[selected]||{level:1,spec:0};showPanel(`<div class="row"><div><div class="eyebrow">Cinderfall refuge</div><h1>CROWN OF CINDERS</h1></div><span class="pill">${save.wins?'New Game +'+save.wins:'A new expedition'}</span></div><p>Choose your hero. Venture into the wilds, gather relics and rebuild the refuge. Your equipment and experience endure between expeditions.</p><div class="grid" id="classes">${CLASSES.map(v=>`<button class="card ${v.id===selected?'selected':''} ${save.bosses<(v.unlock||0)?'locked':''}" data-class="${v.id}" ${save.bosses<(v.unlock||0)?'disabled':''}><span class="glyph" style="color:${v.color}">${v.glyph}</span><h3>${v.name}</h3><span class="muted">${save.bosses<(v.unlock||0)?'Defeat guardian '+v.unlock:'Level '+(save.heroes[v.id]?.level||1)}</span></button>`).join('')}</div><div class="row wrap"><div><h3>${c.name}</h3><p style="margin:0">${c.desc}</p><span class="pill">${c.q}</span><span class="pill">${c.e}</span></div><button class="primary" id="start">Begin expedition</button></div>${save.buildings.guild?`<div class="divider"></div><div class="row wrap"><span class="muted">Specialization · shared mechanical paths</span>${c.specs.map((n,i)=>`<button class="${h.spec===i?'primary':''}" data-spec="${i}">${n}<br><small>${['+10% attacks','+25 HP / +2 armor','+20% skills / +20 mana'][i]}</small></button>`).join('')}</div>`:''}<div class="divider"></div><div class="row wrap"><span class="gold">◈ ${save.gold} gold · ${save.wood} wood · ${save.stone} stone · ${save.iron} iron</span><div><button id="buildings">Rebuild town</button> <button id="equipment">Equipment</button></div></div><p class="muted">Original browser interpretation inspired by Heroes of Hammerwatch II. Solo play. Progress is stored on this device.</p>`);
 document.querySelectorAll('[data-class]').forEach(b=>b.onclick=()=>{selected=b.dataset.class;save.classId=selected;persist();townPanel();});document.querySelectorAll('[data-spec]').forEach(b=>b.onclick=()=>{hero().spec=+b.dataset.spec;persist();townPanel();});bind('start',beginRun);bind('buildings',buildingsPanel);bind('equipment',()=>inventoryPanel(true));}
function buildingsPanel(){showPanel(`<div class="row"><div><div class="eyebrow">A home worth returning to</div><h2>Rebuild Cinderfall</h2></div><button id="back">Back</button></div><p class="gold">◈ ${save.gold} gold · ${save.wood} wood · ${save.stone} stone · ${save.iron} iron</p><div class="grid">${BUILDINGS.map(b=>{let n=save.buildings[b.id],cost=Math.round(b.cost*Math.pow(1.65,n)),wood=b.wood*(n+1),stone=b.stone*(n+1),iron=n>=2?n-1:0,locked=b.id!=='guild'&&n>=2+save.buildings.guild*2,can=n<b.max&&!locked&&save.gold>=cost&&save.wood>=wood&&save.stone>=stone&&save.iron>=iron;return `<div class="card"><span class="glyph">${b.icon}</span><h3>${b.name}</h3><span class="pill">Level ${n} / ${b.max}</span><p>${b.text}</p><p class="gold">${n===b.max?'Fully rebuilt':`${cost} gold · ${wood} wood<br>${stone} stone${iron?' · '+iron+' iron':''}`}</p><button data-upgrade="${b.id}" ${can?'':'disabled'}>${n===b.max?'Complete':locked?'Upgrade Guild Hall':'Build upgrade'}</button></div>`;}).join('')}</div><p class="muted">All town upgrades are shared by your heroes. Guild Hall unlocks specializations and higher building tiers.</p>`);bind('back',townPanel);document.querySelectorAll('[data-upgrade]').forEach(b=>b.onclick=()=>{let v=BUILDINGS.find(x=>x.id===b.dataset.upgrade),n=save.buildings[v.id],cost=Math.round(v.cost*1.65**n);if(save.gold<cost)return;save.gold-=cost;save.wood-=v.wood*(n+1);save.stone-=v.stone*(n+1);if(n>=2)save.iron-=n-1;save.buildings[v.id]++;sound('level');persist();buildingsPanel();notify(v.name+' improved');});}
function inventoryPanel(fromTown=false){showPanel(`<div class="row"><div><div class="eyebrow">Permanent equipment</div><h2>Armory</h2></div><button id="back">${fromTown?'Back':'Resume'}</button></div><p>Equip one weapon, armor and charm. Equipment is kept after death. Equipped bonuses apply immediately.</p><div class="two"><div>${['weapon','armor','charm'].map(slot=>{let g=save.gear.find(x=>x.id===save.equipped[slot]);return `<div class="item-row"><div><span class="eyebrow">${slot}</span><h3>${g?g.name:'Travel-worn '+slot}</h3><p>${g?gearText(g):'No bonus'}</p></div></div>`;}).join('')}<div class="divider"></div><h3>Run trinkets</h3><p>${(run?.relics||[]).map(id=>RELICS.find(r=>r.id===id).name).join(' · ')||'None. Find reliquaries inside the dungeon.'}</p></div><div style="max-height:380px;overflow:auto">${save.gear.length?save.gear.slice().reverse().map(g=>`<div class="item-row"><div><strong class="${g.rarity}">${g.name}</strong><p>${g.slot} · ${gearText(g)}</p></div><button data-equip="${g.id}" ${save.equipped[g.slot]===g.id?'disabled':''}>${save.equipped[g.slot]===g.id?'Equipped':'Equip'}</button></div>`).join(''):'<p>No equipment yet. Open chests and defeat guardians.</p>'}</div></div>`);bind('back',()=>fromTown?townPanel():closePanel());document.querySelectorAll('[data-equip]').forEach(b=>b.onclick=()=>{let g=save.gear.find(g=>g.id===b.dataset.equip);save.equipped[g.slot]=g.id;persist();inventoryPanel(fromTown);sound('coin');});}
function gearText(g){return '+'+(g.stat==='crit'?Math.round(g.value*100)+'%':g.value)+' '+({damage:'attack',hp:'maximum health',armor:'armor',mana:'maximum mana',crit:'critical chance'}[g.stat]);}
function createGear(quality=0){let slot=choice(['weapon','armor','charm']),tier=Math.min(5,Math.floor(run.floor/2)+quality+Math.floor(Math.random()*2)),rarity=tier>=4?'legendary':tier>=2?'epic':tier>=1?'rare':'common',stat=slot==='weapon'?'damage':slot==='armor'?'armor':choice(['hp','mana','crit']),value=stat==='damage'?4+tier*3:stat==='armor'?2+tier:stat==='crit'?.03+tier*.015:15+tier*8;let g={id:'g'+Date.now()+Math.random().toString(36).slice(2,6),slot,stat,value,name:GEAR_NAMES[slot][tier],rarity};save.gear.push(g);if(!save.equipped[slot])save.equipped[slot]=g.id;notify(`Equipment found: ${g.name} · ${gearText(g)}`);persist();return g;}
function relicPanel(){let pool=RELICS.filter(r=>!run.relics.includes(r.id)),options=pool.sort(()=>Math.random()-.5).slice(0,3);if(!options.length){run.gold+=100;notify('The reliquary yields 100 gold');return;}showPanel(`<div class="eyebrow">A gift from a forgotten age</div><h2>Choose a trinket</h2><p>Its power lasts for this expedition.</p><div class="grid" style="grid-template-columns:repeat(${options.length},1fr)">${options.map(r=>`<button class="card" data-relic="${r.id}"><span class="glyph">✦</span><h3>${r.name}</h3><p>${r.text}</p></button>`).join('')}</div>`);document.querySelectorAll('[data-relic]').forEach(b=>b.onclick=()=>{let r=RELICS.find(r=>r.id===b.dataset.relic);run.relics.push(r.id);if(r.stat==='hp')p.hp+=r.value;if(r.stat==='mana')p.mana+=r.value;sound('level');closePanel();notify(r.name+' acquired');persist();});}
function finishRun(won=false,abandon=false){const keep=won?1:Math.min(.85,.6+.05*save.buildings.chapel+.025*save.buildings.treasury),earned={};for(let k of ['gold','wood','stone','iron']){earned[k]=Math.floor(run[k]*keep);save[k]+=earned[k];}save.totalKills+=run.kills;const summary={...run},h=hero();if(won){save.wins++;save.bosses=Math.max(save.bosses,3);}run=null;p=null;save.run=null;persist();mode='town';sound(won?'level':'die');showPanel(`<div class="eyebrow">${won?'The crown is broken':abandon?'Live to fight another day':'Your story is not over'}</div><h1>${won?'DAWN RETURNS':abandon?'BACK TO CINDERFALL':'FALLEN, NOT FORGOTTEN'}</h1><p>${won?'The Hollow King falls, and the refuge sees its first sunrise in years. Stronger foes await in New Game +.':`The refuge brings you home. You retain ${Math.round(keep*100)}% of carried resources. All equipment and experience are safe.`}</p><div class="grid"><div class="card"><h3>${summary.floor+1}</h3><span class="muted">Depth reached</span></div><div class="card"><h3>${summary.kills}</h3><span class="muted">Enemies defeated</span></div><div class="card"><h3>${Math.floor(summary.seconds/60)}m ${Math.floor(summary.seconds%60)}s</h3><span class="muted">Expedition</span></div><div class="card"><h3>Level ${h.level}</h3><span class="muted">${cls().name}</span></div></div><p class="gold">Brought home: ${earned.gold} gold · ${earned.wood} wood · ${earned.stone} stone · ${earned.iron} iron</p><p class="muted">Trinkets return to the dungeon. Your heroes, equipment and town endure.</p><button class="primary" id="returnTown">Return to town</button>`);bind('returnTown',townPanel);}
function solid(x,y,r=11){for(let dy of [-r,r])for(let dx of [-r,r])if(!map.tiles[Math.floor((y+dy)/T)]?.[Math.floor((x+dx)/T)])return true;return false;}
function move(o,dx,dy,r=11){if(!solid(o.x+dx,o.y,r))o.x+=dx;if(!solid(o.x,o.y+dy,r))o.y+=dy;}
function lineClear(a,b){let d=dist(a,b);for(let i=0;i<d;i+=20){let t=i/d;if(solid(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t,2))return false;}return true;}
function burst(x,y,color,n=10,force=80){for(let i=0;i<n;i++)effects.push({type:'particle',x,y,vx:rnd(-force,force),vy:rnd(-force,force),life:rnd(.2,.7),max:.7,color,size:rnd(2,4)});}
function circle(x,y,r,color,life=.35){effects.push({type:'ring',x,y,r,color,life,max:life});}
function floating(x,y,text,color='#f5ddbb'){floaters.push({x,y,text:String(text),color,life:1,max:1});}
function gainXp(amount){let h=hero();h.xp+=amount;const cap=20+save.wins*5;while(h.xp>=levelXp(h.level)&&h.level<cap){h.xp-=levelXp(h.level);h.level++;let s=stats();p.hp=Math.min(s.hp,p.hp+35);p.mana=s.mana;circle(p.x,p.y,80,'#f1ce81',.7);sound('level');notify(`Level ${h.level} · Stronger attacks and +5 maximum health`);}}
function hit(e,damage,knock=0,spell=false){if(e.hp<=0)return;const s=stats(),crit=Math.random()<s.crit;let amount=Math.round(damage*(crit?s.critpower:1));e.hp-=amount;e.flash=.14;if(s.slow)e.slow=2;if(s.burn)e.burn=3;if(knock){let a=Math.atan2(e.y-p.y,e.x-p.x);move(e,Math.cos(a)*knock,Math.sin(a)*knock,e.r*.6);}floating(e.x,e.y-25,amount,crit?'#ffd463':spell?'#99d9ff':'#f1e5d3');burst(e.x,e.y,crit?'#ffd975':'#b55256',crit?10:5);sound('hit');if(e.hp<=0)kill(e);}
function kill(e){if(e.dead)return;e.dead=true;run.kills++;gainXp(e.type==='boss'?120+run.floor*25:7+run.floor*2);let s=stats();p.hp=Math.min(s.hp,p.hp+s.lifekill);burst(e.x,e.y,e.type==='boss'?'#e8b871':'#925859',e.type==='boss'?45:12);const n=e.type==='boss'?18:Math.floor(rnd(1,4));for(let i=0;i<n;i++)loot.push({x:e.x+rnd(-18,18),y:e.y+rnd(-18,18),type:'gold',amount:Math.ceil((e.type==='boss'?8:3)+run.floor),bob:rnd(0,TAU)});if(Math.random()<.38||e.type==='boss')loot.push({x:e.x+12,y:e.y,type:bio().resource,amount:e.type==='boss'?8:1+Math.floor(Math.random()*2),bob:0});if(Math.random()<.09)loot.push({x:e.x-12,y:e.y,type:'health',amount:14,bob:1});if(e.type==='boss'){run.bossKills++;save.bosses=Math.max(save.bosses,Math.floor(run.floor/2)+1);run.cleared.push(run.floor);objects.filter(o=>o.type==='exit').forEach(o=>o.locked=false);createGear(2);p.potions=Math.min(p.potions+1,4);notify(`${bio().boss} defeated · A new hero is available in town`);sound('level');shake=9;objects.push({type:'relic',x:e.x,y:e.y,used:false});persist();}}
function damagePlayer(amount,source){if(p.invuln>0||p.dashTime>0)return;let s=stats();amount=Math.max(1,Math.round(amount-s.armor));p.hp-=amount;p.invuln=.7;shake=6;floating(p.x,p.y-24,'−'+amount,'#ff827b');burst(p.x,p.y,'#cf5c56',10);sound('hurt');if(s.thorns)for(let e of entities)if(e.hp>0&&dist(e,p)<90)hit(e,s.thorns,10,true);if(p.hp<=0){if(s.revive&&!run.revived){run.revived=true;p.hp=s.hp*.5;p.invuln=3;circle(p.x,p.y,120,'#ffd690',1);notify('The Phoenix Feather burns. Rise again.');}else finishRun(false);}}
function projectile(x,y,angle,speed,damage,kind,enemy=false,options={}){shots.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed,damage,kind,enemy,life:options.life||1.5,r:kind==='fire'?7:kind==='soul'?6:4,pierce:options.pierce||0,hit:[],...options});}
function aim(){if(mouse.active)return Math.atan2(mouse.y+cam.y-p.y,mouse.x+cam.x-p.x);let e=entities.filter(e=>e.hp>0&&dist(e,p)<450&&lineClear(p,e)).sort((a,b)=>dist(a,p)-dist(b,p))[0];return e?Math.atan2(e.y-p.y,e.x-p.x):p.angle;}
function attack(){if(p.attack>0||p.dashTime>0)return;let c=cls(),s=stats();p.attack=c.rate/(1+s.haste);p.angle=aim();sound('slash');if(c.kind==='melee'){effects.push({type:'slash',x:p.x,y:p.y,angle:p.angle,r:c.range,life:.18,max:.18,color:c.color});for(let e of entities){let a=Math.atan2(e.y-p.y,e.x-p.x),diff=Math.atan2(Math.sin(a-p.angle),Math.cos(a-p.angle));if(e.hp>0&&dist(e,p)<c.range+e.r&&Math.abs(diff)<1.2&&lineClear(p,e))hit(e,s.damage,12);}for(let o of objects)if(o.type==='barrel'&&!o.broken&&dist(o,p)<c.range+12){o.broken=true;loot.push({x:o.x,y:o.y,type:Math.random()<.6?'gold':bio().resource,amount:2,bob:0});burst(o.x,o.y,'#aa8658',10);}}else projectile(p.x,p.y,p.angle,c.kind==='arrow'?460:330,s.damage,c.kind,false,{life:c.range/(c.kind==='arrow'?460:330),pierce:c.kind==='spark'?2:0});}
function skill(which){let c=cls(),s=stats(),cost=which==='q'?22:34,cd=which==='q'?6:10;if(p[which]>0||p.mana<cost){if(p.mana<cost)notify('Not enough mana');return;}p.mana-=cost;p[which]=cd*(1-Math.min(.65,s.cooldown));p.angle=aim();sound('skill');const power=s.damage*(1+s.spell),near=(r,d,k=20)=>{for(let e of entities)if(e.hp>0&&dist(e,p)<r&&lineClear(p,e))hit(e,power*d,k,true);};
 if(c.id==='warrior'){if(which==='q'){circle(p.x,p.y,120,'#dfc6a5',.45);near(125,2.8,40);}else{let x=p.x+Math.cos(p.angle)*110,y=p.y+Math.sin(p.angle)*110;effects.push({type:'blast',x,y,r:125,color:'#dcaa71',life:.5,max:.5});for(let e of entities)if(e.hp>0&&Math.hypot(e.x-x,e.y-y)<125){hit(e,power*3.8,30,true);e.slow=3;}shake=7;}}
 else if(c.id==='paladin'){if(which==='q'){p.hp=Math.min(s.hp,p.hp+35+s.damage*.5);effects.push({type:'zone',x:p.x,y:p.y,r:100,color:'#dbcc85',life:4,max:4,tick:0,damage:power*.45,heal:true});circle(p.x,p.y,100,'#f3e5a4');}else{projectile(p.x,p.y,p.angle,260,power*4,'hammer',false,{r:14,pierce:8,life:1.5});}}
 else if(c.id==='ranger'){if(which==='q'){for(let i=-2;i<=2;i++)projectile(p.x,p.y,p.angle+i*.13,510,power*1.8,'arrow',false,{pierce:3,life:1});}else{let x=p.x+Math.cos(p.angle)*100,y=p.y+Math.sin(p.angle)*100;effects.push({type:'zone',x,y,r:115,color:'#92b47b',life:6,max:6,tick:0,damage:power*.5,slow:true});}}
 else if(c.id==='wizard'){if(which==='q'){circle(p.x,p.y,150,'#9cdbef',.6);near(150,2.2,25);for(let e of entities)if(dist(e,p)<150)e.slow=5;}else{let d=mouse.active?Math.min(280,Math.hypot(mouse.x+cam.x-p.x,mouse.y+cam.y-p.y)):180,x=p.x+Math.cos(p.angle)*d,y=p.y+Math.sin(p.angle)*d;effects.push({type:'meteor',x,y,r:110,color:'#f3a45d',life:1,max:1,damage:power*6});}}
 else if(c.id==='rogue'){if(which==='q'){for(let i=0;i<12;i++)projectile(p.x,p.y,i*TAU/12,420,power*1.8,'knife',false,{pierce:2,life:.8});}else{p.invuln=2;move(p,Math.cos(p.angle)*125,Math.sin(p.angle)*125);circle(p.x,p.y,95,'#c79edd');near(100,4,10);}}
 else if(c.id==='warlock'){if(which==='q'){let n=entities.filter(e=>e.hp>0&&dist(e,p)<170).length;near(170,2.5,0);p.hp=Math.min(s.hp,p.hp+12*n);circle(p.x,p.y,170,'#8bc5a8');}else effects.push({type:'zone',x:p.x+Math.cos(p.angle)*120,y:p.y+Math.sin(p.angle)*120,r:120,color:'#85af86',life:7,max:7,tick:0,damage:power*.8,slow:true});}
 else if(c.id==='sorcerer'){if(which==='q'){let targets=entities.filter(e=>e.hp>0&&dist(e,p)<300).sort((a,b)=>dist(a,p)-dist(b,p)).slice(0,7),from=p;for(let e of targets){effects.push({type:'bolt',x:from.x,y:from.y,x2:e.x,y2:e.y,color:'#9be9ee',life:.3,max:.3});hit(e,power*2.5,5,true);from=e;}}else effects.push({type:'zone',x:p.x,y:p.y,r:170,color:'#88bed6',life:6,max:6,tick:0,damage:power,storm:true});}}
function dodge(){if(p.dash>0)return;let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0),a=dx||dy?Math.atan2(dy,dx):p.angle;p.dash=1.4*(1-stats().dodge);p.dashTime=.19;p.vx=Math.cos(a)*650;p.vy=Math.sin(a)*650;sound('dash');burst(p.x,p.y,cls().color,8);}
function potion(){if(p.potions<=0){notify('No potions left. Guardians replenish one.');return;}let s=stats();if(p.hp>=s.hp&&p.mana>=s.mana)return;p.potions--;p.hp=Math.min(s.hp,p.hp+s.hp*(.4+.04*save.buildings.apothecary));p.mana=Math.min(s.mana,p.mana+s.mana*.4);circle(p.x,p.y,45,'#a1da94',.6);sound('level');notify('Health and mana restored');}
function interact(){let nearby=objects.filter(o=>!['torch','barrel','trap'].includes(o.type)&&dist(o,p)<64).sort((a,b)=>dist(a,p)-dist(b,p)),o=nearby[0];if(!o){notify('Move closer to a chest, shrine, raven or exit');return;}if(o.type==='chest'){if(o.open)return;o.open=true;for(let i=0;i<7;i++)loot.push({x:o.x+rnd(-30,30),y:o.y+rnd(-25,25),type:i<4?'gold':i===4?'wood':i===5?'stone':bio().resource,amount:i<4?6+run.floor:2,bob:i});if(Math.random()<.55)createGear();sound('coin');}
 if(o.type==='bird'){if(o.used){notify('The courier has already flown');return;}o.used=true;let lines=[];for(let k of ['gold','wood','stone','iron']){let n=Math.floor(run[k]/2);run[k]-=n;save[k]+=n;if(n)lines.push(n+' '+k);}notify('Courier banked half your haul: '+(lines.join(', ')||'nothing to send'));persist();}
 if(o.type==='shrine'){if(o.used)return;o.used=true;p.hp=stats().hp;p.mana=stats().mana;circle(p.x,p.y,90,'#9fd1c0',.8);notify('The shrine restores your health and mana');}
 if(o.type==='relic'){if(o.used)return;o.used=true;relicPanel();}
 if(o.type==='return'){showPanel(`<h2>Return to the refuge?</h2><p>Your equipment and experience stay with you. Returning early has the same carried-resource penalty as falling. Use the courier to bank half your resources first.</p><div class="row"><button id="stay">Keep exploring</button><button id="leave">Return to town</button></div>`,true);bind('stay',closePanel);bind('leave',()=>finishRun(false,true));}
 if(o.type==='exit'){if(o.locked){notify('Defeat the guardian to break the seal');return;}if(entities.some(e=>e.hp>0&&dist(e,o)<200)){notify('Clear nearby enemies before descending');return;}if(run.floor>=5){finishRun(true);return;}run.floor++;p.hp=Math.min(stats().hp,p.hp+stats().hp*.15);p.mana=stats().mana;loadFloor();persist();notify(`${bio().name} · Depth ${run.floor+1}`);}}
let field=null,navTick=0;
function navigation(){field=Array.from({length:map.h},()=>Array(map.w).fill(9999));let sx=Math.floor(p.x/T),sy=Math.floor(p.y/T);if(!map.tiles[sy]?.[sx])return;let q=[[sx,sy]],i=0;field[sy][sx]=0;while(i<q.length){let [x,y]=q[i++];for(let [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let nx=x+dx,ny=y+dy;if(map.tiles[ny]?.[nx]&&field[ny][nx]>field[y][x]+1){field[ny][nx]=field[y][x]+1;q.push([nx,ny]);}}}}
function chase(e,dt,mult=1){let dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy);if(!lineClear(e,p)&&field){let x=Math.floor(e.x/T),y=Math.floor(e.y/T),best=field[y]?.[x]??9999,bx=x,by=y;for(let [ox,oy] of [[1,0],[-1,0],[0,1],[0,-1]]){if(field[y+oy]?.[x+ox]<best){best=field[y+oy][x+ox];bx=x+ox;by=y+oy;}}dx=(bx+.5)*T-e.x;dy=(by+.5)*T-e.y;d=Math.hypot(dx,dy);}if(d>3){let speed=e.speed*mult*(e.slow>0?.45:1);move(e,dx/d*speed*dt,dy/d*speed*dt,Math.min(11,e.r*.6));e.angle=Math.atan2(dy,dx);e.walk+=dt*speed/20;}}
function enemyUpdate(e,dt){if(e.hp<=0)return;let d=dist(e,p);if(d<340)e.active=true;if(!e.active||d>700)return;e.flash=Math.max(0,e.flash-dt);e.slow=Math.max(0,e.slow-dt);e.burn=Math.max(0,e.burn-dt);if(e.burn>0){e.burnTick-=dt;if(e.burnTick<=0){e.burnTick=.65;hit(e,stats().burn,0,true);}}e.timer-=dt;
 if(e.type==='boss'){bossUpdate(e,dt,d);return;}
 if(e.state==='windup'){if(e.timer<=0){if(['archer','mage'].includes(e.type)){let a=e.aim;if(e.type==='mage')for(let k=-1;k<=1;k++)projectile(e.x,e.y,a+k*.22,160,e.damage,'orb',true,{life:3});else projectile(e.x,e.y,a,230,e.damage,'arrow',true,{life:2.5});}else if(e.type==='imp'){e.state='charge';e.timer=.35;return;}else if(dist(e,p)<e.r+43)damagePlayer(e.damage,e);e.state='recover';e.timer=e.type==='rat'?.55:.8;}return;}
 if(e.state==='charge'){move(e,Math.cos(e.aim)*310*dt,Math.sin(e.aim)*310*dt,8);if(dist(e,p)<25)damagePlayer(e.damage,e);if(e.timer<=0){e.state='recover';e.timer=1;}return;}
 if(e.state==='recover'){if(e.timer<=0)e.state='idle';return;}
 let ranged=['archer','mage'].includes(e.type),range=ranged?250:e.type==='imp'?180:e.r+30;if(d<range&&lineClear(e,p)&&e.timer<=0){e.state='windup';e.timer=ranged?.75:e.type==='imp'?.6:.42;e.aim=Math.atan2(p.y-e.y,p.x-e.x);e.angle=e.aim;}else if(ranged&&d<100){let a=Math.atan2(e.y-p.y,e.x-p.x);move(e,Math.cos(a)*40*dt,Math.sin(a)*40*dt);}else chase(e,dt);
 // Small separation prevents unreadable enemy stacks.
 for(let other of entities){if(other===e||other.hp<=0)continue;let dd=dist(e,other),min=e.r+other.r-5;if(dd<min&&dd>0){let push=(min-dd)*dt*2;move(e,(e.x-other.x)/dd*push,(e.y-other.y)/dd*push,8);}}
}
function bossUpdate(e,dt,d){let index=Math.floor(run.floor/2);if(e.hp<e.max*.5&&e.phase===1){e.phase=2;circle(e.x,e.y,140,'#ef7762',.8);notify(bio().boss+' awakens!');for(let k=0;k<3;k++)spawnEnemy(bio().enemy[0],e.x+Math.cos(k*TAU/3)*65,e.y+Math.sin(k*TAU/3)*65);}
 if(e.state==='windup'){if(e.timer<=0){let attack=e.attackCount%3;if(index===0){if(attack===0){circle(e.x,e.y,120,'#dbc477',.5);if(d<125)damagePlayer(e.damage,e);}else if(attack===1){let n=e.phase===2?16:10;for(let i=0;i<n;i++)projectile(e.x,e.y,i*TAU/n+e.angle,135,e.damage*.7,'thorn',true,{life:3});}else{for(let k=0;k<4;k++){let a=k*TAU/4;spawnEnemy('rat',e.x+Math.cos(a)*50,e.y+Math.sin(a)*50);}}}
 else if(index===1){if(attack===0){for(let i=0;i<3;i++)effects.push({type:'hostileZone',x:p.x+rnd(-70,70),y:p.y+rnd(-70,70),r:55,color:'#ab91d0',life:1.8,max:1.8,delay:.7,damage:e.damage});}else if(attack===1){for(let k=-2;k<=2;k++)projectile(e.x,e.y,e.aim+k*.24,190,e.damage*.8,'orb',true,{life:3});}else{circle(e.x,e.y,160,'#9babd7',.5);for(let k=0;k<8;k++)projectile(e.x,e.y,k*TAU/8+time,110,e.damage*.6,'orb',true,{life:4});}}
 else{if(attack===0){e.state='charge';e.timer=.6;return;}else if(attack===1){for(let k=0;k<12;k++)projectile(e.x,e.y,k*TAU/12,160,e.damage*.8,'fire',true,{life:3});effects.push({type:'hostileZone',x:e.x,y:e.y,r:95,color:'#d97852',life:4,max:4,delay:0,damage:e.damage*.6});}else{for(let i=0;i<5;i++)effects.push({type:'hostileZone',x:p.x+rnd(-140,140),y:p.y+rnd(-140,140),r:50,color:'#d98c5c',life:2,max:2,delay:.9,damage:e.damage});}}
 e.attackCount++;e.state='recover';e.timer=e.phase===2?.9:1.3;}return;}
 if(e.state==='charge'){move(e,Math.cos(e.aim)*310*dt,Math.sin(e.aim)*310*dt,15);if(dist(e,p)<55)damagePlayer(e.damage*1.3,e);burst(e.x,e.y,'#ae5747',1,20);if(e.timer<=0){e.state='recover';e.timer=1;}return;}
 if(e.state==='recover'){if(e.timer<=0)e.state='idle';return;}
 let range=index===0&&e.attackCount%3===0?110:290;if(d<range&&e.timer<=0){e.state='windup';e.timer=e.phase===2?.85:1.15;e.aim=Math.atan2(p.y-e.y,p.x-e.x);e.angle=e.aim;}else chase(e,dt,e.phase===2?1.3:1);
}
function update(dt){time+=dt;townTime+=dt;if(noticeTimer>0){noticeTimer-=dt;if(noticeTimer<=0)$('#notice').classList.remove('show');}if(mode!=='run'||panel||paused||!run)return;if(document.hidden)return;
 run.seconds+=dt;let s=stats();p.hp=Math.min(p.hp,s.hp);p.mana=Math.min(s.mana,p.mana+dt*(4+(run.relics.includes('crystal')?2:0)));for(let k of ['attack','q','e','dash','dashTime','invuln'])p[k]=Math.max(0,p[k]-dt);shake=Math.max(0,shake-dt*24);
 let dx=(keys.d||keys.ArrowRight?1:0)-(keys.a||keys.ArrowLeft?1:0),dy=(keys.s||keys.ArrowDown?1:0)-(keys.w||keys.ArrowUp?1:0),len=Math.hypot(dx,dy);if(p.dashTime>0)move(p,p.vx*dt,p.vy*dt);else if(len){move(p,dx/len*s.speed*dt,dy/len*s.speed*dt);p.walk+=dt*10;if(!mouse.active)p.angle=Math.atan2(dy,dx);}if(mouse.down||keys.attack||keys.j)attack();if(keys[' '])dodge();if(keys.q)skill('q');if(keys.e)skill('e');
 navTick-=dt;if(navTick<=0){navTick=.45;navigation();}for(let e of entities){enemyUpdate(e,dt);if(!run)return;}entities=entities.filter(e=>!e.dead);
 for(let b of shots){b.life-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(solid(b.x,b.y,2)){b.life=0;burst(b.x,b.y,b.enemy?'#b16e62':'#cbb284',3,25);}if(b.enemy){if(dist(b,p)<b.r+10){damagePlayer(b.damage,b);b.life=0;if(!run)return;}}else{for(let e of entities){if(e.hp<=0||b.hit.includes(e)||dist(b,e)>e.r+b.r)continue;hit(e,b.damage,3);b.hit.push(e);if(b.kind==='fire'){circle(b.x,b.y,40,'#f3a15d',.25);for(let o of entities)if(o!==e&&o.hp>0&&dist(o,b)<45)hit(o,b.damage*.45,4,true);}if(b.pierce--<=0){b.life=0;break;}}for(let o of objects)if(o.type==='barrel'&&!o.broken&&dist(b,o)<18){o.broken=true;b.life=0;loot.push({x:o.x,y:o.y,type:'gold',amount:5,bob:0});burst(o.x,o.y,'#aa8658',8);}}
 }shots=shots.filter(b=>b.life>0);
 for(let f of effects){f.life-=dt;if(f.type==='particle'){f.x+=f.vx*dt;f.y+=f.vy*dt;f.vx*=.95;f.vy*=.95;}if(f.type==='zone'){f.tick-=dt;if(f.tick<=0){f.tick=.6;for(let e of entities)if(e.hp>0&&dist(e,f)<f.r){hit(e,f.damage,0,true);if(f.slow)e.slow=1.5;if(f.storm)effects.push({type:'bolt',x:e.x-20,y:e.y-120,x2:e.x,y2:e.y,color:'#d2f4ff',life:.2,max:.2});}if(f.heal&&dist(p,f)<f.r)p.hp=Math.min(stats().hp,p.hp+3);}}if(f.type==='meteor'&&f.life<=0){for(let e of entities)if(e.hp>0&&dist(e,f)<f.r)hit(e,f.damage,20,true);effects.push({type:'blast',x:f.x,y:f.y,r:f.r,color:f.color,life:.5,max:.5});burst(f.x,f.y,f.color,30,140);shake=8;}if(f.type==='hostileZone'&&f.max-f.life>f.delay&&dist(p,f)<f.r){damagePlayer(f.damage,f);if(!run)return;}}
 effects=effects.filter(f=>f.life>0);for(let f of floaters){f.life-=dt;f.y-=dt*35;}floaters=floaters.filter(f=>f.life>0);
 for(let l of loot){let d=dist(l,p);if(d<65+s.magnet){l.x+=(p.x-l.x)*dt*9;l.y+=(p.y-l.y)*dt*9;}if(d<20){if(l.type==='health')p.hp=Math.min(s.hp,p.hp+l.amount);else{let n=l.type==='gold'?Math.round(l.amount*(1+s.gold)):l.amount;run[l.type]+=n;}l.picked=true;sound('coin');}}loot=loot.filter(l=>!l.picked);
 for(let o of objects){if(o.type==='trap'&&dist(o,p)<25&&Math.sin(time*2+o.phase)>.65){damagePlayer(12+run.floor*3,o);if(!run)return;}}
 let tx=Math.floor(p.x/T),ty=Math.floor(p.y/T);for(let y=ty-9;y<=ty+9;y++)for(let x=tx-12;x<=tx+12;x++)if(seen[y]?.[x]!==undefined&&Math.hypot(x-tx,y-ty)<12)seen[y][x]=true;
 map.rooms.forEach((r,i)=>{if(!discovered[i]&&p.x>r.x*T&&p.x<(r.x+r.w)*T&&p.y>r.y*T&&p.y<(r.y+r.h)*T){discovered[i]=true;if(i===11&&map.boss)notify(bio().boss+' guards the passage');}});
 cam.x+=(clamp(p.x-W/2,0,map.w*T-W)-cam.x)*Math.min(1,dt*8);cam.y+=(clamp(p.y-H/2,0,map.h*T-H)-cam.y)*Math.min(1,dt*8);
 saveTick+=dt;if(saveTick>8){saveTick=0;persist();}uiTick+=dt;if(uiTick>.12){uiTick=0;updateHud();}
}
function updateHud(){if(!p||!run)return;let s=stats(),h=hero(),c=cls();$('#hud').innerHTML=`<div><strong>${c.name} · LV ${h.level}</strong><div class="bar"><i style="width:${100*p.hp/s.hp}%"></i></div><div>${Math.ceil(p.hp)} / ${Math.round(s.hp)} health</div><div class="bar mana"><i style="width:${100*p.mana/s.mana}%"></i></div><div class="bar xp"><i style="width:${100*h.xp/levelXp(h.level)}%"></i></div><div class="skills"><div class="skill ${p.q<=0?'ready':''}"><b>${p.q>0?p.q.toFixed(1):'Q'}</b>${c.q.split(' ')[0]}</div><div class="skill ${p.e<=0?'ready':''}"><b>${p.e>0?p.e.toFixed(1):'E'}</b>${c.e.split(' ')[0]}</div><div class="skill ${p.dash<=0?'ready':''}"><b>${p.dash>0?p.dash.toFixed(1):'SPC'}</b>Dodge</div><div class="skill"><b>R ×${p.potions}</b>Potion</div></div></div><div class="status-right"><strong>${bio().name.toUpperCase()}</strong><p style="margin:6px 0;color:#d4c0a0;font-size:12px">Depth ${run.floor+1} / 6 · ${run.kills} defeated</p>◈ ${run.gold}<br><small>${run.wood} wood · ${run.stone} stone · ${run.iron} iron</small><p class="muted" style="margin-top:8px">${run.relics.length} trinkets · ${Math.floor(run.seconds/60)}:${String(Math.floor(run.seconds%60)).padStart(2,'0')}</p></div>`;}
const tileNoise=(x,y)=>{let n=(x*374761393+y*668265263)^12345;n=(n^(n>>>13))*1274126177;return (n^(n>>>16))>>>0;};
function rect(x,y,w,h,c){ctx.fillStyle=c;ctx.fillRect(Math.round(x),Math.round(y),w,h);}function ellipse(x,y,rx,ry,c){ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill();}
function text(s,x,y,size=14,color='#e0d3b8',align='center'){ctx.font=`${size}px Inter, sans-serif`;ctx.textAlign=align;ctx.fillStyle='#060a0d';ctx.fillText(s,x+1,y+2);ctx.fillStyle=color;ctx.fillText(s,x,y);}
function tree(x,y,seed=0,autumn=false){let sway=Math.sin(time*1.3+seed)*1.5;ellipse(x,y+10,25,11,'#0005');rect(x-4,y-17,8,31,'#322b29');rect(x-2,y-17,3,26,'#65513a');if(autumn){for(let j=0;j<5;j++){let xx=x+Math.sin(seed+j*5)*14,yy=y-28-j*6;ellipse(xx,yy,19,14,['#784a32','#91623b','#aa7340','#bb8846','#8c653b'][j]);rect(xx-9,yy-5,8,3,'#d09b54');}}else{for(let k=0;k<3;k++){let yy=y-15-k*15,rr=26-k*4;ctx.fillStyle=['#1c352f','#294436','#36523d'][k];ctx.beginPath();ctx.moveTo(x+sway,yy-29);ctx.lineTo(x-rr,yy+12);ctx.lineTo(x+rr,yy+12);ctx.closePath();ctx.fill();ctx.fillStyle='#52704a';ctx.beginPath();ctx.moveTo(x+sway,yy-26);ctx.lineTo(x-rr+6,yy+7);ctx.lineTo(x-5,yy+2);ctx.closePath();ctx.fill();}}}
function ground(){let b=bio(),startX=Math.max(0,Math.floor(cam.x/T)-1),endX=Math.min(map.w,Math.ceil((cam.x+W)/T)+1),startY=Math.max(0,Math.floor(cam.y/T)-2),endY=Math.min(map.h,Math.ceil((cam.y+H)/T)+3);for(let y=startY;y<endY;y++)for(let x=startX;x<endX;x++){let px=x*T,py=y*T,n=tileNoise(x,y),floor=map.tiles[y][x],known=seen[y]?.[x];if(!known){rect(px,py,T,T,'#0b1218');continue;}if(floor){rect(px,py,T,T,n%3?b.floor:b.alt);if(run.floor<2){rect(px+(n%21),py+((n>>4)%24),3,2,'#596246');rect(px+((n>>6)%25),py+((n>>8)%25),2,5,'#4a583e');if(n%7===0){rect(px+8,py+18,11,4,'#504a39');rect(px+11,py+16,7,2,'#6a5a40');}if(n%11===0)rect(px+13,py+8,3,3,'#b69b51');}else{rect(px,py,T,1,'#171c2460');rect(px,py,1,T,'#151b2260');if(n%4===0)rect(px+5,py+8,10,1,'#80859122');if(n%9===0){rect(px+12,py+18,8,2,'#1b2228');rect(px+18,py+20,2,5,'#1b2228');}}}else{rect(px,py,T,T,b.wall);let below=map.tiles[y+1]?.[x];if(below){rect(px,py-6,T,T+7,'#151c23');rect(px,py-10,T,10,b.top);rect(px+1,py-9,T-2,2,'#a0a58b33');rect(px+1,py+2,14,12,b.wall);rect(px+17,py+2,14,12,b.wall);rect(px+5,py+17,22,9,b.wall);}else{rect(px,py,T,2,b.top);if(n%2===0)rect(px+4,py+9,20,2,'#ffffff06');}}}
 // Wall-side vegetation retains a legible central combat space.
 if(run.floor<2)for(let y=startY;y<endY;y++)for(let x=startX;x<endX;x++){let n=tileNoise(x,y);if(!map.tiles[y][x]&&seen[y]?.[x]&&n%7===0&&map.tiles[y+1]?.[x])tree(x*T+16,y*T+7,n,n%3===0);}}
function actor(o,player=false){let x=Math.round(o.x),y=Math.round(o.y),c=player?cls().color:o.type==='boss'?bio().bossColor:({rat:'#779751',bandit:'#a97b5b',archer:'#829367',skeleton:'#b5b6a2',mage:'#9383b5',knight:'#927f89',imp:'#bf6954'}[o.type]),sc=o.type==='boss'?2.2:1,walk=Math.sin(o.walk||0)*3,flash=o.flash>0||player&&o.invuln>0&&Math.sin(time*40)>0;ctx.save();ctx.translate(x,y);ctx.scale(sc,sc);ellipse(0,7,13,6,'#0006');if(player&&o.dashTime>0){ctx.globalAlpha=.6;rect(-12,-24,24,30,'#a6c4b05a');ctx.globalAlpha=1;}
 if(o.type==='rat'){ellipse(0,0,13,8,flash?'#f2ead6':c);rect(-8,-8,14,8,flash?'#f2ead6':'#91ab68');rect(o.angle>Math.PI/2||o.angle<-Math.PI/2?-11:7,-7,3,2,'#e8cd75');ctx.strokeStyle='#6e8454';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-10,3);ctx.lineTo(-18,8);ctx.lineTo(-21,5);ctx.stroke();rect(-7,7,3,3,'#384536');rect(6,7,3,3,'#384536');}
 else{rect(-7+walk*.4,1,5,10,'#2a292c');rect(3-walk*.4,1,5,10,'#2a292c');rect(-8+walk*.4,8,7,3,'#504339');rect(2-walk*.4,8,7,3,'#504339');rect(-10,-15,20,20,flash?'#fff2d6':c);rect(-10,-15,5,18,flash?'#fff2d6':'#00000030');rect(-6,-13,13,2,'#ffffff33');rect(-11,-1,22,4,'#3e3534');rect(-2,0,4,3,'#bc9b5b');rect(-6,-28,13,13,flash?'#fff2d6':o.type==='skeleton'?'#d0cbb4':'#c5a387');rect(-7,-29,15,5,flash?'#fff2d6':player?c:'#4c4343');rect(-7,-25,3,8,flash?'#fff2d6':c);rect(5,-25,3,8,flash?'#fff2d6':c);rect(-4,-22,3,2,'#25292b');rect(2,-22,3,2,'#25292b');rect(-3,-17,6,2,'#8d695c');rect(-14,-13,4,13,flash?'#fff2d6':c);rect(10,-13,4,13,flash?'#fff2d6':c);rect(-14,-2,4,4,'#c0a085');rect(10,-2,4,4,'#c0a085');
 let a=o.angle||0;ctx.save();ctx.translate(11,-7);ctx.rotate(a+Math.PI/2);if(player&&cls().kind==='arrow'||o.type==='archer'){ctx.strokeStyle='#be9d62';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-7,13,Math.PI*.2,Math.PI*.8);ctx.stroke();ctx.strokeStyle='#cabbaa';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(-10,1);ctx.lineTo(10,1);ctx.stroke();}else if(player&&['fire','soul','spark'].includes(cls().kind)||o.type==='mage'){rect(-2,-24,4,32,'#8f7256');ellipse(0,-25,5,5,player?cls().color:'#c084cd');rect(-1,-28,2,5,'#e2e6ce');}else{rect(-2,-23,4,24,'#bdc7bc');rect(-1,-24,2,22,'#eef0d2');rect(-6,-1,12,3,'#b29957');rect(-2,2,4,7,'#66513d');}ctx.restore();
 if(o.type==='boss'){rect(-10,-33,20,5,'#d0ab65');rect(-11,-39,4,10,'#d0ab65');rect(-2,-41,4,12,'#e4c276');rect(7,-39,4,10,'#d0ab65');ellipse(0,-35,2,3,'#cd5e4a');}}
 ctx.restore();if(!player&&o.hp<o.max&&o.hp>0){rect(x-17*sc,y-37*sc,34*sc,4,'#10171c');rect(x-16*sc,y-37*sc,32*sc*o.hp/o.max,3,o.type==='boss'?'#d59b63':'#b85050');}if(player){let s=stats();rect(x-13,y-38,26,3,'#121c23');rect(x-13,y-38,26*p.hp/s.hp,3,'#bd5551');rect(x-13,y-34,26*p.mana/s.mana,2,'#64a5bf');}}
function object(o){let x=o.x,y=o.y;if(o.type==='torch'){rect(x-3,y-12,6,21,'#64533a');rect(x-5,y-19,10,8,'#d5a35d');ellipse(x,y-22,4+Math.sin(time*12+x)*1.5,8,'#efc47a');ellipse(x,y-23,2,4,'#fff2b4');}
 if(o.type==='barrel'){if(o.broken){rect(x-12,y+3,9,3,'#806344');rect(x+5,y+5,8,3,'#70573d');return;}ellipse(x,y+7,14,6,'#0005');rect(x-11,y-16,22,23,'#76583b');rect(x-9,y-18,18,4,'#ad8552');rect(x-11,y-12,22,3,'#494b45');rect(x-11,y+1,22,3,'#494b45');rect(x-4,y-13,2,14,'#c193573f');}
 if(o.type==='chest'){ellipse(x,y+9,18,7,'#0006');rect(x-15,y-8,30,18,o.open?'#413b32':'#93663c');rect(x-15,y-16,30,o.open?4:10,'#be9050');rect(x-15,y-8,30,3,'#423a30');rect(x-11,y-14,3,22,'#cba756');rect(x+8,y-14,3,22,'#cba756');rect(x-3,y-6,6,7,'#e8c777');if(o.open)rect(x-11,y-9,22,5,'#131b1d');}
 if(o.type==='bird'){rect(x-3,y-5,6,18,'#686353');rect(x-18,y-10,36,5,'#77725b');if(!o.used){ellipse(x,y-20,10,9,'#17242e');rect(x+6,y-29,7,12,'#1f303b');rect(x+12,y-26,7,3,'#ad9b65');rect(x+9,y-27,2,2,'#ffd785');ctx.fillStyle='#354d5b';ctx.beginPath();ctx.moveTo(x-7,y-21);ctx.lineTo(x-27,y-26+Math.sin(time*3)*5);ctx.lineTo(x-8,y-9);ctx.fill();}text(o.used?'Banked':'Courier',x,y+34,11,'#c4c8aa');}
 if(o.type==='shrine'){ellipse(x,y+9,20,8,'#0005');rect(x-17,y+1,34,10,'#6e7973');rect(x-10,y-19,20,23,'#919d8b');rect(x-6,y-28,12,15,o.used?'#555f5d':'#9ed8cb');if(!o.used){circleGlow(x,y-20,25,'#a3e1ca',.16);ellipse(x,y-21,3,6,'#e8ffda');}}
 if(o.type==='relic'){if(o.used)return;ellipse(x,y+7,17,7,'#0005');rect(x-11,y,22,8,'#626477');rect(x-5,y-13,10,15,'#9792a0');ctx.save();ctx.translate(x,y-25+Math.sin(time*2)*4);ctx.rotate(time*.6);rect(-6,-6,12,12,'#cbb77d');rect(-3,-3,6,6,'#ffe9ab');ctx.restore();circleGlow(x,y-24,32,'#eed39c',.12);}
 if(o.type==='exit'||o.type==='return'){let locked=o.locked,color=o.type==='return'?'#8ba8ae':locked?'#b56369':'#8cbcb1';ellipse(x,y+3,26,13,'#060d15');ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(x,y-4,23,32,0,0,TAU);ctx.stroke();for(let i=0;i<8;i++){let a=time+i*TAU/8;ellipse(x+Math.cos(a)*18,y-5+Math.sin(a)*25,2,3,color);}text(o.type==='return'?'Refuge':locked?'Sealed':'Descend',x,y+44,11,color);}
 if(o.type==='trap'){let active=Math.sin(time*2+o.phase)>.65;rect(x-18,y-13,36,28,'#1a2428');for(let i=0;i<3;i++)for(let j=0;j<2;j++){let xx=x-12+i*12,yy=y-7+j*12;ctx.fillStyle=active?'#d1c4b1':'#726a60';ctx.beginPath();ctx.moveTo(xx-3,yy+3);ctx.lineTo(xx,yy-(active?13:2));ctx.lineTo(xx+3,yy+3);ctx.fill();}if(!active&&Math.sin(time*2+o.phase)>.3)rect(x-18,y+12,36,2,'#d48463');}}
function circleGlow(x,y,r,color,alpha){ctx.save();ctx.globalAlpha=alpha;let g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.fillRect(x-r,y-r,r*2,r*2);ctx.restore();}
function drawEffects(){for(let f of effects){let a=clamp(f.life/f.max,0,1);ctx.save();ctx.globalAlpha=a;if(f.type==='particle')rect(f.x,f.y,f.size,f.size,f.color);if(f.type==='ring'||f.type==='blast'){ctx.strokeStyle=f.color;ctx.lineWidth=f.type==='blast'?8:3;ctx.beginPath();ctx.arc(f.x,f.y,f.r*(1-a*.45),0,TAU);ctx.stroke();if(f.type==='blast'){ctx.globalAlpha=a*.3;ctx.fillStyle=f.color;ctx.fill();}}if(f.type==='slash'){ctx.strokeStyle=f.color;ctx.lineWidth=10*a;ctx.beginPath();ctx.arc(f.x,f.y,f.r*.8,f.angle-1.1+(1-a),f.angle+.7+(1-a));ctx.stroke();ctx.strokeStyle='#fff0ce';ctx.lineWidth=2;ctx.stroke();}if(['zone','hostileZone','meteor'].includes(f.type)){ctx.globalAlpha=.12;ctx.fillStyle=f.color;ctx.beginPath();ctx.arc(f.x,f.y,f.r,0,TAU);ctx.fill();ctx.globalAlpha=f.type==='hostileZone'&&f.max-f.life<f.delay?.8:.4;ctx.strokeStyle=f.color;ctx.lineWidth=2;ctx.setLineDash([7,7]);ctx.stroke();ctx.setLineDash([]);if(f.type==='meteor'){ctx.globalAlpha=.8;ctx.beginPath();ctx.moveTo(f.x-45*a,f.y-220*a);ctx.lineTo(f.x,f.y);ctx.lineWidth=12*(1-a);ctx.stroke();}else for(let i=0;i<5;i++){let an=time+i*TAU/5;rect(f.x+Math.cos(an)*f.r*.7,f.y+Math.sin(an)*f.r*.7,3,3,f.color);}}if(f.type==='bolt'){ctx.strokeStyle=f.color;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(f.x,f.y);for(let i=1;i<6;i++){let a=i/6;ctx.lineTo(f.x+(f.x2-f.x)*a+Math.sin(i*5+time*50)*9,f.y+(f.y2-f.y)*a);}ctx.lineTo(f.x2,f.y2);ctx.stroke();}ctx.restore();}}
function drawMini(){const scale=2.4,mw=map.w*scale,mh=map.h*scale,x=W-mw-24,y=H-mh-30;rect(x-8,y-8,mw+16,mh+16,'#090f17c9');ctx.strokeStyle='#73786577';ctx.strokeRect(x-8,y-8,mw+16,mh+16);for(let yy=0;yy<map.h;yy++)for(let xx=0;xx<map.w;xx++)if(seen[yy][xx]&&map.tiles[yy][xx])rect(x+xx*scale,y+yy*scale,scale,scale,'#72827180');for(let o of objects)if(seen[Math.floor(o.y/T)]?.[Math.floor(o.x/T)]&&['exit','bird','relic','shrine'].includes(o.type))rect(x+o.x/T*scale-2,y+o.y/T*scale-2,4,4,{exit:'#e5c080',bird:'#73cbd1',relic:'#bd96e5',shrine:'#a7c894'}[o.type]);ellipse(x+p.x/T*scale,y+p.y/T*scale,3,3,'#fff1c0');text('MAP · EXPLORED '+Math.round(discovered.filter(Boolean).length/12*100)+'%',x+mw/2,y+mh+26,10,'#a5ac99');}
function drawTown(){ctx.fillStyle='#182329';ctx.fillRect(0,0,W,H);for(let y=0;y<26;y++)for(let x=0;x<41;x++){let n=tileNoise(x,y);rect(x*T,y*T,T,T,n%3?'#303d35':'#344238');if(n%3===0)rect(x*T+8,y*T+16,3,5,'#566348');}for(let y=0;y<H;y+=32)rect(W/2-60,y,120,32,y%64?'#5b5140':'#554c3c');for(let x=0;x<W;x+=32)rect(x,H/2-35,32,90,x%64?'#5b5140':'#554c3c');for(let [x,y,col] of [[220,230,'#8a5d43'],[960,270,'#665c77'],[220,620,'#6e7661'],[950,630,'#70614e']]){ellipse(x,y+40,120,35,'#0004');rect(x-95,y-80,190,130,'#5c5547');rect(x-91,y-78,182,125,'#86775c');rect(x-100,y-88,200,22,col);for(let j=0;j<4;j++)rect(x-110+j*8,y-120-j*15,220-j*16,18,col);rect(x-25,y-30,50,77,'#282c2a');rect(x-70,y-35,28,28,'#e2b365');rect(x+44,y-35,28,28,'#e2b365');}for(let i=0;i<20;i++)tree((i*137)%W,(i*239)%H,i,i%4===0);circleGlow(W/2,H/2,250,'#e8b960',.17);for(let i=0;i<12;i++){let x=W/2+Math.sin(time*.2+i)*100,y=H/2+Math.cos(time*.25+i*3)*80;rect(x,y,2,2,'#e4bd6588');}}
function render(){ctx.clearRect(0,0,W,H);ctx.imageSmoothingEnabled=false;if(mode!=='run'||!p||!map){drawTown();return;}ctx.save();ctx.translate(-Math.floor(cam.x)+(Math.random()-.5)*shake,-Math.floor(cam.y)+(Math.random()-.5)*shake);ground();for(let o of objects)if(seen[Math.floor(o.y/T)]?.[Math.floor(o.x/T)]&&['trap','exit','return'].includes(o.type))object(o);
 for(let e of entities){if(!e.active||e.state!=='windup')continue;let a=e.aim||0;ctx.save();ctx.globalAlpha=.2+Math.sin(time*13)*.08;ctx.fillStyle='#f08065';ctx.strokeStyle='#ffc58d';ctx.lineWidth=2;if(e.type==='boss'){ctx.beginPath();ctx.arc(e.x,e.y,e.attackCount%3===0?120:70,0,TAU);ctx.fill();ctx.stroke();}else{ctx.beginPath();ctx.moveTo(e.x,e.y);ctx.arc(e.x,e.y,['archer','mage','imp'].includes(e.type)?200:48,a-.32,a+.32);ctx.closePath();ctx.fill();ctx.stroke();}ctx.restore();}
 for(let l of loot)if(seen[Math.floor(l.y/T)]?.[Math.floor(l.x/T)]){let yy=l.y+Math.sin(time*3+l.bob)*2;ellipse(l.x,l.y+5,5,2,'#0005');if(l.type==='gold'){rect(l.x-3,yy-4,6,7,'#e3bc63');rect(l.x-2,yy-4,3,2,'#fff1a2');}else if(l.type==='health'){rect(l.x-4,yy-5,8,10,'#c56c5d');rect(l.x-2,yy-8,4,4,'#a79573');}else{rect(l.x-5,yy-4,10,8,{wood:'#ae8554',stone:'#9a9e98',iron:'#b8abc0'}[l.type]);rect(l.x-3,yy-6,6,3,'#d4c59a');}}
 let drawables=[...objects.filter(o=>!['trap','exit','return'].includes(o.type)&&seen[Math.floor(o.y/T)]?.[Math.floor(o.x/T)]),...entities.filter(e=>e.hp>0&&seen[Math.floor(e.y/T)]?.[Math.floor(e.x/T)]),{...p,player:true}].sort((a,b)=>a.y-b.y);for(let o of drawables){if(o.player)actor(o,true);else if(o.max)actor(o);else object(o);}
 for(let b of shots){ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.atan2(b.vy,b.vx));if(['arrow','knife','thorn'].includes(b.kind)){rect(-10,-1,18,2,b.enemy?'#e79d72':'#dec798');rect(7,-3,4,6,'#d8dbbc');}else{let color=b.enemy?'#e97a69':({fire:'#efb369',soul:'#89d0a7',spark:'#a2dfef',hammer:'#eee0a4'}[b.kind]||'#b8a9df');ellipse(0,0,b.r+2,b.r,color);ellipse(0,0,b.r*.4,b.r*.4,'#ffefd5');}ctx.restore();}
 drawEffects();for(let f of floaters){ctx.save();ctx.globalAlpha=f.life;text(f.text,f.x,f.y,14,f.color);ctx.restore();}
 // Soft torch pools and edge vignette leave telegraphs visible.
 ctx.globalCompositeOperation='screen';for(let o of objects)if(o.type==='torch'&&Math.abs(o.x-p.x)<700&&Math.abs(o.y-p.y)<500)circleGlow(o.x,o.y-20,100,bio().light,.1);circleGlow(p.x,p.y,150,'#b7c8a8',.045);ctx.globalCompositeOperation='source-over';
 let near=objects.filter(o=>!['torch','trap','barrel'].includes(o.type)&&!o.open&&!o.used&&dist(o,p)<64).sort((a,b)=>dist(a,p)-dist(b,p))[0];if(near){let labels={chest:'Open chest',bird:'Bank half your haul',shrine:'Restore health & mana',relic:'Choose a trinket',exit:near.locked?'Defeat the guardian':'Descend',return:'Return to town'};text('[F] '+labels[near.type],near.x,near.y-48,13,'#ffe2a3');}
 ctx.restore();let g=ctx.createRadialGradient(W/2,H/2,180,W/2,H/2,750);g.addColorStop(0,'transparent');g.addColorStop(1,'#030811aa');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);drawMini();let boss=entities.find(e=>e.type==='boss'&&e.active&&e.hp>0);if(boss){let bw=420;rect(W/2-bw/2,H-59,bw,12,'#13191f');rect(W/2-bw/2+2,H-57,(bw-4)*boss.hp/boss.max,8,'#b66756');ctx.strokeStyle='#c7a772';ctx.strokeRect(W/2-bw/2,H-59,bw,12);text(bio().boss,W/2,H-69,16,'#ecd2aa');}if(paused){rect(0,0,W,H,'#0006');text('PAUSED',W/2,H/2,32,'#eace9b');}}
function guide(){const wasTown=mode==='town',wasPending=pendingResume;showPanel(`<div class="row"><div><div class="eyebrow">Field guide</div><h2>The road to the crown</h2></div><button id="guideBack">Close</button></div><div class="two"><div><h3>Explore, fight, return</h3><p>Six generated floors span Pinewild, Sunken Vaults and Ember Citadel. Guardians block floors 2, 4 and 6. Explore the branches for equipment, restoration shrines and three-choice trinkets. Defeat the Hollow King to begin New Game +.</p><h3>What survives?</h3><p>Character level, equipment, town construction and banked resources persist. Trinkets are temporary. A courier sends half your carried resources safely home. Death or retreat keeps 60% of what remains, increased by town upgrades. Victory keeps everything.</p><h3>Read the fight</h3><p>Orange cones and circles warn of enemy attacks. Dodge through danger; you are invulnerable during the dash. Mana regenerates. Potions restore both health and mana. Keyboard-only J attacks with nearby-target aim.</p></div><div><h3>Controls</h3><p>WASD / arrows: move<br>Mouse: aim · hold left click: attack<br>J: attack with nearby-target aim (when mouse inactive)<br>Space: dodge · Q / E: class skills<br>F: interact · R: potion<br>Tab: equipment · Escape: pause<br>Touch: movement pad and action buttons; automatic aim</p><h3>About this interpretation</h3><p>This is an original, solo browser game informed by the <a href="https://wiki.heroesofhammerwatch2.com/Main_Page" target="_blank" rel="noopener">Heroes of Hammerwatch II wiki</a> and <a href="https://store.steampowered.com/app/619820/Heroes_of_Hammerwatch_II/" target="_blank" rel="noopener">official Steam listing</a>. It does not contain the original game’s code, art, music or maps.</p><p class="muted">Compared with the commercial game: three original environments and guardians rather than eight environments/six acts; simplified class specializations and town; no co-op, quest NPC rescues, full skill trees, crafting/enchanting or DLC. It is a smaller interpretation, not a feature-identical port.</p></div></div>`);bind('guideBack',()=>wasPending?welcomePanel():wasTown?townPanel():closePanel());}
function pauseMenu(){if(mode!=='run')return;if(panel){closePanel();return;}showPanel(`<div class="eyebrow">Take a breath</div><h2>Expedition paused</h2><p>Your progress saves automatically on this device. You can close this tab and resume your expedition later.</p><div class="row wrap"><button class="primary" id="continue">Resume</button><button id="armory">Equipment</button><button id="controls">Controls</button><button id="abandon">Retreat to town</button></div>`,true);bind('continue',closePanel);bind('armory',()=>inventoryPanel());bind('controls',guide);bind('abandon',()=>{showPanel(`<h2>Retreat to town?</h2><p>Keep all equipment and experience, and ${Math.round(Math.min(.85,.6+.05*save.buildings.chapel+.025*save.buildings.treasury)*100)}% of carried resources.</p><div class="row"><button id="cancel">Stay</button><button id="confirmRetreat">Retreat</button></div>`,true);bind('cancel',pauseMenu);bind('confirmRetreat',()=>finishRun(false,true));});persist();}
window.addEventListener('keydown',e=>{let key=e.key.length===1?e.key.toLowerCase():e.key;if([' ','Tab','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(key))e.preventDefault();if(e.repeat&&['f','r','Escape','Tab'].includes(key))return;if(key==='Escape'){pauseMenu();return;}if(mode!=='run'||panel)return;keys[key]=true;if(key==='f')interact();if(key==='r')potion();if(key==='Tab')inventoryPanel();if(key==='j')mouse.active=false;});window.addEventListener('keyup',e=>{keys[e.key.length===1?e.key.toLowerCase():e.key]=false;});
canvas.addEventListener('pointermove',e=>{if(e.pointerType==='touch')return;let r=canvas.getBoundingClientRect(),scale=Math.min(r.width/W,r.height/H),ox=(r.width-W*scale)/2,oy=(r.height-H*scale)/2;mouse.x=(e.clientX-r.left-ox)/scale;mouse.y=(e.clientY-r.top-oy)/scale;mouse.active=true;});canvas.addEventListener('pointerdown',e=>{if(e.button!==0||panel)return;mouse.down=true;canvas.focus();if(e.pointerType==='touch')mouse.active=false;});window.addEventListener('pointerup',()=>mouse.down=false);window.addEventListener('blur',()=>{clearInput();if(mode==='run'&&!panel){paused=true;persist();}});window.addEventListener('focus',()=>{paused=false;last=performance.now();});document.addEventListener('visibilitychange',()=>{clearInput();if(document.hidden)persist();last=performance.now();});window.addEventListener('beforeunload',persist);canvas.addEventListener('contextmenu',e=>e.preventDefault());
document.querySelectorAll('[data-key]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();let k=b.dataset.key;if(mode!=='run'||panel)return;mouse.active=false;keys[k]=true;if(k==='f')interact();if(k==='r')potion();b.setPointerCapture(e.pointerId);});const up=e=>{e.preventDefault();keys[b.dataset.key]=false;};b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);});
bind('sound',()=>{save.settings.sound=!save.settings.sound;$('#sound').textContent=save.settings.sound?'Sound on':'Sound off';sound('coin');persist();});$('#sound').textContent=save.settings.sound?'Sound on':'Sound off';bind('help',guide);bind('journal',guide);bind('pause',pauseMenu);
function frame(now){let dt=Math.min(.035,(now-last)/1000||.016);last=now;try{update(dt);render();}catch(err){console.error(err);paused=true;notify('An unexpected error paused the game. Reload to restore the latest save.');}requestAnimationFrame(frame);}
function welcomePanel(){showPanel(`<div class="eyebrow">Welcome back</div><h1>YOUR EXPEDITION AWAITS</h1><p>${CLASSES.find(c=>c.id===save.classId)?.name||'Hero'} · Depth ${save.run.floor+1} · ${save.run.kills} defeated</p><div class="row"><button class="primary" id="resumeRun">Resume expedition</button><button id="retreatSaved">Retreat to town</button></div>`,true);bind('resumeRun',resumeRun);bind('retreatSaved',()=>{resumeRun();finishRun(false,true);});}
if(save.run)welcomePanel();else townPanel();requestAnimationFrame(frame);
// Optional, read-only WebMCP status. This never plays or changes game state.
if(document.modelContext?.registerTool){const life=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'read_emberwatch_progress',title:'Read Emberwatch progress',description:'Read the same hero, expedition and town progress shown in the game interface. No game actions are taken.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');return {hero:cls().name,level:hero().level,mode,depth:run?run.floor+1:null,health:p?Math.ceil(p.hp):null,carried:run?{gold:run.gold,wood:run.wood,stone:run.stone,iron:run.iron}:null,town:{gold:save.gold,wood:save.wood,stone:save.stone,iron:save.iron},victories:save.wins};}},{signal:life.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>life.abort(),{once:true});}
