// Permanent progression and migrations. No DOM dependencies.
export const ATTRIBUTE_DEFS=[{id:'strength',name:'힘',text:'공격력 +1, 방어력 +0.25'},{id:'dexterity',name:'민첩',text:'치명타 확률 +1%, 공격 속도 +0.5%'},{id:'intelligence',name:'지능',text:'기술 피해 +3%'},{id:'focus',name:'집중',text:'최대 마나 +5, 초당 마나 회복 +0.15'},{id:'vitality',name:'활력',text:'최대 체력 +7'}];
export const SKILL_COST=[3,3,5,5,7];
export const AFFIXES=[{id:'ember',name:'불붙은',color:'#efad64',text:'적중 시 적을 3초간 불태움',stat:'burn',value:4},{id:'frost',name:'서리 맺힌',color:'#91d7e4',text:'적중 시 적 이동 속도 35% 감소',stat:'slow',value:.35},{id:'storm',name:'폭풍으로 벼린',color:'#adbcf5',text:'세 번째 적중마다 다른 적에게 번개가 이어짐',stat:'chain',value:1},{id:'vampire',name:'선혈의',color:'#d98f9c',text:'적 처치 시 체력 2 회복',stat:'lifekill',value:2}];
export function newHero(){return {level:1,xp:0,spec:0,skillPoints:0,attributePoints:0,skills:{q:1,e:0,passive:1,ultimate:0},attributes:{strength:0,dexterity:0,intelligence:0,focus:0,vitality:0},growthVersion:2};}
export function migrateGrowth(save){save.buildings.training??=0;save.growthLog??=[];save.milestones??={};for(const h of Object.values(save.heroes)){if(!h.growthVersion){h.skillPoints=3*Math.max(0,h.level-1);h.attributePoints=3*Math.max(0,h.level-1);h.skills={q:1,e:1,passive:1,ultimate:h.level>=10?1:0};h.attributes={strength:0,dexterity:0,intelligence:0,focus:0,vitality:0};h.growthVersion=2;}h.skills={q:1,e:0,passive:1,ultimate:0,...h.skills};h.attributes={strength:0,dexterity:0,intelligence:0,focus:0,vitality:0,...h.attributes};}for(const g of save.gear){g.baseValue??=g.value;g.upgrade??=0;g.ilvl??=1;g.affix??=null;}save.growthVersion=2;return save;}
export function rankLimit(save){return Math.min(5,2+(save.buildings.training||0));}
export function skillPrice(hero,key){return SKILL_COST[hero.skills[key]||0]??Infinity;}
export function trainSkill(save,hero,key){if(!['q','e','passive','ultimate'].includes(key))return {ok:false,reason:'알 수 없는 기술입니다'};const rank=hero.skills[key]||0,cost=skillPrice(hero,key);if(key==='ultimate'&&hero.level<10)return {ok:false,reason:'영웅 10레벨이 필요합니다'};if(rank>=rankLimit(save))return {ok:false,reason:rank>=5?'최고 등급입니다':'훈련장을 강화하세요'};if(hero.skillPoints<cost)return {ok:false,reason:`기술 점수 ${cost}점이 필요합니다`};hero.skillPoints-=cost;hero.skills[key]=rank+1;return {ok:true,before:rank,after:rank+1,cost};}
export function allocateAttribute(hero,id){if(!ATTRIBUTE_DEFS.some(a=>a.id===id)||hero.attributePoints<1)return false;hero.attributePoints--;hero.attributes[id]++;return true;}
export function equipmentValue(g){const value=g.baseValue??g.value;return Math.round(value*(1+.22*(g.upgrade||0))*(g.stat==='crit'?1000:100))/(g.stat==='crit'?1000:100);}
export function forgeQuote(g){const n=g.upgrade||0;return {gold:30+25*n+5*(g.ilvl||1),stone:2+n,iron:n>=2?n-1:0,max:5};}
export function forgeGear(save,g){const q=forgeQuote(g),level=g.upgrade||0;if(level>=q.max)return {ok:false,reason:'최대 강화 단계입니다'};if(level>=1+(save.buildings.forge||0))return {ok:false,reason:'추가 강화에는 대장간 개선이 필요합니다'};if(save.gold<q.gold||save.stone<q.stone||save.iron<q.iron)return {ok:false,reason:'보관 중인 재료가 부족합니다'};const before=equipmentValue(g);save.gold-=q.gold;save.stone-=q.stone;save.iron-=q.iron;g.upgrade=level+1;return {ok:true,before,after:equipmentValue(g)};}
export function skillDescription(classId,key,rank){const r=Math.max(1,rank);if(key==='passive')return `공격력 +${(r-1)*6}% · 최대 체력 +${(r-1)*10}`;
 if(key==='ultimate')return `전문화 기술 · 위력 ${r*55+100}% · ${r>=3?'효과 범위 확대':'영웅 10레벨에 해금'}`;
 const power=Math.round((1+(r-1)*.3)*100);const detail={warrior:{q:r>=3?'돌아오는 도끼 + 도끼 하나 추가':'적을 관통하며 회전하는 도끼 두 개',e:`전장의 함성: 공격 속도 +${20+r*5}% · ${r>=3?'시전 시 충격파 발생':'이동 속도 증가 효과'}`},paladin:{q:`치유의 원 · ${r>=3?'범위 확대 및 빛의 파동':'지속적으로 체력 회복'}`,e:r>=3?'적을 관통하는 빛의 망치 세 개':'적을 관통하는 빛의 망치 하나'},ranger:{q:`화살 ${3+2*r}발 · ${r>=3?'튕기는 불꽃':'관통 사격'}`,e:r>=3?'적을 둔화시키는 덫 세 곳':'적을 둔화시키는 덫 지대 하나'},wizard:{q:r>=3?'서리 폭발 + 얼음 파편 여덟 개':'서리 폭발로 주변 적 둔화',e:r>=3?'유성 세 개':'조준한 곳에 유성 하나'},rogue:{q:`관통 칼날 ${8+4*r}개`,e:r>=3?'그림자 걸음 + 칼날 폭발':'그림자 걸음과 기습'},warlock:{q:r>=3?'생명력 흡수 + 망령의 화살':'주변 적의 생명력 흡수',e:r>=3?'부패 지대 세 곳':'부패 지대 한 곳'},sorcerer:{q:`연쇄 번개로 적 ${3+2*r}명 타격`,e:r>=3?'범위가 넓어진 폭풍과 회전하는 전광':'지속되는 번개 폭풍'}};return `위력 ${power}% · ${detail[classId]?.[key]||'강화된 기술'}`;}
