// Permanent progression and migrations. No DOM dependencies.
export const ATTRIBUTE_DEFS=[{id:'strength',name:'Strength',text:'+1 attack, +0.25 armor'},{id:'dexterity',name:'Dexterity',text:'+1% critical chance, +0.5% attack speed'},{id:'intelligence',name:'Intelligence',text:'+3% skill damage'},{id:'focus',name:'Focus',text:'+5 mana, +0.15 mana/sec'},{id:'vitality',name:'Vitality',text:'+7 health'}];
export const SKILL_COST=[3,3,5,5,7];
export const AFFIXES=[{id:'ember',name:'Kindled',color:'#efad64',text:'Hits ignite enemies for 3 seconds',stat:'burn',value:4},{id:'frost',name:'Winterbound',color:'#91d7e4',text:'Hits slow enemies by 35%',stat:'slow',value:.35},{id:'storm',name:'Stormforged',color:'#adbcf5',text:'Every third hit arcs to another enemy',stat:'chain',value:1},{id:'vampire',name:'Sanguine',color:'#d98f9c',text:'Kills restore 2 health',stat:'lifekill',value:2}];
export function newHero(){return {level:1,xp:0,spec:0,skillPoints:0,attributePoints:0,skills:{q:1,e:0,passive:1,ultimate:0},attributes:{strength:0,dexterity:0,intelligence:0,focus:0,vitality:0},growthVersion:2};}
export function migrateGrowth(save){save.buildings.training??=0;save.growthLog??=[];save.milestones??={};for(const h of Object.values(save.heroes)){if(!h.growthVersion){h.skillPoints=3*Math.max(0,h.level-1);h.attributePoints=3*Math.max(0,h.level-1);h.skills={q:1,e:1,passive:1,ultimate:h.level>=10?1:0};h.attributes={strength:0,dexterity:0,intelligence:0,focus:0,vitality:0};h.growthVersion=2;}h.skills={q:1,e:0,passive:1,ultimate:0,...h.skills};h.attributes={strength:0,dexterity:0,intelligence:0,focus:0,vitality:0,...h.attributes};}for(const g of save.gear){g.baseValue??=g.value;g.upgrade??=0;g.ilvl??=1;g.affix??=null;}save.growthVersion=2;return save;}
export function rankLimit(save){return Math.min(5,2+(save.buildings.training||0));}
export function skillPrice(hero,key){return SKILL_COST[hero.skills[key]||0]??Infinity;}
export function trainSkill(save,hero,key){if(!['q','e','passive','ultimate'].includes(key))return {ok:false,reason:'Unknown skill'};const rank=hero.skills[key]||0,cost=skillPrice(hero,key);if(key==='ultimate'&&hero.level<10)return {ok:false,reason:'Reach hero level 10'};if(rank>=rankLimit(save))return {ok:false,reason:rank>=5?'Maximum rank':'Upgrade the Training Grounds'};if(hero.skillPoints<cost)return {ok:false,reason:`Need ${cost} skill points`};hero.skillPoints-=cost;hero.skills[key]=rank+1;return {ok:true,before:rank,after:rank+1,cost};}
export function allocateAttribute(hero,id){if(!ATTRIBUTE_DEFS.some(a=>a.id===id)||hero.attributePoints<1)return false;hero.attributePoints--;hero.attributes[id]++;return true;}
export function equipmentValue(g){const value=g.baseValue??g.value;return Math.round(value*(1+.22*(g.upgrade||0))*(g.stat==='crit'?1000:100))/(g.stat==='crit'?1000:100);}
export function forgeQuote(g){const n=g.upgrade||0;return {gold:30+25*n+5*(g.ilvl||1),stone:2+n,iron:n>=2?n-1:0,max:5};}
export function forgeGear(save,g){const q=forgeQuote(g),level=g.upgrade||0;if(level>=q.max)return {ok:false,reason:'Maximum upgrade'};if(level>=1+(save.buildings.forge||0))return {ok:false,reason:'Improve the Blacksmith to forge further'};if(save.gold<q.gold||save.stone<q.stone||save.iron<q.iron)return {ok:false,reason:'Not enough banked materials'};const before=equipmentValue(g);save.gold-=q.gold;save.stone-=q.stone;save.iron-=q.iron;g.upgrade=level+1;return {ok:true,before,after:equipmentValue(g)};}
export function skillDescription(classId,key,rank){const r=Math.max(1,rank);if(key==='passive')return `+${(r-1)*6}% attack damage · +${(r-1)*10} maximum health`;
 if(key==='ultimate')return `Specialization technique · ${r*55+100}% power · ${r>=3?'Enhanced area':'Unlock at hero level 10'}`;
 const power=Math.round((1+(r-1)*.3)*100);const detail={warrior:{q:r>=3?'Returning axes + an extra axe':'Two piercing spinning axes',e:`War cry: +${20+r*5}% attack speed; ${r>=3?'shockwave on cast':'speed aura'}`},paladin:{q:`Healing circle; ${r>=3?'larger radius and radiant pulses':'restore health over time'}`,e:r>=3?'Three piercing radiant hammers':'One piercing radiant hammer'},ranger:{q:`${3+2*r} arrows · ${r>=3?'ricochet sparks':'piercing volley'}`,e:r>=3?'Three snare patches':'One slowing snare field'},wizard:{q:r>=3?'Frost nova + eight ice shards':'Frost nova, slows nearby enemies',e:r>=3?'Three meteors':'One targeted meteor'},rogue:{q:`${8+4*r} piercing blades`,e:r>=3?'Shadowstep + blade nova':'Shadowstep and backstab'},warlock:{q:r>=3?'Soul drain + spectral bolts':'Drain life from nearby enemies',e:r>=3?'Three corruption fields':'One corruption field'},sorcerer:{q:`Chain lightning hits ${3+2*r} targets`,e:r>=3?'Expanded storm with orbiting sparks':'Persistent lightning storm'}};return `${power}% rank power · ${detail[classId]?.[key]||'Improved skill'}`;}
