// 생성 파일 — 손으로 고치지 않는다. 원본 ip/src/crew-sprites.mjs, 굽기 node ip/src/export-crew.mjs

export const CREW_SPRITE_W = 16;
export const CREW_SPRITE_H = 24;

export const CREW_COLORS: Record<string, string> = {
  "C": "#232c3e",
  "D": "#91663f",
  "G": "#a9a59b",
  "H": "#3a2f26",
  "L": "#f09a4a",
  "M": "#4a555e",
  "N": "#4d6084",
  "O": "#9c4318",
  "R": "#a22a22",
  "T": "#8a5a3a",
  "U": "#6b4430",
  "V": "#6f84a8",
  "Y": "#8a6218",
  "d": "#6f4a2d",
  "e": "#e3e0d8",
  "g": "#cfcbc2",
  "h": "#241f1a",
  "k": "#12100e",
  "m": "#98a4ad",
  "n": "#d2dade",
  "o": "#d9692b",
  "p": "#e9dcc0",
  "q": "#cbbd9c",
  "r": "#e4553a",
  "s": "#e6c79b",
  "t": "#c49a6c",
  "u": "#f0cd55",
  "v": "#2b3a4a",
  "w": "#efe6d2",
  "y": "#e0a92e"
};

export const CREW_ROWS = {
  "seo-gaon": [
    "............o...",
    "............o...",
    "............o...",
    "....kkkkk...o...",
    "...kwwwwwk..o...",
    "..kwwwwwwwk.o...",
    "..kwvvvvVwk.o...",
    "..kwvvvvvwkkokk.",
    "..kkwwwwwkkMmMk.",
    "...kkkkkkkkMMMk.",
    "..kLooooooookMk.",
    ".kLooooooooookk.",
    ".kLoOoooooOoook.",
    ".koOkwwwwkOoook.",
    ".koOkwkkwkOoook.",
    ".ktkkwwwwkkotk..",
    "..kkMMMMMMMMkk..",
    "...kooooooook...",
    "...kooOkkOook...",
    "...kooOkkOook...",
    "...kooOkkOook...",
    "...kMMMkkMMMk...",
    "..kMMMMkkMMMMk..",
    "..kkkkkk.kkkkk..",
  ],
  "mira-anyango": [
    "................",
    "................",
    "................",
    "....kkkk........",
    "...khhhhk.......",
    "..khhhhhhk......",
    "..khTTTThkk.....",
    "..khTkTTkknk....",
    "..khTTTTTkk.....",
    "...kTTUTk.......",
    "..kkkRkkkk......",
    ".kppkRkppk......",
    ".kppkRkkkkkkkkk.",
    ".kppkTkqqqqqqqk.",
    ".kppkkkqkkkkkqk.",
    ".kppppkqqqqqqqk.",
    ".kppppkqkkkqqqk.",
    ".kppppkqqqqqqqk.",
    ".kppppkkkkkkkkk.",
    ".kpppqppk.......",
    "..kppkppk.......",
    "..kppkppk.......",
    "..kHHkHHk.......",
    "..kkkkkkk.......",
  ],
  "jeong-dokyeong": [
    "................",
    "................",
    ".....kkkk.......",
    "....khhhhk......",
    "....khsssk......",
    "....kskssk......",
    "....kssssk......",
    ".....kssk.......",
    "..kkkkwwkkkk....",
    ".kNNNNkwkNNNk...",
    ".kNVNNNkNNNVk...",
    ".kNVNNNkNNNVk...",
    ".kNVNNNkNNNVk...",
    ".kNkNNNkNNNkk...",
    ".kskNNNkNNNksk..",
    ".kNNNNNkNNNk.k..",
    "kNNNNNkNNNk.kkkk",
    "kNNNNNkNNNk.kuMk",
    "kNNNNNkNNNk.kMMk",
    ".kNNNNkNNNk.kkkk",
    "..kCCk.kCCk.....",
    "..kCCk.kCCk.....",
    ".kkCCk.kCCkk....",
    ".kkkkk.kkkkk....",
  ],
  "haedal-hd8": [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "..k..k..........",
    ".kyk.kyk........",
    ".kyyyyyk........",
    "kyyyyyyyk.......",
    "kyvyyyvyk.kkkkk.",
    "kyyyyyyykkyyyyyk",
    ".kkyyyykyyyyyyyk",
    "kdDDdkkyYkYkYkyk",
    "kDddDkyyyyyyyyyk",
    "kdDDdkyykkkyyyyk",
    "kkkkkkyykuukyyyk",
    ".kmkkyyykkkkyyYk",
    ".kmkYYYYYYYYYYYk",
    ".kkkkkkkkkkkkkkk",
    ".kYk.kYk.kYk.kYk",
    ".kMk.kMk.kMk.kMk",
    ".kkk.kkk.kkk.kkk",
  ],
  "yeoe7": [
    "................",
    "................",
    "................",
    "................",
    "................",
    ".......ee.......",
    "......e..e......",
    "....geeeeeeg....",
    "....gGGGGGGg....",
    "....gGrrGGGg....",
    "....gGrrGGGg....",
    "....gGGGGGGg....",
    "....gggggggg....",
    "......kmmk......",
    "......kmmk......",
    ".....kmkkmk.....",
    ".....kmkkmk.....",
    "....kmk.kmk.....",
    "....kmkkkmk.....",
    "...kmk.km.kmk...",
    "...kmk.km.kmk...",
    "..kmk..km..kmk..",
    "..kmk..km..kmk..",
    ".kkk...kk...kkk.",
  ],
} as const;

export type CrewId = keyof typeof CREW_ROWS;
