import test from 'node:test';import assert from 'node:assert/strict';
import {createCampaignStore,CAMPAIGN_SAVE} from '../src/campaign/save.js';
import {createCampaignController} from '../src/campaign/controller.js';
function fixture(){const data=new Map();const storage={fail:null,getItem:key=>data.get(key)??null,setItem(key,value){if(this.fail===key)throw Error('quota');data.set(key,value);}};return {storage,data,store:createCampaignStore(storage)};}
const reward=(save,{id})=>{if(save.transactions.some(t=>t.id===id))return {ok:false,code:'DUPLICATE'};save.transactions.push({id});save.gold+=5;return {ok:true,save,events:[{type:'reward',id}]};};
test('failed persistence never acknowledges a reward or changes the visible snapshot',async()=>{const f=fixture(),c=createCampaignController(f.store),events=[];c.subscribe(e=>events.push(e));assert((await c.start('warrior')).ok);f.storage.fail=CAMPAIGN_SAVE.head;assert.equal((await c.dispatch({id:'chest'},reward)).code,'WRITE_FAILED');assert.equal(c.snapshot().gold,0);assert.equal(events.filter(e=>e.type==='committed').length,0);f.storage.fail=null;assert((await c.dispatch({id:'chest'},reward)).ok);assert.equal(c.snapshot().gold,5);assert.equal((await c.dispatch({id:'chest'},reward)).code,'DUPLICATE');assert.equal(f.store.load().save.gold,5);});
test('rapid commands are serialized against the last committed world',async()=>{const f=fixture(),c=createCampaignController(f.store);await c.start('warrior');const results=await Promise.all(['a','b','c'].map(id=>c.dispatch({id},reward)));assert(results.every(r=>r.ok));assert.equal(c.snapshot().gold,15);assert.equal(c.revision(),4);});
test('cross-tab conflict blocks stale commands until explicit reload',async()=>{const f=fixture(),a=createCampaignController(f.store),b=createCampaignController(f.store);await a.start('warrior');await b.load();await b.dispatch({id:'b'},reward);assert.equal((await a.dispatch({id:'a'},reward)).code,'CONFLICT');assert.equal((await a.dispatch({id:'a2'},reward)).blocked,true);await a.load();assert((await a.dispatch({id:'a'},reward)).ok);assert.equal(a.snapshot().gold,10);});
test('callers and failing listeners cannot mutate committed state or create a duplicate campaign',async()=>{const f=fixture(),c=createCampaignController(f.store);c.subscribe(()=>{throw Error('bad UI');});const start=await c.start('warrior');start.save.gold=999;assert.equal(c.snapshot().gold,0);assert.equal((await c.start('mage')).code,'CAMPAIGN_EXISTS');const own=c.snapshot();own.gold=99;assert.equal(c.snapshot().gold,0);assert.equal((await c.dispatch({id:'bad'},save=>{save.gold=99;throw Error('bad reducer');})).code,'COMMAND_FAILED');assert.equal(c.snapshot().gold,0);});
