// Isolated logic tests. These are NOT browser play-test evidence.
import fs from 'node:fs';import vm from 'node:vm';import assert from 'node:assert/strict';import * as data from '../src/data.js';import * as growth from '../src/growth.js';import * as visual from '../src/visual.js';import {ART} from '../src/art.js';import * as lifecycle from '../src/lifecycle.js';import * as motion from '../src/motion.js';import * as combat from '../src/combat.js';import * as encounters from '../src/encounters.js';import * as threats from '../src/threat-visibility.js';import * as legacyTelegraphs from '../src/legacy-telegraphs.js';
const nodes=new Map(),events={},storage=new Map();const noop=()=>{};const context=new Proxy({createRadialGradient:()=>({addColorStop:noop})},{get:(t,k)=>t[k]||noop});function node(id){if(!nodes.has(id))nodes.set(id,{innerHTML:'',textContent:'',style:{},classList:{add:noop,remove:noop},addEventListener:(k,f)=>{events[id+':'+k]=f;},getContext:()=>context,focus:noop,getBoundingClientRect:()=>({left:0,top:0,width:1280,height:800})});return nodes.get(id);}
const sandbox={...data,...growth,...visual,...combat,...encounters,...motion,...lifecycle,...threats,...legacyTelegraphs,createFantasyAudio:()=>({play:()=>false,cancel:()=>{},resume:()=>Promise.resolve(false),setEnabled:()=>Promise.resolve(false),tick:()=>{},pause:()=>{}}),ART,console,Math,Date,performance:{now:()=>0},AudioContext:function(){},document:{querySelector:node,querySelectorAll:()=>[],getElementById:node,addEventListener:noop,hidden:false},window:{addEventListener:noop},localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)},requestAnimationFrame:noop};vm.createContext(sandbox);let code=fs.readFileSync(new URL('../src/game.js',import.meta.url),'utf8').replace(/^import .*\n/gm,'');vm.runInContext(code+'\nglobalThis.test={beginRun,loadFloor,resumeRun,stats,skill,attack,dodge,cancelCombatAction,closePanel,kill,damagePlayer,finishRun,persist,render,update,interact,createGear,buildingsPanel,inventoryPanel,guide,pauseMenu,read:()=>({save,run,p,map,entities,objects,shots,effects,hitstop,dummyRecord}),clearEnemies:()=>{entities=[];},clearEffects:()=>{effects=[];shots=[];hitstop=0;},addTarget:e=>{entities.push(e);return e;},setMouse:v=>Object.assign(mouse,v),setClass:id=>{selected=id;save.classId=id;},setPlayer:v=>Object.assign(p,v),floor:n=>{run.floor=n;loadFloor();},selectRelic:id=>run.relics.push(id),setGold:n=>run.gold=n};',sandbox);
const t=sandbox.test;t.render();for(let c of data.CLASSES){t.setClass(c.id);t.beginRun();{let h=t.read().save.heroes[c.id];h.skills.q=3;h.skills.e=3;}t.render();assert(t.skill('q'));for(let i=0;i<90;i++)t.update(1/60);assert(t.skill('e'));for(let i=0;i<90;i++)t.update(1/60);t.attack();for(let i=0;i<120;i++)t.update(1/60);t.render();t.inventoryPanel();t.guide();t.pauseMenu();t.finishRun();}
t.setClass('warrior');t.beginRun();for(let f=0;f<6;f++){t.floor(f);t.render();for(let i=0;i<5;i++)t.createGear();let state=t.read();for(let e of state.entities)if(e.type!=='dummy')t.kill(e);t.render();}t.setGold(100);t.persist();let before=JSON.parse(storage.get('emberwatch-save'));assert(before.run);t.resumeRun();assert.equal(t.read().run.floor,5);let gold=t.read().save.gold;t.finishRun(false);assert.equal(t.read().save.gold-gold,60);t.beginRun();t.setGold(100);gold=t.read().save.gold;t.finishRun(true);assert.equal(t.read().save.gold-gold,100);assert.equal(t.read().save.wins,1);t.buildingsPanel();console.log('PASS: all seven class skills, six floor rendering paths, equipment, boss deaths, save/resume, 60% death settlement and 100% victory settlement in an isolated mock runtime. Not browser QA.');

// Warrior-first action acceptance: actual runtime events in the isolated harness.
t.setClass('warrior');t.beginRun();t.clearEnemies();let state=t.read();state.save.heroes.warrior.skills.e=3;state.save.heroes.warrior.skills.q=3;state.p.angle=0;
let target=t.addTarget({type:'dummy',x:state.p.x+40,y:state.p.y,hp:1e9,max:1e9,r:12,active:false,walk:0});
let baseline=state.dummyRecord.hits;assert(t.attack());assert.equal(t.read().dummyRecord.hits,baseline);for(let i=0;i<5;i++)t.update(1/120);assert.equal(t.read().dummyRecord.hits,baseline,'No startup damage');for(let i=0;i<90;i++)t.update(1/120);assert.equal(t.read().dummyRecord.hits,baseline+1,'Exactly one basic contact');
t.setPlayer({attack:0,action:null,dash:0});assert(t.attack());assert(t.dodge());for(let i=0;i<100;i++)t.update(1/120);assert.equal(t.read().dummyRecord.hits,baseline+1,'Canceled windup cannot ghost hit');
t.clearEffects();t.setPlayer({attack:0,action:null,dashTime:0,q:0,mana:100});let mana=t.read().p.mana;assert(t.skill('q'));assert.equal(t.read().shots.length,0,'Axes wait for release');assert.equal(t.read().p.mana,mana,'Uncommitted skill does not spend mana');for(let i=0;i<20;i++)t.update(1/120);assert.equal(t.read().shots.length,3,'Evolved axes emitted once at release');assert(t.read().p.mana<mana-20);for(let i=0;i<70;i++)t.update(1/120);
t.setPlayer({action:null,e:0,mana:100});assert(t.skill('e'));assert.equal(t.read().p.warcry,0);for(let i=0;i<60;i++)t.update(1/120);assert(t.read().p.warcry>7,'War Cry begins only after its contact');
t.clearEnemies();t.clearEffects();t.setPlayer({action:null,attack:0});assert(t.attack());for(let i=0;i<70;i++)t.update(1/120);assert.equal(t.read().hitstop,0,'Whiff never applies hitstop');
t.damagePlayer(1e9,{x:t.read().p.x-10,y:t.read().p.y});assert(t.read().p.deathTime>0);assert(t.read().run,'Death animation retains scene briefly');for(let i=0;i<120;i++)t.update(1/120);assert.equal(t.read().run,null,'Death completes deterministically');
console.log('PASS: Warrior delayed contacts, startup cancellation, three evolved axes, War Cry release, miss feedback and death sequence. Not browser gameplay.');

// Dodge reward and early dash-strike cancellation are intentional Warrior options.
t.setClass('warrior');t.beginRun();t.clearEnemies();t.setPlayer({action:null,dash:0,invuln:0,counterTime:0});assert(t.dodge());let hpBefore=t.read().p.hp;t.damagePlayer(10,{x:t.read().p.x+5,y:t.read().p.y});assert.equal(t.read().p.hp,hpBefore);assert(t.read().p.counterTime>0);t.setPlayer({action:{name:'dodge',elapsed:.17,duration:.3,contact:.3,payload:{kind:'dodge'}},dashTime:.07,attack:0});assert(t.attack());assert(t.read().p.action.payload.dashStrike);assert(t.read().p.action.payload.counter);assert.equal(t.read().p.action.contact,.08);assert.equal(t.read().p.dashTime,0,'Dash-strike gives up remaining iframe');console.log('PASS: evade counter reward and dash-strike risk/reward. Logic only.');
