// Runtime menu strings and bundled-font contracts. Not browser layout/play evidence.
import assert from 'node:assert/strict';import fs from 'node:fs';import {spawnSync} from 'node:child_process';
import {nextJourneyGoal,resourceLine,retentionRate} from '../src/lifecycle.js';import {defaultSave} from '../src/data.js';import {newHero,migrateGrowth} from '../src/growth.js';
const capture=spawnSync(process.execPath,[new URL('../scripts/capture-korean-ui.mjs',import.meta.url).pathname],{encoding:'utf8'});assert.equal(capture.status,0,capture.stderr);
const report=JSON.parse(fs.readFileSync(new URL('../../assets/screenshots/korean-0.4.1/runtime-ui-snapshots.json',import.meta.url),'utf8'));
const allowed=new Set(['Tab','WASD','Space','Esc','Emberwatch','RPG','Battlecry','spookymodem','CC','BY']);
for(const page of report.snapshots){const text=page.html.replace(/<[^>]*>/g,' ');assert(/[가-힣]/.test(text),page.name+' Korean text');for(const word of text.match(/[A-Za-z]{2,}/g)||[])assert(allowed.has(word),page.name+' has untranslated display word: '+word);}
assert.equal(report.snapshots.length,12);assert(report.inputChecks.every(Boolean),'Korean keyboard layout maps physical game keys');const first=report.snapshots[0].html;assert(first.indexOf('id="startQuick"')<first.indexOf('id="classes"'),'first-entry start action precedes long roster');
const font=fs.readFileSync(new URL('../src/assets/fonts/EmberwatchKorean-Regular.woff',import.meta.url));assert.equal(font.subarray(0,4).toString(),'wOFF');
const provenance=JSON.parse(fs.readFileSync(new URL('../../assets/fonts/provenance.json',import.meta.url),'utf8'));assert.equal(provenance.modern_hangul_syllables,11172);assert(fs.readFileSync(new URL('../src/assets/fonts/OFL-EmberwatchKorean.txt',import.meta.url),'utf8').includes('SIL OPEN FONT LICENSE'));
const html=fs.readFileSync(new URL('../src/index.html',import.meta.url),'utf8'),game=fs.readFileSync(new URL('../src/game.js',import.meta.url),'utf8'),css=fs.readFileSync(new URL('../src/style.css',import.meta.url),'utf8');assert(html.includes('lang="ko"'));assert(html.includes('SIL OPEN FONT LICENSE'));assert(html.includes('id="fontLicense"'));assert(html.includes('id="saveAlert"'));assert(html.includes('id="mapToggle"'));assert(game.includes("if(key==='m'"));assert(game.includes("event.code.slice(3).toLowerCase()"));assert(!css.includes('fonts.googleapis.com'));assert(css.includes('@font-face'));
let s=defaultSave();migrateGrowth(s);s.heroes.warrior=newHero();assert.equal(nextJourneyGoal(s).id,'first-chest');s.milestones.firstChestGear=true;assert.equal(nextJourneyGoal(s).id,'equip');s.gear=[{id:'w',slot:'weapon'}];s.equipped.weapon='w';assert.equal(nextJourneyGoal(s).id,'level-two');s.heroes.warrior.level=2;assert.equal(nextJourneyGoal(s).id,'learn-e');s.heroes.warrior.skills.e=1;assert.equal(nextJourneyGoal(s).id,'guardian');s.heroes.warrior.skills.q=2;assert.equal(nextJourneyGoal(s).id,'training-ground');s.buildings.training=1;assert.equal(nextJourneyGoal(s).id,'guardian');assert.equal(retentionRate(s),.6);assert.equal(retentionRate(s,true),1);assert.equal(resourceLine({gold:5,wood:2,stone:1,iron:0}),'금화 5 · 목재 2 · 석재 1 · 철광석 0');
console.log('PASS:12 actual-runtime menu snapshots in Korean, bundled licensed font, physical-key/map/save-warning hooks, and progressive next-goal contracts. Not browser layout/play QA.');
