/**
 * 메트로폴리탄 `Object Name`(통제 어휘) → 한국어 유물명 + shape + 기본 palette.
 *
 * **이 표가 수집 필터다.** 여기 없는 이름은 후보에서 아예 빠진다 — 그래서
 * "파편(fragment)"·"조각(piece)"·"미상(undetermined)" 같은 카탈로그 부스러기가
 * 도감에 들어오지 않는다. 한국어 이름이 100% 채워지는 것도 이 구조 덕이다
 * (기계 번역이 아니라 유물 종류별로 손으로 고른 역어를 쓴다).
 *
 * `shape`는 도트 스프라이트 생성 입력이자 시세 카테고리다(notes/world-map.md §8.1).
 * `palette`는 기본값일 뿐이고, 메트 `Medium`에 재질이 적혀 있으면 그쪽이 이긴다
 * (build-artifacts.mjs의 `paletteFromMedium`).
 */

/** [메트 Object Name(소문자), 한국어, shape, 기본 palette] */
const RAW = [
  // ── 용기·토기 ──────────────────────────────────────────────────────────
  ["jar", "항아리", "jar", "earthenware"],
  ["covered jar", "뚜껑 항아리", "jar", "earthenware"],
  ["bowl", "발(鉢)", "jar", "earthenware"],
  ["covered bowl", "뚜껑 발", "jar", "celadon"],
  ["dish", "접시", "jar", "celadon"],
  ["plate", "반(盤)", "jar", "celadon"],
  ["saucer", "받침 접시", "jar", "celadon"],
  ["cup", "잔", "jar", "celadon"],
  ["wine cup", "술잔", "jar", "celadon"],
  ["soba cup", "소바 잔", "jar", "celadon"],
  ["teabowl", "찻사발", "jar", "celadon"],
  ["tea jar", "차 항아리", "jar", "celadon"],
  ["teapot", "주전자", "jar", "celadon"],
  ["water jar", "물 항아리", "jar", "earthenware"],
  ["vase", "화병", "jar", "celadon"],
  ["bottle vase", "병형 화병", "jar", "celadon"],
  ["bottle", "병", "jar", "glass"],
  ["wine bottle", "술병", "jar", "glass"],
  ["snuff bottle", "코담배 병", "jar", "glass"],
  ["perfume bottle", "향유병", "jar", "glass"],
  ["flask", "편병", "jar", "glass"],
  ["beaker", "굽 없는 잔", "jar", "glass"],
  ["goblet", "굽다리 잔", "jar", "glass"],
  ["jug", "주자(注子)", "jar", "earthenware"],
  ["juglet", "소형 주자", "jar", "earthenware"],
  ["pitcher", "물주전자", "jar", "earthenware"],
  ["ewer", "정병(淨甁)", "jar", "silver"],
  ["vessel", "용기", "jar", "earthenware"],
  ["vessel with lid", "뚜껑 용기", "jar", "earthenware"],
  ["pot", "단지", "jar", "earthenware"],
  ["tray", "쟁반", "jar", "wood"],
  ["platter", "큰 접시", "jar", "celadon"],
  ["basket", "바구니", "jar", "wood"],
  ["basket with lid", "뚜껑 바구니", "jar", "wood"],
  ["box", "합(盒)", "jar", "wood"],
  ["covered box", "뚜껑 합", "jar", "wood"],
  ["incense box", "향합", "jar", "gold"],
  ["writing box", "연상(硯床)", "jar", "wood"],
  ["pen box", "필통", "jar", "wood"],
  ["brush holder", "필가(筆架)", "jar", "celadon"],
  ["kohl jar", "콜 단지", "jar", "stone"],
  ["cosmetic container", "화장 용기", "jar", "stone"],
  ["container", "담는 그릇", "jar", "earthenware"],
  ["lid", "뚜껑", "jar", "earthenware"],
  ["cover", "덮개", "jar", "earthenware"],
  ["incense burner", "향로", "jar", "gold"],
  ["lamp", "등잔", "jar", "earthenware"],
  ["mosque lamp", "모스크 등", "jar", "glass"],
  ["candlestick", "촛대", "mechanism", "silver"],
  ["rhyton", "리톤", "jar", "gold"],
  ["mortar", "절구", "jar", "stone"],
  ["spoon", "숟가락", "mechanism", "silver"],
  ["lime spoon", "석회 숟가락", "mechanism", "wood"],
  ["kero", "케로 잔", "jar", "wood"],
  // ── 그리스·로마 기형(고유명이라 그대로 음차한다) ─────────────────────────
  ["kylix", "킬릭스", "jar", "earthenware"],
  ["skyphos", "스키포스", "jar", "earthenware"],
  ["amphora", "암포라", "jar", "earthenware"],
  ["neck-amphora", "목 암포라", "jar", "earthenware"],
  ["amphoriskos", "소형 암포라", "jar", "glass"],
  ["lekythos", "레키토스", "jar", "earthenware"],
  ["squat lekythos", "단형 레키토스", "jar", "earthenware"],
  ["oinochoe", "오이노코에", "jar", "earthenware"],
  ["olpe", "올페", "jar", "earthenware"],
  ["hydria", "히드리아", "jar", "earthenware"],
  ["pelike", "펠리케", "jar", "earthenware"],
  ["stamnos", "스탐노스", "jar", "earthenware"],
  ["kantharos", "칸타로스", "jar", "earthenware"],
  ["kyathos", "키아토스", "jar", "earthenware"],
  ["alabastron", "알라바스트론", "jar", "glass"],
  ["aryballos", "아리발로스", "jar", "earthenware"],
  ["pyxis", "픽시스", "jar", "earthenware"],
  ["pyxis with lid", "뚜껑 픽시스", "jar", "earthenware"],
  ["column-krater", "기둥형 크라테르", "jar", "earthenware"],
  ["calyx-krater", "꽃받침형 크라테르", "jar", "earthenware"],
  ["bell-krater", "종형 크라테르", "jar", "earthenware"],
  ["volute-krater", "소용돌이형 크라테르", "jar", "earthenware"],
  ["krater", "크라테르", "jar", "earthenware"],
  ["lekanis", "레카니스", "jar", "earthenware"],
  ["mastoid", "마스토이드 잔", "jar", "earthenware"],
  // ── 장신구 ────────────────────────────────────────────────────────────
  ["ring", "반지", "ornament", "gold"],
  ["earring", "귀걸이", "ornament", "gold"],
  ["ear ornament", "귀 장식", "ornament", "gold"],
  ["earflare", "귀 확장 장식", "ornament", "gold"],
  ["nose ornament", "코 장식", "ornament", "gold"],
  ["necklace", "목걸이", "ornament", "gold"],
  ["pendant", "드리개", "ornament", "gold"],
  ["bracelet", "팔찌", "ornament", "gold"],
  ["bangle", "고리 팔찌", "ornament", "gold"],
  ["armband", "팔 장식", "ornament", "gold"],
  ["armlet", "위팔 장식", "ornament", "gold"],
  ["anklet", "발찌", "ornament", "gold"],
  ["bead", "구슬", "ornament", "glass"],
  ["beads", "구슬 꿰미", "ornament", "glass"],
  ["string of beads", "구슬 목걸이", "ornament", "glass"],
  ["brooch", "브로치", "ornament", "gold"],
  ["fibula", "피불라", "ornament", "silver"],
  ["pin", "비녀", "ornament", "silver"],
  ["hair pin", "머리 비녀", "ornament", "silver"],
  ["comb", "빗", "ornament", "wood"],
  ["belt buckle", "허리띠 고리", "ornament", "gold"],
  ["belt hook", "띠고리", "ornament", "gold"],
  ["belt", "허리띠", "ornament", "gold"],
  ["girdle ornament", "요대 장식", "ornament", "gold"],
  ["dress ornament", "의복 장식", "ornament", "gold"],
  ["costume ornament", "복식 장식", "ornament", "gold"],
  ["garment plaque", "의복 패식", "ornament", "gold"],
  ["ornament", "장식구", "ornament", "gold"],
  ["medallion", "메달 장식", "ornament", "gold"],
  ["roundel", "원형 장식", "ornament", "gold"],
  ["plaque", "패식(牌飾)", "ornament", "gold"],
  ["finial", "정상 장식", "ornament", "gold"],
  ["diadem", "관식(冠飾)", "crown", "gold"],
  ["crown", "관(冠)", "crown", "gold"],
  ["headdress", "머리 장식", "crown", "gold"],
  ["headband", "머리띠", "crown", "gold"],
  ["hat", "모자", "crown", "wood"],
  ["cameo", "카메오", "ornament", "stone"],
  ["intaglio", "음각 보석", "ornament", "stone"],
  ["scaraboid", "스카라보이드", "ornament", "stone"],
  ["amulet", "부적", "ornament", "stone"],
  ["charm", "호부(護符)", "ornament", "stone"],
  ["talisman", "호신부", "ornament", "stone"],
  ["mirror", "거울", "ornament", "silver"],
  ["buckle", "교구(鉸具)", "ornament", "gold"],
  ["button", "단추", "ornament", "silver"],
  ["stud", "장식 못", "ornament", "gold"],
  ["disk", "원판 장식", "ornament", "gold"],
  ["disc", "원반", "ornament", "gold"],
  ["inlay", "상감 장식", "ornament", "gold"],
  ["appliqué", "부착 장식", "ornament", "gold"],
  ["rank badge", "흉배(胸背)", "ornament", "gold"],
  ["netsuke", "네쓰케", "ornament", "wood"],
  ["ojime", "오지메", "ornament", "wood"],
  ["inrō", "인로", "ornament", "wood"],
  ["inro", "인로", "ornament", "wood"],
  ["toggle", "띠돈", "ornament", "wood"],
  // ── 조각·상 ───────────────────────────────────────────────────────────
  ["figure", "인물상", "statue", "stone"],
  ["female figure", "여인상", "statue", "stone"],
  ["male figure", "남자상", "statue", "stone"],
  ["twin figure", "쌍둥이상", "statue", "wood"],
  ["figurine", "소조상", "statue", "earthenware"],
  ["statuette", "소상(小像)", "statue", "gold"],
  ["statue", "상(像)", "statue", "stone"],
  ["sculpture", "조각상", "statue", "stone"],
  ["head", "두상", "statue", "stone"],
  ["bust", "흉상", "statue", "stone"],
  ["relief", "부조", "tablet", "stone"],
  ["funerary relief", "장례 부조", "tablet", "stone"],
  ["stele", "비석", "tablet", "stone"],
  ["stela", "석비", "tablet", "stone"],
  ["mask", "가면", "mask", "wood"],
  ["shabti", "샵티", "statue", "earthenware"],
  ["ushabti", "우샤브티", "statue", "earthenware"],
  ["scarab", "스카라베", "ornament", "stone"],
  ["canopic jar", "카노푸스 단지", "jar", "earthenware"],
  ["katsina", "카치나 인형", "statue", "wood"],
  ["ancestor pole", "조상 기둥", "statue", "wood"],
  ["architectural model", "건축 모형", "statue", "earthenware"],
  ["model", "모형", "statue", "earthenware"],
  ["capital", "주두(柱頭)", "statue", "stone"],
  ["ritual stone", "의례용 석기", "statue", "stone"],
  ["celt", "간돌도끼", "sword", "stone"],
  ["mace head", "철퇴 머리", "sword", "stone"],
  ["headrest", "목침", "statue", "wood"],
  ["stool", "걸상", "statue", "wood"],
  ["drum", "북", "mechanism", "wood"],
  ["bell", "종(鐘)", "mechanism", "gold"],
  ["rattle bell", "방울", "mechanism", "gold"],
  ["rattle", "딸랑이", "mechanism", "earthenware"],
  ["whistle", "호루라기", "mechanism", "earthenware"],
  ["horn", "뿔피리", "mechanism", "wood"],
  // ── 문서·인장 ─────────────────────────────────────────────────────────
  ["cuneiform tablet", "설형문자 점토판", "tablet", "earthenware"],
  ["cuneiform cylinder", "설형문자 원통", "tablet", "earthenware"],
  ["cuneiform cone", "설형문자 원추", "tablet", "earthenware"],
  ["cylinder seal", "원통 인장", "tablet", "stone"],
  ["stamp seal", "스탬프 인장", "tablet", "stone"],
  ["seal", "인장", "tablet", "stone"],
  ["seal stamp", "도장", "tablet", "stone"],
  ["sealing", "봉니(封泥)", "tablet", "earthenware"],
  ["bulla", "봉인구", "tablet", "earthenware"],
  ["ostracon", "도편 문서", "tablet", "earthenware"],
  ["hanging scroll", "족자", "scroll", "wood"],
  ["handscroll", "두루마리", "scroll", "wood"],
  ["album leaf", "화첩 낱장", "scroll", "wood"],
  ["album", "화첩", "scroll", "wood"],
  ["folio", "사본 낱장", "scroll", "wood"],
  ["illustrated book", "삽화본", "scroll", "wood"],
  ["sketchbook", "화고(畵稿)", "scroll", "wood"],
  ["sutra cover", "경전 표지", "scroll", "gold"],
  ["bookbinding", "장정(裝幀)", "scroll", "gold"],
  ["rubbing", "탁본", "scroll", "wood"],
  ["ink tablet", "먹", "tablet", "stone"],
  ["palette", "팔레트", "tablet", "stone"],
  ["tile", "기와", "tablet", "earthenware"],
  ["brick", "벽돌", "tablet", "earthenware"],
  ["weight", "저울추", "tablet", "stone"],
  ["coin weight", "화폐 저울추", "tablet", "glass"],
  ["playing card", "놀이패", "tablet", "wood"],
  ["chess piece", "장기말", "tablet", "wood"],
  ["gaming piece", "놀이말", "tablet", "wood"],
  ["game piece", "놀이 알", "tablet", "stone"],
  // ── 화폐 ──────────────────────────────────────────────────────────────
  ["coin", "주화", "coin", "silver"],
  ["token", "전표", "coin", "silver"],
  // ── 무기·공구 ─────────────────────────────────────────────────────────
  ["sword", "검", "sword", "silver"],
  ["dagger", "단검", "sword", "silver"],
  ["dagger blade", "단검 몸", "sword", "silver"],
  ["knife", "칼", "sword", "silver"],
  ["blade", "도신(刀身)", "sword", "silver"],
  ["spearhead", "창끝", "sword", "silver"],
  ["spear", "창", "sword", "wood"],
  ["arrowhead", "화살촉", "sword", "silver"],
  ["arrow", "화살", "sword", "wood"],
  ["arrow point", "촉", "sword", "stone"],
  ["axe", "도끼", "sword", "silver"],
  ["ax", "도끼", "sword", "silver"],
  ["hafted ax", "자루 도끼", "sword", "wood"],
  ["hatchet", "손도끼", "sword", "silver"],
  ["adze", "자귀", "sword", "silver"],
  ["chisel", "끌", "sword", "silver"],
  ["awl", "송곳", "sword", "silver"],
  ["club", "곤봉", "sword", "wood"],
  ["mace", "철퇴", "sword", "silver"],
  ["shield", "방패", "sword", "wood"],
  ["armor", "갑옷", "sword", "silver"],
  ["helmet", "투구", "crown", "silver"],
  ["sword guard", "코등이", "sword", "silver"],
  ["spear thrower", "투창기", "sword", "wood"],
  ["paddle", "노", "sword", "wood"],
  ["staff", "지팡이", "sword", "wood"],
  ["fish hook", "낚시바늘", "mechanism", "silver"],
  ["tool", "공구", "mechanism", "silver"],
  ["spindle whorl", "가락바퀴", "mechanism", "earthenware"],
  ["spindle", "물레 가락", "mechanism", "wood"],
  ["heddle pulley", "베틀 도르래", "mechanism", "wood"],
  ["loom", "베틀", "mechanism", "wood"],
  ["whetstone", "숫돌", "mechanism", "stone"],
  ["scraper", "긁개", "mechanism", "stone"],
  ["horse bit", "재갈", "mechanism", "silver"],
  ["harness ring", "마구 고리", "mechanism", "silver"],
  ["standard top", "의장 장식", "mechanism", "silver"],
  ["furniture element", "가구 부재", "mechanism", "wood"],
  ["handle", "손잡이", "mechanism", "silver"],
  ["fan", "부채", "mechanism", "wood"],
  ["folding fan", "쥘부채", "mechanism", "wood"],
  ["screen", "병풍", "scroll", "wood"],
  ["window", "창호", "mechanism", "wood"],
  ["cricket cage", "귀뚜라미 집", "mechanism", "wood"],
  ["water filter", "물거르개", "mechanism", "earthenware"],
  ["bath scraper", "때밀개", "mechanism", "silver"],
  // ── 직물·복식 ─────────────────────────────────────────────────────────
  ["carpet", "양탄자", "scroll", "wood"],
  ["textile", "직물", "scroll", "wood"],
  ["cloth", "천", "scroll", "wood"],
  ["hanging", "벽걸이", "scroll", "wood"],
  ["robe", "포(袍)", "scroll", "gold"],
  ["coat", "외투", "scroll", "gold"],
  ["kimono", "기모노", "scroll", "gold"],
  ["kaftan", "카프탄", "scroll", "gold"],
  ["tunic", "튜닉", "scroll", "wood"],
  ["mantle", "망토", "scroll", "wood"],
  ["poncho", "판초", "scroll", "wood"],
  ["skirt", "치마", "scroll", "wood"],
  ["sash", "띠", "scroll", "gold"],
  ["shawl", "숄", "scroll", "wood"],
  ["sari", "사리", "scroll", "gold"],
  ["bag", "주머니", "scroll", "wood"],
  ["saddle bag", "안장 주머니", "scroll", "wood"],
  ["blanket", "담요", "scroll", "wood"],
  ["cushion cover", "방석 덮개", "scroll", "wood"],
  ["banner", "깃발", "scroll", "wood"],
  ["altar cloth", "제단보", "scroll", "gold"],
  ["sleeve band", "소매 단", "scroll", "gold"]
];

export const LEXICON = new Map(RAW.map(([en, ko, shape, palette]) => [en, { ko, shape, palette }]));

/**
 * 메트 이름을 어휘 키로 접는다. 괄호 주기·쉼표 뒤 한정어를 떼고 단수형으로 맞춘다.
 * 단서를 떼는 게 아니라 **같은 종류를 한 종으로 묶기 위한** 정규화다 —
 * "jar, cylindrical"과 "jar"는 같은 항아리고, 시대·거점이 그 둘을 이미 가른다.
 */
export function lexKey(objectName) {
  let s = (objectName || "").toLowerCase().trim();
  if (!s) return null;
  s = s.replace(/\([^)]*\)/g, " ");        // 괄호 주기 제거
  s = s.split(/[,;?]/)[0];                  // 쉼표·물음표 뒤 한정어 제거
  s = s.split(/ with | for | from | mounted /)[0];  // "~ with stopper" 류 부속 설명 제거
  s = s.replace(/[^a-zÀ-ɏḀ-ỿ'\- ]/g, " ").replace(/\s+/g, " ").trim();
  if (!s) return null;
  if (LEXICON.has(s)) return s;
  const singular = s.replace(/ies$/, "y").replace(/([^s])s$/, "$1");
  if (LEXICON.has(singular)) return singular;
  // "bronze jar" 처럼 앞에 재질이 붙은 형태 — 마지막 1~3단어로 재시도
  const w = s.split(" ");
  for (let n = 1; n <= 3 && n <= w.length; n++) {
    const tail = w.slice(w.length - n).join(" ");
    if (LEXICON.has(tail)) return tail;
    const tailSingular = tail.replace(/ies$/, "y").replace(/([^s])s$/, "$1");
    if (LEXICON.has(tailSingular)) return tailSingular;
  }
  return null;
}
