import test from 'node:test';import assert from 'node:assert/strict';
import {World,type TargetInfo} from './world';import {createGame,act,tickEconomy,parseSave,serializeGame,type CardId} from './model';
Object.assign(globalThis,{requestAnimationFrame:()=>1,cancelAnimationFrame:()=>{},ResizeObserver:class{observe(){}disconnect(){}}});
function harness(){const state=createGame(),messages:string[]=[];let target:TargetInfo|null=null;let card:CardId='card';const canvas={width:1280,height:650,getContext:()=>({}),getBoundingClientRect:()=>({width:1280,height:650})} as unknown as HTMLCanvasElement;const world=new World(canvas,{state:()=>state,action:a=>act(state,a),damage:n=>{state.hp=Math.max(0,state.hp-n)},restore:n=>{state.hp=Math.min(state.maxHp,state.hp+n)},notify:m=>messages.push(m),sound:()=>{},onTarget:t=>target=t,onPosition:()=>{},onGatherPrompt:()=>{},card:()=>card,onCamp:()=>{}});world.paused=false;const advance=(seconds:number)=>{for(let i=0;i<Math.ceil(seconds*60);i++)world.update(1/60)};return{world,state,messages,advance,target:()=>target,setCard:(c:CardId)=>card=c};}
test('scene starter loop gathers, crafts, weakens, captures and enters camp',()=>{const h=harness();h.world.command('gather');assert.equal(h.state.stats.woodGathered,5);assert.ok(act(h.state,{type:'craft',recipeId:'sword'}).ok);tickEconomy(h.state,3);assert.equal(h.state.equipment.weapon,1);h.world.player.x=300;h.world.command('attack');const slime=h.world.wild.find(m=>m.id===8)!;assert.ok(slime.hp<slime.maxHp);h.world.command('capture');assert.equal(h.state.monsters.length,1);assert.equal(slime.hp,0);assert.ok(act(h.state,{type:'camp'}).ok);h.world.setMode('camp');assert.equal(h.world.mode,'camp');assert.ok(parseSave(serializeGame(h.state)).ok);});
test('pause rejects commands, clears held keys and resumes safely',()=>{const h=harness();h.world.keys.add('right');h.world.setPaused(true);assert.equal(h.world.keys.size,0);h.world.command('gather');assert.equal(h.state.inventory.wood,0);h.world.setPaused(false);h.world.command('gather');assert.equal(h.state.inventory.wood,5);});
test('walking is bounded and jump lands on an elevated one-way platform',()=>{const h=harness();h.world.player.x=450;h.world.command('jump');h.advance(.25);assert.ok(h.world.player.y<386);h.advance(.7);assert.equal(h.world.player.y,386);assert.ok(h.world.player.grounded);h.world.keys.add('left');h.advance(10);assert.equal(h.world.player.x,42);});
test('first slime cannot die before the first capture',()=>{const h=harness();h.world.player.x=300;const slime=h.world.wild.find(m=>m.id===8)!;for(let i=0;i<12;i++){h.world.command('attack');h.advance(.4)}assert.ok(slime.hp>=1);});
test('capture cooldown blocks repeated card consumption',()=>{const h=harness();h.world.player.x=530;h.world.command('capture');const cards=h.state.inventory.card;for(let i=0;i<10;i++)h.world.command('capture');assert.equal(h.state.inventory.card,cards);assert.equal(h.state.monsters.length,1);});
test('dead and guardian capture attempts consume no cards',()=>{const h=harness();h.world.player.x=3090;const cards=h.state.inventory.card;h.world.command('capture');assert.equal(h.state.inventory.card,cards);assert.match(h.messages.at(-1)!,/포획할 수 없/);h.world.player.x=800;h.world.wild.forEach(m=>m.hp=0);h.world.command('capture');assert.equal(h.state.inventory.card,cards);});
test('target reports royal-card odds and encountered species',()=>{const h=harness();act(h.state,{type:'capture',species:'slime',hpRatio:1,roll:0});h.world.player.x=1040;h.setCard('royalCard');h.advance(.2);assert.ok(h.target());assert.ok(h.state.encountered.includes('mushroom'));assert.ok(h.target()!.chance>.6);});
test('resource cooldown prevents spam and renews',()=>{const h=harness();h.world.command('gather');h.world.command('gather');assert.equal(h.state.stats.woodGathered,5);h.advance(12.1);h.world.command('gather');assert.equal(h.state.stats.woodGathered,10);});
test('field crystal-shaped ore node does not grant boss crystals',()=>{const h=harness();h.world.player.x=2490;h.world.command('gather');assert.equal(h.state.inventory.ore,2);assert.equal(h.state.inventory.crystal,0);});
test('slime, stump and rare partner abilities differ',()=>{const h=harness();for(const species of ['slime','stump','rare'] as const){act(h.state,{type:'capture',species,hpRatio:.1,roll:0});act(h.state,{type:'partner',monsterId:h.state.monsters.at(-1)!.id});h.world.player.partner=0;h.state.hp=50;h.world.command('partner');if(species==='slime')assert.equal(h.world.player.vy,-760);if(species==='stump')assert.equal(h.world.player.shield,6);if(species==='rare')assert.equal(h.state.hp,80);}});
test('guardian alternates ground shockwave and overhead spores',()=>{const h=harness(),boss=h.world.wild.find(m=>m.species==='guardian')!;h.world.player.x=boss.x+100;boss.attack=0;h.advance(.05);assert.ok(boss.telegraph>0);assert.equal(boss.phase,0);h.advance(1.15);assert.equal(h.state.hp,77);assert.equal(boss.phase,1);h.world.player.hurt=0;boss.attack=0;h.advance(1.3);assert.equal(h.state.hp,77);assert.equal(boss.phase,2);});
test('guardian defeat grants one reward and persists as absent',()=>{const h=harness(),boss=h.world.wild.find(m=>m.species==='guardian')!;h.world.hit(boss,10000,false);assert.equal(h.state.inventory.crystal,3);h.advance(20);assert.equal(boss.hp,0);assert.ok(h.state.flags.bossDefeated);});
test('accelerated thirty-minute fixed-step soak stays finite and save-valid',()=>{const h=harness();act(h.state,{type:'capture',species:'slime',hpRatio:.1,roll:0});h.world.setMode('camp');for(let second=0;second<1800;second++){h.world.keys.clear();h.world.keys.add(second%8<4?'right':'left');for(let f=0;f<60;f++)h.world.update(1/60);tickEconomy(h.state,1);if(second%60===0)assert.ok(parseSave(serializeGame(h.state)).ok)}assert.ok(Number.isFinite(h.world.player.x));assert.ok(h.world.player.x>=42&&h.world.player.x<=1200);assert.equal(h.state.playSeconds,1800);assert.ok(h.world.particles.length<=180);});
test('respawn timer clamps to zero and returning monster can be captured',()=>{const h=harness(),slime=h.world.wild.find(m=>m.id===8)!;slime.hp=0;slime.respawn=.025;h.world.player.x=300;h.advance(.1);assert.equal(slime.respawn,0);assert.equal(slime.hp,slime.maxHp);assert.equal(h.world.nearest()?.id,slime.id);h.world.command('capture');assert.equal(h.state.monsters.length,1);});
test('reduced motion cannot send wandering creatures off-map',()=>{const h=harness();h.state.settings.reducedMotion=true;h.world.player.x=42;h.advance(180);for(const m of h.world.wild.filter(m=>m.species!=='guardian'))assert.ok(Math.abs(m.x-m.origin)<80,`${m.species} drifted`);});
test('rejected capture produces no escape animation or cooldown',()=>{const h=harness();h.state.inventory.card=0;h.world.player.x=300;h.world.command('capture');assert.equal(h.world.player.capture,0);assert.equal(h.world.floaters.length,0);assert.equal(h.world.particles.length,0);});

test('enemy hits preserve the app respawn invulnerability and checkpoint position',()=>{const h=harness();h.state.hp=1;const boar=h.world.wild.find(m=>m.species==='boar')!;h.world.player.x=boar.x+20;boar.attack=0;h.world.hooks.damage=()=>{h.state.hp=h.state.maxHp;h.world.player.x=130;h.world.player.y=485;h.world.player.vy=0;h.world.player.hurt=3;h.world.camera=0;};h.world.update(1/60);assert.equal(h.world.player.x,130);assert.equal(h.world.player.hurt,3);assert.equal(h.world.player.vy,0);});
test('boss hit cannot overwrite checkpoint recovery with knockback',()=>{const h=harness();h.state.hp=1;const boss=h.world.wild.find(m=>m.species==='guardian')!;h.world.player.x=boss.x+100;boss.telegraph=.001;h.world.hooks.damage=()=>{h.state.hp=h.state.maxHp;h.world.player.x=130;h.world.player.y=485;h.world.player.vy=0;h.world.player.hurt=3;h.world.camera=0;};h.world.update(1/60);assert.equal(h.world.player.x,130);assert.equal(h.world.player.hurt,3);assert.equal(h.world.player.vy,0);});
