import {drawBackdrop,drawGround,drawMonster,drawPlayer,drawFacility,drawResource} from './art';
import {SPECIES,FACILITIES,captureChance,getPlayerStats,type GameState,type SpeciesId,type Action,type ActionResult,type CardId} from './model';
export type WorldMode='field'|'camp';
export type WorldCommand='jump'|'attack'|'skill'|'gather'|'capture'|'partner'|'heal';
export type TargetInfo={name:string;hp:number;maxHp:number;chance:number;boss:boolean;distance:number;groggy:boolean;species:string};
type Wild={id:number;species:SpeciesId|'guardian';x:number;y:number;origin:number;hp:number;maxHp:number;facing:number;attack:number;hurt:number;groggy:number;slow:number;respawn:number;phase:number;telegraph:number;elite:boolean};
type Resource={type:'wood'|'stone'|'herb'|'crystal';x:number;y:number;cool:number};
type Particle={x:number;y:number;vx:number;vy:number;life:number;color:string;size:number};
type Floater={x:number;y:number;text:string;color:string;life:number};
export type WorldHooks={state:()=>GameState;action:(action:Action)=>ActionResult;damage:(amount:number)=>void;restore:(amount:number)=>void;notify:(message:string)=>void;sound:(kind:string)=>void;onTarget:(target:TargetInfo|null)=>void;onPosition:(x:number)=>void;onGatherPrompt:(text:string)=>void;card:()=>CardId;onCamp:()=>void};
const GROUND=485,WIDTH=3420;
export class World{
 canvas:HTMLCanvasElement;ctx:CanvasRenderingContext2D;hooks:WorldHooks;resizeObserver:ResizeObserver;
 keys=new Set<string>();mode:WorldMode='field';paused=true;time=0;simulationTime=0;camera=0;running=true;
 player={x:130,y:GROUND,vx:0,vy:0,facing:1,grounded:true,attack:0,hurt:0,skill:0,partner:0,capture:0,shield:0};
 wild:Wild[]=[];resources:Resource[]=[];particles:Particle[]=[];floaters:Floater[]=[];
 platforms=[{x:390,y:386,w:190},{x:930,y:350,w:175},{x:1450,y:405,w:200},{x:1920,y:366,w:200},{x:2480,y:385,w:160}];
 onFrame=0;last=0;accum=0;uiClock=0;shake=0;bossSeen=false;savedX=130;partnerTime=0;
 constructor(canvas:HTMLCanvasElement,hooks:WorldHooks){this.canvas=canvas;this.ctx=canvas.getContext('2d')!;this.hooks=hooks;canvas.width=1280;canvas.height=650;this.resizeObserver=new ResizeObserver(()=>{const r=canvas.getBoundingClientRect();canvas.width=Math.max(280,Math.round(r.width/Math.max(1,r.height)*650));});this.resizeObserver.observe(canvas);
  const species:SpeciesId[]=['slime','mushroom','stump','octopus','boar','rare'];this.wild=species.map((s,i)=>this.spawn(s,630+i*410,i));this.wild.push(this.spawn('mushroom',1150,7),this.spawn('slime',380,8),this.spawn('guardian',3090,9));
  this.resources=[{type:'wood',x:190,y:GROUND,cool:0},{type:'wood',x:310,y:GROUND,cool:0},{type:'stone',x:510,y:386,cool:0},{type:'herb',x:820,y:GROUND,cool:0},{type:'wood',x:1180,y:GROUND,cool:0},{type:'stone',x:1540,y:405,cool:0},{type:'herb',x:1990,y:366,cool:0},{type:'crystal',x:2490,y:GROUND,cool:0},{type:'wood',x:2160,y:GROUND,cool:0}];this.onFrame=requestAnimationFrame(this.frame);
 }
 spawn(species:SpeciesId|'guardian',x:number,id:number):Wild{const hp=species==='guardian'?720:SPECIES[species].hp;return{id,species,x,y:GROUND,origin:x,hp,maxHp:hp,facing:-1,attack:2,hurt:0,groggy:0,slow:0,respawn:0,phase:species==='guardian'?0:id,telegraph:0,elite:species==='rare'};}
 destroy(){this.running=false;cancelAnimationFrame(this.onFrame);this.resizeObserver.disconnect();this.keys.clear();}
 setMode(mode:WorldMode){if(mode===this.mode)return;this.mode=mode;this.keys.clear();if(mode==='camp'){this.savedX=this.player.x;this.player.x=350;this.camera=0;}else this.player.x=this.savedX;this.player.y=GROUND;this.player.vy=0;this.hooks.onTarget(null);}
 setPaused(paused:boolean){this.paused=paused;if(paused)this.keys.clear();}
 emit(x:number,y:number,color:string,n=14){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=40+Math.random()*150;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s-50,life:.5+Math.random()*.5,color,size:2+Math.random()*4});}if(this.particles.length>180)this.particles.splice(0,this.particles.length-180);}
 float(x:number,y:number,text:string,color='#fff8d7'){this.floaters.push({x,y,text,color,life:1.3});}
 nearest(){return this.wild.filter(m=>m.hp>0&&m.respawn===0&&Math.abs(m.x-this.player.x)<220).sort((a,b)=>Math.abs(a.x-this.player.x)-Math.abs(b.x-this.player.x))[0];}
 command(command:WorldCommand){if(this.paused)return;const p=this.player,s=this.hooks.state();if(command==='heal'){const result=this.hooks.action({type:'heal'});if(result.ok){this.emit(p.x,p.y-30,'#a6ffd6');this.hooks.sound('heal');}return;}
  if(command==='jump'&&p.grounded){p.vy=-610;p.grounded=false;this.hooks.sound('jump');this.emit(p.x,p.y,'#e9dfbb',5);}
  if(this.mode==='camp'){if(command==='gather')this.hooks.onCamp();return;}
  if(command==='gather'){const r=this.resources.filter(r=>r.cool<=0&&Math.abs(r.x-p.x)<90&&Math.abs(r.y-p.y)<110).sort((a,b)=>Math.abs(a.x-p.x)-Math.abs(b.x-p.x))[0];if(r){const amount=r.type==='wood'?5:r.type==='stone'?4:2;const result=this.hooks.action({type:'gather',item:r.type==='crystal'?'ore':r.type,amount});if(result.ok){r.cool=r.type==='crystal'?75:12;const name=r.type==='wood'?'목재':r.type==='stone'?'돌':r.type==='herb'?'약초':'철광석';this.float(r.x,r.y-55,`+${amount+getPlayerStats(s).gatherBonus} ${name}`,'#fff0ab');this.emit(r.x,r.y-20,'#f9dc89');this.hooks.sound('gather');}}else if(p.x<170)this.hooks.onCamp();else this.hooks.notify('자원 가까이에서 E를 눌러 채집하세요');}
  if(command==='attack'&&p.attack<=0){p.attack=.34;this.hooks.sound('attack');let hit=false;for(const m of this.wild){if(m.hp<=0||Math.abs(m.x-p.x)>115||Math.abs(m.y-p.y)>95||(m.x-p.x)*p.facing < -38)continue;this.hit(m,getPlayerStats(s).attack,false);hit=true;}if(!hit)this.emit(p.x+p.facing*55,p.y-33,'#fff3bc',4);}
  if(command==='skill'&&p.skill<=0){p.skill=4.5;p.attack=.55;this.hooks.sound('skill');this.emit(p.x,p.y-35,'#8affd7',28);for(const m of this.wild)if(m.hp>0&&Math.abs(m.x-p.x)<170&&Math.abs(m.y-p.y)<120)this.hit(m,Math.round(getPlayerStats(s).attack*1.6),true);}
  if(command==='capture'&&p.capture<=0){const m=this.nearest();if(!m||Math.abs(m.y-p.y)>120){this.hooks.notify('포획할 몬스터에 더 가까이 다가가세요');return;}if(m.species==='guardian'){this.hooks.notify('숲의 수호자는 포획할 수 없어요');return;}p.capture=.85;const result=this.hooks.action({type:'capture',species:m.species,hpRatio:m.hp/m.maxHp,groggy:m.groggy>0,card:this.hooks.card()});if(!result.ok&&result.chance===undefined){p.capture=0;return;}this.emit(m.x,m.y-35,result.ok?'#ffe6a0':'#c8d5f2',30);this.hooks.sound(result.ok?'capture':'fail');if(result.ok){this.float(m.x,m.y-75,'함께 가자!','#ffdd70');m.hp=0;m.respawn=35;this.shake=4;}else this.float(m.x,m.y-65,'카드 탈출!','#fff');}
  if(command==='partner'&&p.partner<=0){const partner=s.monsters.find(m=>m.id===s.partnerId);if(!partner){this.hooks.notify('몬스터북에서 동행 몬스터를 선택하세요');return;}p.partner=9;this.hooks.sound('skill');this.emit(p.x,p.y-40,'#a9ecf0',30);if(partner.species==='slime'){p.vy=-760;p.grounded=false;}else if(partner.species==='boar')p.x=Math.max(42,Math.min(WIDTH-55,p.x+p.facing*160));else if(partner.species==='stump'){p.shield=6;this.float(p.x,p.y-65,'나무껍질 방패 · 6초','#d8e9ac');}else if(partner.species==='rare'){this.hooks.restore(30);this.float(p.x,p.y-65,'별빛 회복 +30','#b8efdf');}else if(partner.species==='mushroom'){for(const m of this.wild)if(m.hp>0&&Math.abs(m.x-p.x)<300)m.slow=7;this.float(p.x,p.y-65,'포자 구름 · 둔화','#f8c7a7');}else if(partner.species==='octopus')for(const r of this.resources.filter(r=>Math.abs(r.x-p.x)<650&&r.cool===0))this.float(r.x,r.y-55,'여기 있어요!','#ffe199');for(const m of this.wild)if(m.hp>0&&Math.abs(m.x-p.x)<260)this.hit(m,22+partner.level*3,true);}
 }
 hit(m:Wild,damage:number,breakHit:boolean){const s=this.hooks.state(),critical=Math.random()<.12;damage=Math.max(1,Math.round(damage*(critical?1.5:1)*(m.species==='guardian'?.9:1)));if(!s.monsters.length&&m.species==='slime')damage=Math.min(damage,m.hp-1);m.hp=Math.max(0,m.hp-damage);m.hurt=.18;if(breakHit&&m.species!=='guardian')m.groggy=3.5;this.float(m.x,m.y-66,`${critical?'✦ ':''}${damage}`,critical?'#ffe180':'#ffffff');this.emit(m.x,m.y-30,'#fff0b7',9);this.shake=critical?5:2;if(m.hp===0){m.respawn=m.species==='guardian'?99999:28;this.hooks.action(m.species==='guardian'?{type:'boss'}:{type:'kill',species:m.species});this.hooks.sound(m.species==='guardian'?'victory':'gather');this.emit(m.x,m.y-50,'#ffe4a5',40);}}
 frame=(stamp:number)=>{if(!this.running)return;const dt=this.last?Math.min((stamp-this.last)/1000,.05):.016;this.last=stamp;this.time+=dt;if(!this.paused){this.accum+=dt;while(this.accum>=1/60){this.update(1/60);this.accum-=1/60;}}this.draw();this.onFrame=requestAnimationFrame(this.frame);};
 update(dt:number){this.simulationTime+=dt;const p=this.player,s=this.hooks.state();for(const key of ['attack','hurt','skill','partner','capture','shield'] as const)p[key]=Math.max(0,p[key]-dt);this.shake=Math.max(0,this.shake-dt*20);p.vx=(this.keys.has('right')?1:0)-(this.keys.has('left')?1:0);if(p.vx)p.facing=p.vx;p.x=Math.max(42,Math.min(this.mode==='camp'?1200:WIDTH-55,p.x+p.vx*245*getPlayerStats(s).speed*dt));const oldY=p.y;p.vy+=1550*dt;p.y+=p.vy*dt;p.grounded=false;if(p.y>=GROUND){p.y=GROUND;p.vy=0;p.grounded=true;}if(this.mode==='field')for(const f of this.platforms)if(p.vy>=0&&oldY<=f.y+2&&p.y>=f.y&&p.x>f.x-15&&p.x<f.x+f.w+15){p.y=f.y;p.vy=0;p.grounded=true;}
  const cameraGoal=Math.max(0,Math.min(Math.max(0,(this.mode==='camp'?1280:WIDTH)-this.canvas.width),p.x-this.canvas.width*.4));this.camera+=(cameraGoal-this.camera)*Math.min(1,dt*6);
  if(this.mode==='field'){for(const r of this.resources)r.cool=Math.max(0,r.cool-dt);for(const m of this.wild){if(m.respawn>0){m.respawn=Math.max(0,m.respawn-dt);if(m.respawn===0){m.hp=m.maxHp;m.x=m.origin;m.groggy=0;m.slow=0;m.hurt=0;m.telegraph=0;m.attack=2;}continue;}m.hurt=Math.max(0,m.hurt-dt);m.groggy=Math.max(0,m.groggy-dt);m.slow=Math.max(0,m.slow-dt);m.attack-=dt;const d=p.x-m.x,boss=m.species==='guardian';if(boss&&s.flags.bossDefeated){m.hp=0;continue;}if(m.groggy>0)continue;
   if(boss&&Math.abs(d)<490){if(!this.bossSeen){this.hooks.notify('숲의 수호자 · 붉은 충격파는 점프, 머리 위 포자는 낮게 피하세요');this.bossSeen=true;}if(m.telegraph>0){m.telegraph-=dt;if(m.telegraph<=0){this.shake=11;this.emit(m.x,m.y,'#ffb07d',35);if(Math.abs(d)<(m.phase%2?300:230)&&(m.phase%2?p.y<GROUND-55:p.y>GROUND-95)&&p.hurt<=0){const hpBefore=this.hooks.state().hp;this.hooks.damage(p.shield>0?8:23);if(this.hooks.state().hp<=hpBefore){p.hurt=1.2;p.vy=-280;p.x=Math.max(42,Math.min(WIDTH-55,p.x+Math.sign(d)*40));}this.hooks.sound('hurt');}m.phase++;m.attack=m.hp/m.maxHp<.5?1.85:2.8;}}else if(m.attack<=0)m.telegraph=1.1;else if(Math.abs(d)>135)m.x+=Math.sign(d)*40*dt;m.facing=Math.sign(d);}
   else if(!boss){const aggro=m.hp<m.maxHp||m.species==='boar'||m.elite;if(aggro&&Math.abs(d)<280){m.facing=Math.sign(d);if(Math.abs(d)>52)m.x+=Math.sign(d)*(m.species==='boar'?87:52)*(m.slow>0?.5:1)*dt;if(Math.abs(d)<65&&Math.abs(p.y-m.y)<70&&m.attack<=0&&p.hurt<=0){const hpBefore=this.hooks.state().hp;this.hooks.damage(SPECIES[m.species as SpeciesId].attack*(p.shield>0?.35:1));if(this.hooks.state().hp<=hpBefore)p.hurt=1.05;m.attack=1.5;this.hooks.sound('hurt');this.float(p.x,p.y-75,'앗!','#ffb8a6');}}else{m.x+=Math.sin(this.simulationTime*.75+m.phase)*18*dt;m.facing=Math.cos(this.simulationTime*.75+m.phase)>0?1:-1;}}
  }this.partnerTime+=dt;if(s.partnerId&&this.partnerTime>2){this.partnerTime=0;const target=this.nearest();if(target&&target.hp/target.maxHp>.28&&Math.abs(target.x-p.x)<150)this.hit(target,7,false);}}
  for(const a of this.particles){a.life-=dt;a.x+=a.vx*dt;a.y+=a.vy*dt;a.vy+=160*dt;}this.particles=this.particles.filter(a=>a.life>0);for(const f of this.floaters){f.life-=dt;f.y-=32*dt;}this.floaters=this.floaters.filter(f=>f.life>0);
  this.uiClock+=dt;if(this.uiClock>.16){this.uiClock=0;const t=this.mode==='field'?this.nearest():undefined;if(t&&t.species!=='guardian'&&!s.encountered.includes(t.species))this.hooks.action({type:'encounter',species:t.species});this.hooks.onTarget(t?{name:t.species==='guardian'?'숲의 수호자':SPECIES[t.species].name,hp:t.hp,maxHp:t.maxHp,chance:t.species==='guardian'?0:captureChance(s,t.species,t.hp/t.maxHp,t.groggy>0,this.hooks.card()),boss:t.species==='guardian',distance:Math.abs(t.x-p.x),groggy:t.groggy>0,species:t.species}:null);this.hooks.onPosition(p.x);const r=this.resources.find(r=>r.cool<=0&&Math.abs(r.x-p.x)<90&&Math.abs(r.y-p.y)<110);this.hooks.onGatherPrompt(this.mode==='camp'?'캠프 시설 관리':r?`${r.type==='wood'?'나뭇가지':r.type==='stone'?'돌무더기':r.type==='herb'?'야생 약초':'철광석'} 채집`:p.x<170?'캠프로 이동':'');}
 }
 draw(){const c=this.ctx,w=this.canvas.width,h=650,t=this.hooks.state().settings.reducedMotion?0:this.time;c.clearRect(0,0,w,h);drawBackdrop(c,w,h,this.camera,t,this.mode);c.save();if(this.shake&&!this.paused&&!this.hooks.state().settings.reducedMotion)c.translate((Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);c.translate(-this.camera,0);drawGround(c,0,GROUND,this.mode==='camp'?1280:WIDTH,165,t);
  if(this.mode==='field'){for(const f of this.platforms)drawGround(c,f.x,f.y,f.w,28,t);for(const r of this.resources)if(r.x>this.camera-80&&r.x<this.camera+w+80)drawResource(c,r.type,r.x,r.y,t,r.cool>0);this.sign(c,80,GROUND,'CAMP',true);this.sign(c,1730,GROUND,'깊은 숲',false);this.sign(c,2795,GROUND,'수호자의 정원',false);
   for(const m of this.wild){if(m.hp<=0||m.respawn>0||m.x<this.camera-110||m.x>this.camera+w+110)continue;const boss=m.species==='guardian';if(m.telegraph>0){c.fillStyle=`rgba(243,110,71,${.15+Math.sin(t*15)*.06})`;c.fillRect(m.x-(m.phase%2?300:230),GROUND-(m.phase%2?230:12),m.phase%2?600:460,m.phase%2?145:18);c.strokeStyle='#ff784f';c.lineWidth=3;c.strokeRect(m.x-(m.phase%2?300:230),GROUND-(m.phase%2?230:12),m.phase%2?600:460,m.phase%2?145:18);c.font='bold 15px sans-serif';c.textAlign='center';c.fillStyle='#fff2b5';c.fillText(m.phase%2?'! 머리 위 포자 · 낮게 피하세요':'! 충격파 · 점프하세요',m.x,GROUND-150);}drawMonster(c,m.species,m.x,m.y,boss?67:29,t,{flip:m.facing<0,hurt:m.hurt>0,elite:m.elite});if(m.hp<m.maxHp||Math.abs(m.x-this.player.x)<150){const ww=boss?120:58;c.fillStyle='#193b36cc';this.round(c,m.x-ww/2,m.y-(boss?138:78),ww,7,4);c.fillStyle=m.groggy>0?'#ffe391':'#a5efbd';this.round(c,m.x-ww/2,m.y-(boss?138:78),ww*m.hp/m.maxHp,7,4);}if(m.groggy>0){c.font='16px sans-serif';c.fillStyle='#ffdc7d';c.textAlign='center';c.fillText('✦  ✧  ✦',m.x,m.y-(boss?145:90));}}
  }else{const s=this.hooks.state(),slots=[95,250,405,560,715,870,1025,1180];for(let i=0;i<8;i++){const f=s.facilities.find(f=>f.slot===i),x=slots[i];if(f){drawFacility(c,f.type,x,GROUND,t,!!f.workerId);c.font='bold 13px sans-serif';c.textAlign='center';c.fillStyle='#fff5d5';c.fillText(FACILITIES[f.type].name,x,GROUND+35);const worker=s.monsters.find(m=>m.id===f.workerId);if(worker){const buffer=Object.values(f.buffer).reduce((n,v)=>n+(v||0),0);const source=s.facilities.find(src=>Object.values(src.buffer).some(n=>(n||0)>0));const carrying=f.type==='storage'&&!!source&&!worker.resting;const sourceX=source?.id===f.id?slots[0]:slots[source?.slot??f.slot];const progress=Math.min(1,f.progress/FACILITIES[f.type].seconds);const dx=carrying?(sourceX-x)*(1-progress):Math.sin(t*.6+i)*20;drawMonster(c,worker.species,x+dx,GROUND+10,24,t,{flip:carrying?sourceX>x:Math.cos(t*.6+i)<0,sleeping:!!worker.resting});if(carrying){c.fillStyle='#d4a665';this.round(c,x+dx-9,GROUND-29,19,12,3);c.fillStyle='#fae2a1';c.fillRect(x+dx-2,GROUND-29,4,12);}const queued=s.queue.some(job=>job.facilityId===f.id);const status=worker.resting?'휴식 중 · 활력 회복':f.type==='storage'?carrying?'자원을 가방으로 운반 중':'다음 운반을 기다려요':['workbench','kitchen'].includes(f.type)?queued?'차근차근 제작 중':'다음 제작을 기다려요':buffer>=FACILITIES[f.type].capacity-3?'보관 공간이 필요해요':'열심히 작업 중';c.fillStyle='#dbf5cd';c.font='12px sans-serif';c.fillText(status,x,GROUND-125);}}else{c.setLineDash([6,8]);c.strokeStyle='#eef5c966';c.lineWidth=2;this.round(c,x-58,GROUND-70,116,76,12,true);c.setLineDash([]);c.fillStyle='#f4f6d599';c.font='24px sans-serif';c.textAlign='center';c.fillText('+',x,GROUND-25);}}}
  const s=this.hooks.state(),partner=s.monsters.find(m=>m.id===s.partnerId);if(partner)drawMonster(c,partner.species,this.player.x-this.player.facing*61,this.player.y,23,t,{flip:this.player.facing<0});drawPlayer(c,this.player.x,this.player.y,t,{flip:this.player.facing<0,moving:!!this.player.vx&&!this.paused,attack:this.player.attack,hurt:this.player.hurt>0,grounded:this.player.grounded});if(this.player.attack>0){c.save();c.translate(this.player.x,this.player.y-35);c.scale(this.player.facing,1);c.strokeStyle=`rgba(255,243,185,${this.player.attack*2})`;c.lineWidth=9;c.beginPath();c.arc(10,-3,70,-1.1,1.1);c.stroke();c.restore();}if(this.player.shield>0){c.strokeStyle='#e8edb6aa';c.lineWidth=3;c.beginPath();c.ellipse(this.player.x,this.player.y-32,38,48,0,0,Math.PI*2);c.stroke();}
  for(const a of this.particles){c.globalAlpha=Math.max(0,a.life);c.fillStyle=a.color;c.beginPath();c.arc(a.x,a.y,a.size,0,Math.PI*2);c.fill();}c.globalAlpha=1;for(const f of this.floaters){c.globalAlpha=Math.min(1,f.life*2);c.textAlign='center';c.font='900 21px sans-serif';c.lineWidth=4;c.strokeStyle='#274b40';c.strokeText(f.text,f.x,f.y);c.fillStyle=f.color;c.fillText(f.text,f.x,f.y);}c.globalAlpha=1;c.restore();
 }
 sign(c:CanvasRenderingContext2D,x:number,y:number,text:string,left:boolean){c.fillStyle='#947757';c.fillRect(x-4,y-85,8,85);c.fillStyle='#dbc69b';this.round(c,x-48,y-94,96,32,6);c.fillStyle='#486044';c.font='bold 12px sans-serif';c.textAlign='center';c.fillText(`${left?'‹ ':''}${text}${left?'':' ›'}`,x,y-74);}
 round(c:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,stroke=false){c.beginPath();c.roundRect(x,y,w,h,r);stroke?c.stroke():c.fill();}
}
